microsoft/perfview

src/TraceEvent/Computers/StartStopActivityComputer.cs
Show exception handling call stacks as a seperate activity.
This can help users notice the time spent in the exception handling logic.
=> Show exception handling call stacks as a seperate activity

src/PerfView/SupportFiles/UsersGuide.htm
- Removed an extra closing `</strong>` tag that prevented the "Memory Investigations:" label from being bolded in the users guide.
=> Minor Documentation Fix

src/TraceEvent/Computers/TraceManagedProcess.cs, src/TraceEvent/Computers/TraceProcess.cs
As I explored more complex uses of NeedProcesses and NeedLoadedDotNetRuntimes I found that the check for when to add callbacks was too aggressive.  I built a NeedThreadPool* extension for CAP and was receiving mulitiple JIT callbacks because for a given source callbacks were added mulitple times.  For more complex scenarios NeedLoadedDotNetRuntimes may be called multiple times witht the same source.
Tested with the more complex case and PerfView scenarios.
Note this case is not hit in PerfView, but as more complex external scenarios are built it is an important scenario.
=> More complex uses of Need* artitecture need to guard against redundant calls with the same source

src/TraceEvent/Parsers/KernelTraceEventParser.cs, src/TraceEvent/TraceLog.cs
Microsoft-Windows-Kernel-Memory/MemoryProcessMemInfo was showing bogus payloads because the additional payloads were added to the MemoryProcessMemInfoValues structure in Version2 and PerfView only knows how to parse the payloads from Version1. This has been happening for at least several months but we need these events for a metric we want to report in our perf tests so I'd like to get this fixed. This change makes it so TraceEvent can parse events from either version 1 or version 2.
=> Update the MemoryProcessMemInfoTraceData class so it can parse V2 of the event

src/TraceEvent/Parsers/KernelTraceEventParser.cs
This PR adds an event handler for the the Microsoft-Windows-Kernel-Memory/MemInfo event. Without this, the only way I was able to successfully listen to this event was to subscribe to the Kernel.All event and look at only events with a particular TaskName (which is not cheap since a string needs to be allocated for every kernel event).
=> Add strongly typed TraceEvent for Microsoft-Windows-Kernel-Memory/MemInfo event

src/TraceEvent/Computers/TraceManagedProcess.cs
Two similar 'used before initialized' crashes.  IsNotCompacting fails if GlobalHistory event was not seen for this GC - checked for null.  GetCondemnedReasons fails if the length of the CondemnedReasons does not include details even for the first heap - added a check to exit gracefully.
Fix for #108
=> Fix for #108 and similar code path

src/PerfView/GcStats.cs, src/PerfView/PerfViewData.cs
As part of some GC work I've been doing lately, I've been using the GCStats view quite a lot. While using it, I noticed a few things that could be improved about how PerfView generates its HTML views and thought I'd send a PR to address them. I'm not a web/UI dev, so it's pretty minimal stuff and there's nothing fancy.
This change adds some very basic styling to the generated views like GCStats, Processes, and the others that rely on table-heavy HTML.
Main changes:
- Table data is now in a monospaced font, which makes visually parsing numeric values much easier.
- As you hover over a table cell, the entire row gets highlighted. This is really helpful for horizontal tracking (especially when you're looking at a screen full of numbers representing each GC in the GCStats view).
- The …
=> Improve readability of GCStats and other views

src/TraceEvent/Computers/TraceManagedProcess.cs
When processing Linux traces, TraceEvent relies on kernel events to set key process information (like ProcessName).  This fix is a balance of impact and a targeted fix.  For traces that do not have the appropriate kernel events and if you are processing a managed process, the processname is set.
=> Set ProcessName for managed processes in Linux traces (eg. no kernel events to set it properly)

src/PerfView/CommandLineArgs.cs, src/PerfView/CommandProcessor.cs, src/PerfView/Triggers.cs
This change adds a command line option to stop collection when a background GC is encountered whose final pause takes longer than the specified number of milliseconds.
@Maoni0 PTAL
=> Add trigger to stop collection on long BGC final pause

src/PerfView/MainWindow.xaml.cs
I noticed that "Command Line Help" and "User Command Help" open in editable controls, which is not useful. This change fixes that and also removes a file path that (I think) was accidentally included in a comment.
=> Make help text editors readonly

src/EtwHeapDump/DotNetHeapDumper.cs, src/HtmlJs/PerfDataService/CallTreeDataProviderFactory.cs, src/PerfView/PerfViewData.cs, src/TraceEvent/TraceEvent.Tests/GeneralParsing.cs, src/TraceEvent/ZippedETL.cs
Correct two related typos
1. `ZippedETLReader.UnpackAchive()` --> `.UnpackArchive()`
2. Comment in `DotNetHeapDumper` "achive" --> "achieve"
Note that this is technically a breaking change because
`ZippedETLWriter.UnpackArchive()` is public
=> Correct typo in ZippedETLReader.UnpackArchive()

src/PerfView/CommandLineArgs.cs, src/PerfView/Dialogs/RunCommandDialog.xaml.cs, src/PerfView/Properties/AssemblyInfo.cs, src/PerfView/SupportFiles/UsersGuide.htm
It is useful for /GCCollectOnly to have version information on the runtime.  We can get this
by simply turning on the kernel events for Image loads.   This does not increase the size of the file
significanctly.
=> Add Image Events to /GCCollectOnly

src/PerfView/GcStats.cs, src/TraceEvent/Computers/TraceManagedProcess.cs
Actionable .NET Runtime versions are key to analysis.  Prior to .NET 4.? the RuntimeStart event did not include the qfe version (revision).  As a result many of the runtime versions are not actionable.  This change monitors KernelTraceControl/ImageID and KernelTraceControl/ImageID/FileVersion to capture the build time and version for clr.dll/mscorwks.dll.
=> Gather more details about .NET Versions for managed processes

src/TraceEvent/ETWTraceEventSource.cs, src/TraceEvent/TraceLoggingEventId.cs
1. Make TraceLoggingEventId to implement IDisposable.
2. Optimize some codes in TraceLoggingEventId for perf.
3. Fix typos.
=> Trivial fixes

src/PerfView/GcStats.cs, src/TraceEvent/Computers/TraceManagedProcess.cs
enable LOHWait analysis to look at waits due to allocating too much
enable mark times to recognize overflow marking event
check for cases where we are simply missing a PerHeapHistory event
=> various bug fixes

PerfView.sln, src/PerfView/App.cs, src/PerfView/CommandProcessor.cs, src/PerfView/Extensibility.cs, src/PerfView/MainWindow.xaml.cs, src/PerfView/PerfViewData.cs, src/PerfView/Utilities/SupportFiles.cs, src/PerfView64/App.config, src/PerfView64/App.cs, src/PerfView64/PerfView64.csproj, src/PerfView64/Properties/AssemblyInfo.cs
This change introduces **PerfView64**, a 12KiB file wrapper executable which launches **PerfView** as a 64-bit application.
In this initial form, the intent is the **PerfView64** executable would be attached to the GitHub release alongside the **PerfView** executable. Users could optionally download the executable, and would be responsible for launching through it if they need to use more memory during analysis.
Fixes #175
Fixes #171
=> Add PerfView64, a wrapper around PerfView

CONTRIBUTING.md, src/TraceEvent/Ctf/CtfTracing.Tests/CtfTraceTests.cs, src/TraceEvent/Ctf/CtfTracing.Tests/CtfTracing.Tests.csproj, src/TraceEvent/Ctf/CtfTracing.Tests/packages.config, src/TraceEvent/TraceEvent.Tests/GeneralParsing.cs, src/TraceEvent/TraceEvent.Tests/TraceEvent.Tests.csproj, src/TraceEvent/TraceEvent.Tests/packages.config
=> switch mstest projects to use xunit 

src/LinuxEvent.Tests/Constants.cs, src/LinuxEvent.Tests/EventParseTests.cs
We have a non-determinstic failure with the oneStack test because of a file acess issue.
Caused by probing for the file by concurrent tests.
Removed the probing.
=> Fix non-deterministic error with OneStack test

appveyor.yml
Currently build artifacts are only getting uploaded for the Release configuration jobs. This change updates the AppVeyor definition to include artifacts for all build jobs.
=> Fix artifact path for debug builds

src/TraceEvent/TraceEvent.Tests/GeneralParsing.cs, src/TraceEvent/TraceEvent.Tests/inputs/net.4.0.x64.baseline.txt, src/TraceEvent/TraceEvent.Tests/inputs/net.4.0.x86.baseline.txt, src/TraceEvent/TraceEvent.Tests/inputs/net.4.5.2.x64.baseline.txt, src/TraceEvent/TraceEvent.Tests/inputs/net.4.5.2.x86.baseline.txt, src/TraceEvent/TraceEvent.Tests/inputs/net.4.5.x64.baseline.txt, src/TraceEvent/TraceEvent.Tests/inputs/net.4.5.x86.baseline.txt, src/TraceEvent/TraceEvent.Tests/inputs/net.4.6.2.x86.baseline.txt, src/TraceEvent/TraceEvent.Tests/inputs/netfx.4.6.1080.0.netfxrel3stage.x64.baseline.txt, src/TraceEvent/TraceEvent.Tests/inputs/netfx.4.6.1080.0.netfxrel3stage.x86.baseline.txt, src/TraceEvent/TraceEvent.Tests/inputs/sl.5.x86.baseline.txt
Improve testing speed and granularity
* Use `StringComparer.Ordinal` instead of the current culture
* Use `[Theory]` instead of `[Fact]` to separate a test with several sub-tests
* Fix test output not showing up when run from **Test Explorer** in Visual Studio (only covers one test where I was trying to review the output)
=> Faster testing

src/EtwClrProfiler/ETWClrProfilerX64.vcxproj, src/EtwClrProfiler/ETWClrProfilerX86.vcxproj
It turns out that the header files that are needed for PerfView's ETWClrProfiler code
are in a different place in newer versions of the Windows SDK.
If you had installed an older SDK, and upgraded, the header files ended up both places and so things 'just worked'
But if you installed the SDK clean (as you do when you install VS 2017 on a new machine) it is only in the new place.
Basically add the new place to the include search paths to fix.
=> Fix it so that clean installs of 2017 works

src/LinuxEvent.Tests/LinuxTracing.Tests.csproj
This is not a functional change, but improves the experience slightly. See dotnet/roslyn#18363 for example screenshot of the difference.
=> Show LinuxTracing.Tests as a test project in Solution Explorer

PerfView.sln
Now that we switched from MSTest to XUnit, the \*.testsettings files are no longer needed.
=> Remove reference to non-existent file

src/EtwClrProfiler/ETWClrProfilerX64.vcxproj, src/EtwClrProfiler/ETWClrProfilerX86.vcxproj
In PR #238 I did not apply the fix to the Release variant.  This fixes that.
=> Fix release build include paths to match Debug build

src/PerfView/Extensibility.cs, src/PerfView/memory/HeapSnapshot.cs
Currently the heap dump for a 32-bit process only works when running PerfView as a 32-bit process. This pull request updates the code launching HeapDump to work with both PerfView and PerfView64.
=> Fix heap dump when running PerfView as a 64-bit process

src/HeapDump/ICorDebugGCHeap.cs, src/PerfView/Extensibility.cs, src/PerfView/OtherSources/XMLStackSource.cs, src/PerfView/PerfView.csproj, src/PerfView/PerfViewData.cs, src/PerfView/Triggers.cs, src/TraceEvent/Computers/TraceManagedProcess.cs, src/TraceEvent/TraceEvent.csproj
💭 In the future we can consider alternatives to `[Obsolete]` for experimental features, but for now it seemed to make sense to clean up the build.
=> Fix build warnings

src/CSVReader/ETLStackBrowse/ZL/DeflateStreamAsyncResult.cs, src/HeapDump/GCHeapDumper.cs, src/MemoryGraph/graph.cs, src/PerfView/Dialogs/RunCommandDialog.xaml.cs, src/PerfView/Extensibility.cs, src/PerfView/GuiUtilities/HistoryComboBox/HistoryCombBox.cs, src/PerfView/GuiUtilities/StatusBar/StatusBar.xaml.cs, src/PerfView/HeapView/HeapView.cs, src/PerfView/HeapView/Toolbox.cs, src/PerfView/MainWindow.xaml.cs, src/PerfView/OtherSources/XMLStackSource.cs, src/PerfView/PerfViewData.cs, src/PerfView/StackViewer/StackWindow.xaml.cs, src/PerfView/Triggers.cs, src/PerfView/memory/ClrProfilerParser.cs, src/PerfView/memory/GCHeapSimulator.cs
Consistently use the latest recommended pattern for delegate invocation (including events).
=> Use new null propagation operator to invoke delegates

src/LinuxEvent.Tests/LinuxTracing.Tests.csproj, src/PerfView.Tests/PerfView.Tests.csproj, src/TraceEvent/Ctf/CtfTracing.Tests/CtfTracing.Tests.csproj, src/TraceEvent/TraceEvent.Tests/TraceEvent.Tests.csproj
This change ensures features like Add Using and Remove Unused Usings work with documentation comments. See dotnet/roslyn#2773.
:memo: This is limited to test projects as part of a specific change I'm working on.
=> Check syntax of XML comments during a build

src/LinuxEvent.Tests/EventParseTests.cs, src/LinuxEvent.Tests/InterningTests.cs
One test had a simple mistake in the expected results which was corrected.
=> Enable two tests which are currently working

src/CSVReader/CSVReader.csproj, src/FastSerialization/FastSerialization.csproj, src/HeapDump/HeapDumpX64.csproj, src/HeapDump/HeapDumpX86.csproj, src/HeapDumpInterface/HeapDumpInterface.csproj, src/LinuxEvent.Tests/LinuxTracing.Tests.csproj, src/PerfView.Tests/PerfView.Tests.csproj, src/PerfView/PerfView.csproj, src/PerfView/memory/ClrProfilerSources.cs, src/PerfView64/PerfView64.csproj, src/PerfViewExtensions/GlobalSrc/Global.csproj, src/TraceEvent/Ctf/CtfTracing.Tests/CtfTracing.Tests.csproj, src/TraceEvent/TraceEvent.Tests/TraceEvent.Tests.csproj, src/TraceEvent/TraceEvent.csproj
This change enables some compiler warnings and errors which could not be enabled in recent releases for backwards compatibility reasons, but help to identify real problems in code.
=> Enable /features:strict in C# projects

src/TraceEvent/TraceLog.cs
This field was not providing particular value as a static variable. Changing it to an instance variable means one less thing to worry about when it comes to test determinism.
=> Make TraceLog.s_skipCount an instance variable

src/FastSerialization/FastSerialization.cs, src/FastSerialization/StreamReaderWriter.cs
This parameter indicates stream ownership, similar to the `BinaryWriter` constructor.
=> Update FastSerialization to support a 'leaveOpen' parameter

src/TraceEvent/Computers/StartStopActivityComputer.cs, src/TraceEvent/Stacks/CallTree.cs
* Make `DisableParallelism` an instance variable
* Remove static state in `StartStopActivityComputer` for an unused field
=> Remove unnecessary static state

src/TraceEvent/Utilities/command.cs
Following review of #267, it was suggested that this code be removed since it's outside the scope of the TraceEvent library and likely better implemented in individual applications.
=> Remove the disabled Ctrl+C support

src/HeapDump/HeapDumpX64.csproj, src/HeapDump/HeapDumpX86.csproj, src/HeapDump/packages.config, src/NugetSupportFiles/Microsoft.Diagnostics.Tracing.TraceEvent.SupportFiles/build/Microsoft.Diagnostics.Tracing.TraceEvent.SupportFiles.props, src/NugetSupportFiles/PerfView.SupportFiles.Populate.bat, src/NugetSupportFiles/PerfView.SupportFiles/build/PerfView.SupportFiles.props, src/PerfView/PerfView.csproj, src/PerfView/packages.config
This fixes issue #277 
A new package with updated DiagnosticHub dlls (now Dev 15).  
The vast majority of the update is updating the version for the support package.
however the key fix is to move the DiagnosticHub.Interop.dll OUT of the architecture specific directory.
=> Diag session fix 

src/PerfView/Dialogs/RunCommandDialog.xaml, src/PerfView/Dialogs/RunCommandDialog.xaml.cs
This is a naive attempt to fix #88 - I just implemented the same as for command history (with same history length == 10).
I was thinking to refactor code a little and extract concatenating logic into separate method, but decided not to, because actual logic varies a little (reg. ';' handling in items).
But if this is good idea, I can introduce that as well.
=> Remember history of additional providers

src/HeapDump/Debugger/DumpDebugging/LibraryProvider.cs
Prior to this change, the `LibraryProvider` always tried to load the V2 CLR libraries when converting a **.dmp** to a **.gcDump**. This resulted in a return code of **CORDBG_E_LIBRARY_PROVIDER_ERROR** which [results in an exception](https://github.com/Microsoft/perfview/blob/c1d0048aa563b0b902295edb46163c13a7549503/src/HeapDump/Debugger/Debugger.cs#L76).
=> Update LibraryProvider to avoid loading a v2 CLR

src/FastSerialization/StreamReaderWriter.cs, src/PerfView/CommandLineArgs.cs, src/PerfView/CommandProcessor.cs, src/PerfView/Properties/AssemblyInfo.cs, src/PerfView/SupportFiles/UsersGuide.htm
Added a link to more documenation about collecting on Linux machines.
Updated logic so that /OnlyProviders will collect addtion events if the user asks for stacks on those events (there was logic but it was geared to old syntax).
Fix a bug with creating large data that might exceed 4GB (happened with some large heap dumps).
Fixed bug where /CpuCounters argument was lost if PerfView had to elevate.
=> Several minor updates

PerfView.sln, src/LinuxEvent.Tests/LinuxTracing.Tests.csproj, src/PerfView.TestUtilities/DebugAssertionTests.cs, src/PerfView.TestUtilities/PerfView.TestUtilities.csproj, src/PerfView.TestUtilities/Properties/AssemblyInfo.cs, src/PerfView.TestUtilities/ThrowingTraceListener.cs, src/PerfView.TestUtilities/UseCultureAttribute.cs, src/PerfView.TestUtilities/WorkItemAttribute.cs, src/PerfView.TestUtilities/packages.config, src/PerfView.Tests/PerfView.Tests.csproj, src/PerfView.Tests/StackViewer/StackWindowTests.cs, src/PerfView.Tests/app.config, src/TraceEvent/Ctf/CtfTracing.Tests/CtfTracing.Tests.csproj, src/TraceEvent/Ctf/CtfTracing.Tests/app.config, src/TraceEvent/TraceEvent.Tests/TraceEvent.Tests.csproj, src/TraceEvent/TraceEvent.Tests/app.config
⚠️ This pull request builds on the work in #274, and its diff will be simplified after that one is merged. 
This change alters the behavior of `Debug.Assert`, `Debug.Fail`, and the related methods in the `Trace` class to throw exceptions rather than show the assertion UI during testing. The assertion UI would hang the AppVeyor tests making it near impossible to understand the cause of a failure.
The approach has been adopted from the one used by the Roslyn project.
=> Fix assertion handling during unit tests

src/LinuxEvent.Tests/BlockedTimeTests.cs, src/LinuxEvent.Tests/Constants.cs, src/LinuxEvent.Tests/EventParseTests.cs, src/LinuxEvent.Tests/FastStreamTests.cs, src/LinuxEvent.Tests/InterningTests.cs, src/LinuxEvent.Tests/XMLWriting.cs, src/PerfView/OtherSources/Linux/LinuxPerfScriptStackSource.cs
The tests all read from files located in source control. As long as the tests only take non-exclusive read locks, they will no longer fail due to exceptions seen during several recent AppVeyor builds.
=> Fix flaky tests due to file access errors

src/HeapDump/GCHeapDumper.cs
Previously, static fields with a name ending in `Handle` were getting renamed during heap extraction (by appending an `s`). The renaming was never meant to apply to these roots, but rather to the container nodes for handle roots.
=> Avoid renaming handle fields during extraction

src/HeapDump/GCHeapDumper.cs
`comPtr` is not necessary unique in a heap dump, but the `ccwInfo.Handle` is. This change updates the CCW node to use a unique handle so we don't try to call `SetNode` twice for the same address.
=> Fix errors related to multiple wrappers for the same object

src/HeapDump/GCHeapDumper.cs
Currently there is no command line flag for HeapDump which specifies that all objects should be extracted. This change is a simplification for the only case I ever use, without changing default values or other use cases.
=> Allow passing /MaxDumpCountK=0 to dump all objects

src/PerfView.Tests/Utilities/PerfViewTestBase.cs, src/PerfView/StackViewer/StackWindow.xaml.cs
@vancem During local testing I observed a couple issues which could cause test failures in the StackWindowTests. One of these, a reliance on `Keyboard.FocusedElement`, represents a true race condition in the product that is fixed by this.
:memo: I was not able to specifically reproduce the *hang* seen during testing, but it's possible it was some side effect of the test failing due to the above case.
=> Test hardening

src/TraceEvent/Parsers/KernelTraceEventParser.cs
The time field was simply parsed wrong.  
It is a QueryPerformanceCounter tick count.
Fixed it to decode this properly.
Fixes issue #234
=> Fix for issue ISR DPC times not decoded properly #234

src/TraceEvent/Symbols/SymbolReader.cs
Crossgened DLLs might be named XXX.dd rather than XXX.ni.dll.
However the Native PDBs for these are always XXX.ni.pdb.   Previously
we used the DLL name to make the PDB name, now we use the
emedded PDB name (which is always right).
=> Fix Crossgen symbol lookup.

src/TraceEvent/TraceUtilities/HistoryDictionary.cs
This is the attempt to fix issue #297.
I made an attempt to replace manually sorted list which spends a lot of time in linear search inside `Add` with tree-based `SortedDictionary`.
After the fix the same file is opened within half a minute as opposed to 4 minutes in the original case:
```
159 distinct processes.
Totals
2 856 343 events.
1 771 483 events with stack traces.
141 728 events with code addresses in them.
62 855 364 total code address instances. (stacks or other)
168 745 unique code addresses. 
1 699 553 unique stacks.
2 971 unique managed methods parsed.
101 257 CLR method event records.
[Conversion complete 2 856 343 events.  Conversion took 25 sec.]
A total of 168745 symbolic addresses were looked up.
Addresses outside any module: 2091 out of 168745 (1,2%)
Done with symbolic …
```
=> HistoryDictionary: Replace manually sorted list with SortedDictionary

src/FastSerialization/FastSerialization.csproj, src/TraceEvent/Microsoft.Diagnostics.Tracing.TraceEvent.nuspec
Currently the **Microsoft.Diagnostics.Tracing.TraceEvent** assembly depends on **Microsoft.Diagnostics.FastSerialization**, but no dependency was added to the NuGet package. Rather than deal with separate NuGet packages at this time, this change simply includes the dependency in the original NuGet package.
:memo: If we ever need to split these in the future, we can trivially do so and add a dependency from the current NuGet package to the new one without breaking upgrade scenarios. Since this makes distribution a little bit more complex (managing multiple NuGet releases from one repository) and didn't seem essential at this time, I chose the simplest route to packaging for my initial proposed approach.
=> Include Microsoft.Diagnostics.FastSerialization in the TraceEvent package

src/TraceEvent/Microsoft.Diagnostics.Tracing.TraceEvent.nuspec
This is missing and is an essential part of the package.
=> Add the OSExtentions DLL to the TraceEvent Nuget package

src/TraceEvent/TraceEvent.cs
This member is needed to parse events in a high performance way (no copying)
It was protected because the common scenario is to use this in TraceEvent subclasses
but it can be useful for ad-hoc pointer based parsing, so we are making it public.
=> Make The DataStart property public

src/LinuxEvent.Tests/EventParseTests.cs, src/PerfView/OtherSources/Linux/LinuxPerfScriptEventParser.cs, src/PerfView/OtherSources/Linux/LinuxPerfScriptStackSource.cs
When parsing timestamp of an event ("0.0") with the current culture set to "fr-FR", a System.FormatException is raised.
=> Fix LinuxPerfScriptEventParser when parsing timespamp event

src/TraceEvent/Computers/TraceProcess.cs
Setting Computers\TraceProcess.Start/EndRealitveMsec.  The way TraceLog\TraceProcess sets these fields is via the tracelog.  This portion of the code (as it transitions to a source based model) does not have access to the right information.  The *RelativeMsec data is stored as the process is inspected on events.
=> Set Computers\TraceProcess.Start/EndRealitveMsec

src/PerfView/GuiUtilities/StatusBar/StatusBar.xaml.cs
Fixes an occasional assertion failure (and subsequent test hang) where `EndWork` was called before `m_work` was assigned.
=> Ensure StatusBar.m_work is assigned before the work starts

.codecov.yml
This pull request serves four purposes:
1. After codecov supports inferred flags from the .codecov.yml, it will correctly¹ apply the **production** and **test** flags to our existing code base.
2. Work around a problem merging the coverage information for Debug and Release builds (which have different sequence points in the debug information) by using a filter to suppress the reports from release builds.
3. Work around a performance problem related to merging very large reports by suppressing the reports from Visual Studio 2015 builds (these will go away anyway after #319).
4. Stop showing the graphic for coverage comments in pull requests
¹ There will be some minor visual discrepancies in the codecov UI until we stop nesting test projects in the folders of production code, but I'm …
=> Improved codecov reporting and performance

.codecov.yml
Command used to validate this:
```powershell
Invoke-RestMethod -Uri https://codecov.io/validate -Body (Get-Content -Raw -LiteralPath .\.codecov.yml) -Method post
```
:link: Source: https://docs.codecov.io/docs/codecov-yaml#section-validate-your-repository-yaml
=> Fix an incorrectly quoted key in .codecov.yml

src/TraceEvent/ETWReloggerTraceEventSource.cs, src/TraceEvent/ETWTraceEventSource.cs, src/TraceEvent/NativeDlls.cs
When using  Realtime tracing the call stacks of x64 processes did come up empty because the code addresses were treated as kernel addresses which did result in the assignment of 0 (IDLE) process instead of the real processes where the stack was generated.  See issue #332
=> Fix for missing callstacks in real time Tracelog sessions (issue 332)

src/TraceEvent/TraceEvent.cs
Turns out that some ETL files have and incorrect sessionEnd time
(sometimes it is wildly too small).   This caused GCStats to give
wildly incorrect results.
The incorrect results were mostly because we forced all timestamps
to be less than sessionEndTime.   We now stop doing this.
Note that this does not affect ETLX (perfView) traces because when
the ETLX file is created we 'fix; the sessionEndTime if it is incurrect
(smaller than any of the event timestamps).
=> Fix Incorrect GCStats information when reading an ETL file directly

src/NugetSupportFiles/Microsoft.Diagnostics.Tracing.TraceEvent.SupportFiles.Populate.bat, src/NugetSupportFiles/Microsoft.Diagnostics.Tracing.TraceEvent.SupportFiles/Microsoft.Diagnostics.Tracing.TraceEvent.SupportFiles.nuspec, src/NugetSupportFiles/PerfView.SupportFiles.Populate.bat, src/PerfView/PerfView.csproj, src/TraceEvent/Symbols/SymbolReader.cs, src/TraceEvent/TraceEvent.csproj
When we updated the build scripts to use the new 2.0 CSPROJ format
we lost the fact that we emed the Interop code for the Interop.Dia2lib.dll
This caused any native symbol lookups to fail (since it is needed to interface to msdia140.dll)
It is not clear that the new build system supports embedding Interop code but we
did not really need it (We coudl just load the interop DLL for real).   However for this
to work the DLL needs to be named Dia2Lib.    It is unclear why this DLL was named
Interop.Dia2lib.dll before so we are just going to change it.
Do do this rename, we need to update the Support library package (since Interop.Dia2lib.dll
is in there), and then update to refrence the new version (with the rename).
@sharwell - if you are interested, having a test that confirms that fails if …
=> Fix native symbol lookup failure

src/LinuxEvent.Tests/EventParseTests.cs, src/TraceEvent/RegisteredTraceEventParser.cs, src/TraceParserGen/ETWManifest.cs
We had been using System.Diagnostics.Eventing.EventDescriptor in some of our PINVOKE structures that happend to exist in the Desktop Runtime
However this type was removed for NetStandard.
There was no particular reason to take this depencency (it just happened to already exist).  This change changes its use to a local defintion
(using the name EVENT_DESRIPTOR (which is how it is defined in C++ and using the C++ names for the fields (basically what we would have
done if it was just another structure needed for PINOVOKE).
This change is in peparation for compiling TraceEvent against NetStandard (not just desktop).
Also so fixed a mintor unreleated test issue that showed up during testing (added a missing [Fact] attribute).
=> Remove dependency on System.Diagnostics.Eventing.EventDescriptor

src/FastSerialization/FastSerialization.csproj, src/FastSerialization/StreamReaderWriter.cs, src/NugetSupportFiles/Microsoft.Diagnostics.Tracing.TraceEvent.SupportFiles.Populate.bat, src/NugetSupportFiles/Microsoft.Diagnostics.Tracing.TraceEvent.SupportFiles/Microsoft.Diagnostics.Tracing.TraceEvent.SupportFiles.nuspec, src/PerfView/PerfView.csproj, src/TraceEvent/Microsoft.Diagnostics.Tracing.TraceEvent.nuspec, src/TraceEvent/TraceEvent.csproj
This allows TraceEvent to be used in .NET Core scenarios.   I am likely to change details
of the package, but this is forward progress (I was able to build a TraceEvent application
in .NET Core.
I  used @sharwell's pull request #345 as a starting point, and fiddled with it to get my 
.NET Core TraceEvent app working.   I think this subsumes that PR.
=> Add NetStandard2.0 support (.NET Core) for the TraceEvent Nuget package

src/PerfView/PerfView.csproj
There is no point in having Solution Explorer show these DLLs because they are not editable.   Hide them.
=> Hide the support DLLs in the solution.

src/PerfView/PerfViewData.cs
It looks like this initialization was missing.  This fixes a warning
@puneetg1983
=> Fix warning by initializing ErrorCode variable

src/PerfView/PerfViewData.cs, src/TraceEvent/Parsers/IisTraceEventParser.cs, src/TraceEvent/Parsers/w3core.man.xml, src/TraceEvent/Parsers/w3core.mof
Regenerated the IisTraceEventParser.cs after fixing some issues in TraceParserGen. Also adding the w3core.mof and w3core.mof.man file generated as a result of TraceParserGen exe.
Updated the relevant code in PerfviewData to reflect the new function names.
=> Cleaning up the IisTraceEventParser.cs to have the right opcode names

src/PerfView/SupportFiles/UsersGuide.htm, src/TraceEvent/TraceEvent.cs, src/TraceEvent/TraceLog.cs
This allows PerfVIew users to decode the IIS events without having to install IIS ETW providers on the machine doing the analysis.
Also cleaned up an unrelated help file fix (pointing people at Github for logging feedback) in UsersGuide.htm
@puneet-gupta
=> Enable Puneet's IIS parser by default

src/TraceEvent/TraceEventNativeMethods.cs
This is not used in perf critical paths, so the simplest implementation was used.
=> Make ZeroMemory portable to Linux

src/PerfView/OtherSources/Linux/LinuxPerfScriptEventParser.cs
Stack traces from perf on Linux have method offsets appended to the method name.  This means that samples in each method are not properly aggregated.  They are aggregated at the method and offset level, not just at the method level.
Before this change:
\|   \|            \|  + System.Net.Sockets!System.Net.Sockets.Socket::SendAsync(class System.Net.Sockets.SocketAsyncEventArgs)+0xec
\|   \|            \|  \|+ System.Net.Sockets!System.Net.Sockets.Socket::SendAsync(valuetype [System.Runtime]System.ArraySegment`1,valuetype System.Net.Sockets.SocketFlags,bool)+0x8b
\|   \|            \|  \| + System.Net.Sockets!System.Net.Sockets.NetworkStream::WriteAsync(uint8[],int32,int32,valuetype [System.Runtime]System.Threading.CancellationToken)+0x118
\|   \|            \|  \|  + …
=> Strip Function Offsets from Stack Frames

src/PerfView/SupportFiles/UsersGuide.htm
The default value is 10,000 not 1,000 - https://github.com/Microsoft/perfview/blob/bf565bc8fd801c9ec86a2d33d499aa75cf10b4d6/src/PerfView/EventViewer/EventWindow.xaml.cs#L873
=> Corrected MaxRet default value in documentation

src/PerfView.Tests/StackViewer/StackWindowTests.cs
The previously reported failure appears to have been a transient issue (not reproducible).
Closes #364
=> Enable TestIncludeItemOnCallerCalleeTabCallerAsync

src/PerfView/PerfViewData.cs
Combining ASP.NET events with the IIS events so that we can get a combined view of all the pipeline events that happen for ASP.NET. The advantage of doing this along with the existing ASP.NET view is that the end user gets a better picture of both the combined events in one shot and can drill down faster than by looking at IIS or ASP.NET events individually.
=> Adding ASP.NET events to the IIS Parser to get a combined view

src/PerfView/App.cs, src/PerfView/OtherSources/Linux/LinuxPerfScriptStackSource.cs, src/PerfView/PerfView.csproj, src/PerfView/PerfViewData.cs, src/PerfView/SupportFiles/UsersGuide.htm, src/TraceEvent/Parsers/KernelTraceEventParser.cs, src/TraceEvent/Symbols/SymbolReader.cs, src/TraceEvent/TraceEvent.Tests/EventPipeParsing.cs, src/TraceEvent/TraceEventSession.cs, src/TraceEvent/TraceLog.cs
This makes PerfVIew mostly work for RS3.   Some unmanaged symbol lookup of OS DLLs may not work until the OS fixes some things, but mostly it works.    
There are some hacks here that hopefully will be backed out soon under the !CONTAINER_WORKAROUND_NOT_NEEDED ifdef when the OS is fixed.   
Also did some unrelated updates
1) Simple Linux scripting fix.
2) Turn off splash screen when /logFile is being used
3) Removed dead code in EventPipe test
4) Added TraceCodeAddress support for PMCCounterProfTraceData
5) Strip out support we dont' care about any more for source code lookup on pre 4.6.1 runtimes
=> Added support for Windows Containers.

src/TraceEvent/Parsers/KernelTraceEventParser.cs, src/TraceEvent/TraceEvent.cs, src/TraceEvent/TraceEventSession.cs, src/TraceEvent/TraceLog.cs
Basically in the SysCall events don't have process or thread IDs but we DO collect stacks, which have these things.
We already had logic that uses these stacks to fix events without thread IDs and so we just extend this for Process IDs.
Also changed it so that the stack is on the 'SysCall' exit since that has better information (the return code).
If you don't care about syscalls (almost no one does, you can ignore this).
=> Fixes for SysCall support in PerfView 

src/HeapDump/HeapDump.csproj, src/PerfView/CommandLineArgs.cs, src/PerfView/CommandProcessor.cs, src/PerfView/EventViewer/EventWindow.xaml.cs, src/PerfView/Extensibility.cs, src/PerfView/PerfView.csproj, src/PerfView/PerfViewData.cs, src/PerfView/PerfViewLogger.cs
This was put in as a 'direct' command understood by PerfView directly.   Moved it to be
a user command.  We have wanted to do this for a while because this command is not really
that central, and we do it now becuase it is convinient for making a .NET Core version
of the PerfView collector (for Nano-OS).
FetchSymbolsForProcess has dependencies on code that are related to the GUI which is
not available on .NET Core.   By moving to be an extension, we make the 'core' parts
of perfview less entagled with the GUI which makes the port easier.
I also happened to rename PerfViewEventSource.cs to PerfViewLogger.cs, because that
is the name of hte class in that file.   This is just cleanup.
=> Moves FetchSymbolsForProcess to be a user command.

src/PerfView/OtherSources/Linux/LinuxPerfScriptEventParser.cs, src/PerfView/Utilities/FastStream.cs
Basically linux processes can have / and spaces and numbers in their names, fooling our parser logic.
Now we look ahead to find a pattern of spaces, digits slash digit (which is the next field).   So as long as
the process name does not have this pattern, we are OK.
=> Fix for issue 166, (FormatException of Linux CPU Trace)

src/PerfView/OtherSources/FileSizeStackSource.cs, src/PerfView/SupportFiles/UsersGuide.htm
It may be surpising that a console window is created when you specify /LogFile (which implies no-gui) when using the 'collect' command
This is because without the console you have no way to stop the collect.   However if you specify /MaxCollectSec it won't generate the console.
Document that.
=> Clarify when new console window is created.

src/PerfView/SupportFiles/UsersGuide.htm, src/TraceEvent/TraceEvent.csproj
In preparation for publishing the TraceEvent Nuget package out of this branch, I am updating its version number to 2.0.
While there has not been a big breaking change, the code base has changed a bunch since the last time the nuget package was
updated and this warns people that it is a non-trivial step
Also made an unreleated doc update to UsersGuide.htm
=> Update TraceEvent's version number to 2.0

src/PerfView/SupportFiles/UsersGuide.htm
I am now following the tutorials from [channel9](https://channel9.msdn.com/Series/PerfView-Tutorial/PerfView-Tutorial-2-A-Simple-CPU-Performance-Investigation) and found that the docs are not up to date.
GUI was updated to use text "Metric/Interval" instead of "metric/msec". I think that it is a very important information so I made it **bold** and starting in new line. Moreover I added the comment what does it mean when the value is low (also mentioned in the video tutorial but not described in the docs)
btw. It's a cool feature!
=> docs: rename "Metric/msec" to "Metric/Interval" (as in UI) + mention what if the value is low

src/PerfView/StackViewer/StackWindow.xaml.cs
Currently, the user needs to select "First" and "Last" columns cells to make "Set Time Range" menu item work.
This is rather non-intuitive, you most probably use keyboard shortcuts so you don't hit this issue.
The PR is trivial. Single cell selected? If it's CallTreeNode, use the right values to set the time filter.
=> make Set Time Range work for single cell selection

src/TraceEvent/TraceLog.cs
@heejaechang This bug is the reason why we weren't seeing correct allocation data this past week.
=> Create new thread objects when necessary to avoid assigning events to the wrong thread

src/PerfView/PerfViewData.cs
This pull request fixes a NullReferenceException which was happening in AddGenericStopEventToRequest method and this adds additional details of CLR Exceptions in the Failed Requests view under IIS Statistics
=> Fixing NRE in IIS Stats view and adding CLR exception details in failed requests view

src/Directory.Build.props, src/LinuxEvent.Tests/LinuxTracing.Tests.csproj, src/PerfView.TestUtilities/PerfView.TestUtilities.csproj, src/PerfView.Tests/PerfView.Tests.csproj, src/PerfView.Tests/Utilities/PerfViewTestBase.cs, src/TraceEvent/Ctf/CtfTracing.Tests/CtfTracing.Tests.csproj, src/TraceEvent/TraceEvent.Tests/DispatchTests.cs, src/TraceEvent/TraceEvent.Tests/TraceEvent.Tests.csproj
Fixes test explorer behavior in some Visual Studio 2017 updates.
:memo: Please make sure to not rebase or squash this change during the merge process.
=> Update to xunit 2.3.0

src/PerfView/PerfViewData.cs, src/TraceEvent/TraceLog.cs
The Process/File/Registry view had a infinit loop because the
parent process ID formed a loop.   Use the 'Parent' field instead
of the ParentID field and insure that this field never forms loops
(by giving up on pointing to a parent if it would form a loop).
=> Avoid loops in process parent.

src/PerfView/CommandLineArgs.cs
Reduces the chance of missed events.
I was missing some events (often thousands) measuring Visual Studio even though I have NVMe drives and 28 logical processors. With this change, the events are no longer dropped.
:memo: Please make sure to not rebase or squash this change during the merge process.
=> Increase the default buffer size to 256MiB

src/TraceEvent/Ctf/CtfTraceEventSource.cs, src/TraceEvent/ETWTraceEventSource.cs, src/TraceEvent/EventPipe/EventPipeEventSourceV1.cs, src/TraceEvent/TraceEvent.cs, src/TraceEvent/TraceEventNativeMethods.cs, src/TraceEvent/TraceEventSession.cs
I tried other approaches as well:
1. Using `initblk` via `ILGenerator` (fast but high overhead)
1. Using `UnmanagedMemoryStream` to wrap a `byte*` and calling `SetLength` (incurs allocation penalty or object sharing costs)
The approach I used in this pull request is simple, but in the end it works well for each case.
=> Remove TraceEventNativeMethods.ZeroMemory

src/Directory.Build.props, src/PerfView/PerfViewData.cs, src/PerfView/SupportFiles/UsersGuide.htm, src/PerfView/memory/GCHeapSimulator.cs, src/PerfView/memory/GCPinnedObjectAnalyzer.cs
Added the Gen2 Object Death view that use the 100KB allocation events (coarse sampling).  Thus most traces
will now have this view (inncluding the /GCOnly view).   This view shows you were you allocated objects that
then die in Gen 2 (These are the
most important for reducing the number of Gen2 GCs (and Gen 2 GC fragmentation)).   You coudl do this before
when you truned on /DotNetAlloc or /DotNetAllocSampled collection but those are more expensive and can have
logistic issues (you can't attach to a existing process).    The view will only show you a coarse sampling
but that often has useful information.
Added the 'GC Occured Gen(X)' frame to the GC Heap Net Alloc and GC 2 Object Death views.   These are
useful for seeing where the GCs in time without having to go to the GCStats or Events …
=> Added the Gen 2 object Deaths view for 100K Sampling

src/TraceEvent/Stacks/CallTree.cs
:memo: Please make sure to not rebase or squash this change during the merge process.
=> Improve the performance of CallTreeNode.AllCallees

src/HtmlJs/PerfDataService/Views/static/help.html
The documentation implied that you only had to match one IncPat for a sample to be included, which isn't correct. This was particularly confusing since the documentation continued discussing an OR operator.
=> Clarify documentation for IncPats

src/Directory.Build.props, src/PerfView/CommandProcessor.cs, src/PerfView/SupportFiles/UsersGuide.htm
We need to install a .NET Profiler via the registry for some PerfView operations.
We were not being agressive enough to clean up even, if things are partly wrong.
This can leave stale state behind.  This improves the robustness.
=> Fix logic that touches registry to be very robust

src/PerfView/OtherSources/Linux/LinuxPerfScriptEventParser.cs
As of .NET Core 2.0, crossgen no longer includes the .ni.dll suffix for native images.  PerfView still expects the .ni.dll suffix, and so it is not able to resolve any NGEN or R2R image symbols.
This PR fixes the issue in a backwards compatible way, allowing resolution of the image with or without the ni suffix.
=> Fix Linux NGEN/R2R symbols

src/PerfView/GcStats.cs
Fixes #324 
I've not supplied any tests as the code in `GcStats.ToHtml(...)` is not easily testable.
=> Encode type name in Finalized Object Counts

src/PerfView/GuiUtilities/StatusBar/StatusBar.xaml, src/PerfView/GuiUtilities/StatusBar/StatusBar.xaml.cs
A few times I did not notice that an error message had been written to the status bar. This change causes error message text (but not other messages) to briefly bold twice so the error is not overlooked then return to normal weight. I did some experimentation and this did the job without being irritating.
=> Make error text bold briefly in the status bar

src/PerfView/App.cs
The native DLLs we have for 64 bit do not work on old OSes.
Give a clean error that tells people what to do
=> Give a clean error if runing 64 bit on old oses

src/HeapDump/GCHeapDumper.cs, src/PerfView/PerfViewData.cs, src/PerfView/memory/ImageFileMemoryGraph.cs, src/PerfView/memory/PdbScopeMemoryGraph.cs, src/TraceEvent/Symbols/NativeSymbolModule.cs, src/TraceEvent/Symbols/PortableSymbolModule.cs, src/TraceEvent/Symbols/SymbolReader.cs, src/TraceEvent/TraceEvent.csproj, src/TraceEvent/TraceLog.cs
With this change you can do goto source on code that was built using portable PDBs and it will work.
The following Renames in TraceEvent were done (these are breaking changes), but are simple renames
SymbolModule -> NativeSymbolModule  and
OpenSymbolFile -> OpenNativeSymbolFile  which is what existing code should call.
We now have a hierarchy where ManagedSymbolModule is at the base contract and NativeSymbolModule is a contract subclass.   Logically WIndows PDBs subclass NativeSymbolModule (but today they ARE NativeSymbolModule), and PortablePDBs subclass ManagedSymbolModule. 
This allows much of the symbol logic to be shared for both portable PDBs.  There is more factoring that can be done, but this is a good step in the right direction.  
Note that making goto Source work with …
=> Added Support for Portable PDBs.   PerfView will now open either kind of PDB

src/PerfView/GuiUtilities/StatusBar/StatusBar.xaml.cs
A change to highlight errors on the status bar did not take into account the fact that
logError could be called off the GUI thread and needs to explicitly switch threads when
it does GUI operations.   Fixed this.
=> Fix error when writing error to status bar

src/TraceEvent/RegisteredTraceEventParser.cs
Event processing which involved registered events currently fails on Linux when this parser tries to load tdh.dll (which is a Windows binary)
This PR fixes this by skipping steps in the lookup process which involve these calls.
=> Ensure RegisteredEventParser does call into tdh.dll on non-Windows platforms

src/Directory.Build.props, src/PerfView/PerfView.csproj, src/PerfView/SupportFiles/UsersGuide.htm
Add System.Runtime.InteropServices.RuntimeInformation to PerfView payload because it is not always present on older runtimes.   By also carrying it as a private DLL it insures it works regardless of the version of the .NET Runtime PerfVIew runs on.
=> Fix RuntimeInformation DLL loading issue

src/PerfView/App.cs
Fix bug where PerfView64 does not launch as a 64 bit app when run off a network share.
Also fixed but running 64 bit on win 10.
=> Fix bug where PerfView64 does not launch as a 64 bit app 

src/MemoryGraph/graph.cs, src/PerfView/EtwEventSource.cs, src/PerfView/EventViewer/EventWindow.xaml.cs, src/PerfView/Extensibility.cs, src/PerfView/PerfViewData.cs, src/TraceEvent/RegisteredTraceEventParser.cs
This fix is in RegisteredTraceEventParser.  The issue is that events generated by the MetaData events were
being logged by ANY parser that derived from ExternalTraceEventParser.  There are now two (EventPipeTraceEventParser)
which caused the events to be delivered twice.   Fixed by moving these events into JUST RegisteredTraceEventParser.
All other fixes are minor logging, whitespace and spelling fixes.
=> Fix double dispatch for some events

src/PerfView/StackViewer/StackWindow.xaml.cs
Also fixed a typo in a method name.
New code for 'View' menu assumed a strong relationship between index in various GUI arrays.   Changed to work off of names (and to be robust)
Use the ?w=1 to avoid seeing whitespace diffs.
=> Fix crash when 'Drill Into' is used.

src/TraceEvent/TraceLog.cs
A previous fix (made on 12/20/17) has an affect on ETLX files but I did not bump the version number to force rebuild of the ETLX file.
Doing so here, so that the fix becomes 'visible' even for ETL files that have a cached ETLX file.
=> Bump ETLX version number

src/TraceEvent/TraceEvent.csproj
Csproj contained invalid xml comment.
`error MSB4025: The project file could not be loaded. An XML comment cannot contain '--', and '-' cannot be the last character. Line 142, position 9.`
=> remove invalid xml comment which makes build fail

src/TraceEvent/TraceEvent.cs
Added a hook right before event dispatch so that 1) programs can gain frequent access to the processing thread and 2) events can be filtered before dispatch.  The primary scenario is to allow a multi-threaded application inspect data accumulated on the source by using a synchronization mechanism in the dispatch hook.
The primary scenario for the DispatchHook is when a secondary thread wants to inspect the contents of accumulators (like TraceManagedDotNetRuntime) during a live ETW session.  The pattern would be to add a hook which sets a manual reset event.  This synchronization will block further processing as the secondary thread inspects the state, and is largely an no-op when no inspection is necessary.
=> Added a Dispatch Hook to enable locking process thread and event filtering

src/PerfView.Tests/StackViewer/StackWindowTests.cs
@vancem I was finally able to reproduce this by setting the display scaling to 200% before running tests.
Closes #354
=> Fix sporadic failures in UI testing

src/PerfView/OtherSources/XMLStackSource.cs, src/PerfView/PerfViewData.cs, src/TraceEvent/Stacks/Stacks.cs, src/TraceEvent/TraceLog.cs
There is some logic that parses paths in TraceEvent.  They were wired to use Windows \
Change it so that / also works.
Note that this makes things consistant with the System.Path (which accepts either as a directory separator.
=> Make Path Parsing logic work with slashes and backslashes.

src/PerfView/StackViewer/CallTreeView.cs, src/PerfView/StackViewer/StackWindow.xaml.cs
Whenever I clicked ExpandAll the app was freezing and it took a lot of time to do the job.
I used PerfView to profile itself and it turned out, that by default the expanded node was being selected after expanded. This envolved scroll of the grid, which took a lot of time.
The solution: don't select nodes when Expanding All.
Result:
=> Immediate ExpandAll

src/TraceEvent/TraceLog.cs
Today if there is an exception when processing some events in a TraceLog real time session. it wil tear down the process.
This is because we need another thread to process kernel events and if an exception
happens there it reaches the base of that thread.    Instead of using Threads, use
Tasks which automatically capture exceptions thrown in them and re-raise them
when the Task is waited upon.  This is what we want here, so the fix was very easy.
This fixes issue #399
=> Make TraceLog real time sessions handle exceptions well.

src/Directory.Build.props, src/PerfView/SupportFiles/UsersGuide.htm, src/TraceEvent/Symbols/NativeSymbolModule.cs, src/TraceEvent/Symbols/PortableSymbolModule.cs, src/TraceEvent/Symbols/SymbolReader.cs
This allows the 'Goto Source' functionality to work on PDBs (Microsoft or Portable) that uses SourceLink to describe how to fetch the source.  This is the mechanism used in .NET Core and thus Goto Source 'Just works' on .NET Core V2.0.3 or later.
=> Support SourceLink in Microsoft PDBs

src/LinuxEvent.Tests/LinuxTracing.Tests.csproj, src/LinuxEvent.Tests/xunit.runner.json, src/PerfView.Tests/PerfView.Tests.csproj, src/PerfView.Tests/xunit.runner.json, src/TraceEvent/Ctf/CtfTracing.Tests/CtfTracing.Tests.csproj, src/TraceEvent/Ctf/CtfTracing.Tests/xunit.runner.json, src/TraceEvent/TraceEvent.Tests/TraceEvent.Tests.csproj, src/TraceEvent/TraceEvent.Tests/xunit.runner.json
I am currently working on Dell XPS 13*, it's hard to work with very long method names. 
By default xunit uses namespace.typeName.methodName for test names.
This PR tells it to use just methodName
Before:
After:
=> tell xunit to use method name as every test name instead of namespace.class.methodName

src/TraceEvent/TraceEvent.Tests/EtlTestBase.cs, src/TraceEvent/TraceEvent.Tests/EventPipeTestBase.cs
The input data was recorded with "en-US" culture so when I run it with polish it fails (different delimiters).
This PR enforces the "en-US" culture for parsing tests.
=> enforce "en-US" culture for parsing-based tests which are based on "en-US" input data

src/FastSerialization/FastSerialization.cs
Fast serialization has blob support but it requires using forward references which may not be desirable.   
Add support for blobs.
Note that this needs to be added proactively so that as many 'old' serializers at least know how to skip blobs.
=> Add support for Blobs (that don't use forward refs) in FastSerialization

src/TraceEvent/ETWTraceEventSource.cs, src/TraceEvent/TraceEvent.cs, src/TraceEvent/TraceLog.cs
We have some logic for keeping some data structures from growing in an unbounded way when using TraceLog with real time sessions (that live forever).
This logic was early, I have moved it late when the number of events 'in flight' (Not dispatched to the user), is at its smallest, and then only remember a number appropriate for that number of events. This makes cleanup less costly, but perhaps more importantly insures that do not trim these tables too soon (which could happen before).
@Alois-xx
=> Improved real time tracelog cleanup code a bit.

src/TraceEvent/Computers/TraceManagedProcess.cs, src/TraceEvent/Computers/TraceProcess.cs, src/TraceEvent/TraceEvent.cs
Added a Lifetime tracking mechanism for TraceEvent Computers.  The contract is that for primary caches they should consult the source if there is a lifetime model being applied, if so trim the cache based on the minimum relative timestamp (remove everything earlier).  This is a best effort mechanism to ensure that information is not accumulated indefinitely.
TraceGC.PinnedPlugs and PinnedObjects are now lazy initialized and eagerly cleaned up to further help keep accumulated memory consumption as low as possible.
The primary scenario is for live ETW sessions that want to run for long periods of time (or forever).  The mechanism will provide a best effort to restrict future memory growth by trimming core caches based on the lifetime provided to the source.  
Parameters:
Lifetime - The …
=> Add source.AddProcessLifetimeLimits as a mechanism to reduce how much information that computers accumulate

.gitignore, documentation/Downloading.md, documentation/TraceEvent/TraceEventLibrary.md, src/Directory.Build.props, src/PerfView/Properties/launchSettings.json, src/TraceEvent/DynamicTraceEventParser.cs, src/TraceEvent/EventPipe/EventPipeFormat.md
Also updated the docs a bit.
Previously it was an error if an event had more fileds than were serialized.
Now it simply makes the 'extra' fields empty.   This allows versioning (you can add more fileds, but if
some older EventSource does not create the new fields, it is not an error, you simply just don't get the
information.  This makes for better versioning.
=> Allow Events to have too more fields than have been serialized.

src/PerfView/StackViewer/CallTreeView.cs, src/PerfView/StackViewer/ColorValidatorConverter.cs, src/PerfView/StackViewer/PerfDataGrid.xaml, src/PerfView/StackViewer/PerfDataGrid.xaml.cs, src/PerfView/StackViewer/StackWindow.xaml, src/PerfView/StackViewer/StackWindow.xaml.cs, src/TraceEvent/Stacks/CallTree.cs
This change allows row colors of the perf data grid to be set to either red, blue, or brown.
A nice feature to have when staring at two different call stack trees.
=> Enable row color changes

.editorconfig
The previous settings were applying to file types which didn't match these settings. The main case was project files, but for now we simply restrict the .editorconfig settings to **\*.cs** until if/when we figure out other cases where we want specific settings.
=> Restrict .editorconfig to *.cs

src/NugetSupportFiles/Microsoft.Diagnostics.Tracing.TraceEvent.SupportFiles.Populate.bat, src/NugetSupportFiles/Microsoft.Diagnostics.Tracing.TraceEvent.SupportFiles/Microsoft.Diagnostics.Tracing.TraceEvent.SupportFiles.nuspec, src/OSExtensions/OSExtensions.csproj
This PR contains preparatory steps to produce a new TraceEvent SupportFiles nuget package.  The following changes are included:
1. Add signing support for OSExtensions.dll.
2. Update the nuget package population script to ensure that it pulls the freshly built OSExtensions.dll into the package for both net45 and netstandard1.6.
3. Increase the version of TraceEvent.SupportFiles in the nuspec to 1.0.13.
Once this PR is merged, the official build can be modified to build and sign OSExtensions.dll.
cc:@jorive
=> Prepare to Update Microsoft.Diagnostics.Tracing.TraceEvent.SupportFiles Nuget Package

Nuget.config, src/Directory.Build.props, src/TraceEvent/Microsoft.Diagnostics.Tracing.TraceEvent.nuspec
This updates TraceEvent to use a netstandard1.6 OSExtensions.dll for the netstandard1.6 version of TraceEvent.  Prior to this change TraceEvent is inadvertently using a net45 version of OSExtensions.dll which does not work on versions of .NET Core prior to 2.0.
Note - the addition of the dotnet-core MyGet feed is because the TraceEvent.SupportFiles package is posted on MyGet.
=> Consume TraceEvent.SupportFiles 1.0.13

src/TraceParserGen/ETWManifest.cs
Fixing an issue that make parser generation failed when providers are defining custom opcodes.
In manifests files (like wpf-etw.man) opcodes are defined this way:
``` xml  
<task name="WClientMeasure" symbol="TWClientMeasure" value="26" eventGUID="{3005e67b-129c-4ced-bcaa-91d7d73b1544}">
<opcodes>
<opcode name="MeasureAbort" symbol="OP_MEASURE_ABORT" value="10" />
<opcode name="MeasureElementBegin" symbol="OP_MEASURE_ELEMENT_BEGIN" value="11" />
<opcode name="MeasureElementEnd" symbol="OP_MEASURE_ELEMENT_END" value="12" />
</opcodes>
</task>
```
The current Provider method is calling a `reader.Skip()` after reading a task, which is skiping children, and opcodes are never loaded.
=> TraceParserGen: fix provider opcodes loading

src/TraceEvent/Symbols/SymbolReader.cs
This is bringing back old code that was removed because it was not available on NetStandard 1.6
and seemed to not matter.
Fixes issue #571
=> Fix problem fetching from some symbol servers.

src/Directory.Build.props
Prior to the release of TraceEvent 2.0.5, the TraceEvent version was already set to 2.0.5 in preparation for a future release.  This PR sets things up for 2.0.6 release in the future.
=> Increase TraceEvent Package Version

src/TraceEvent/EventPipe/EventPipeEventSource.cs, src/TraceEvent/Microsoft.Diagnostics.Tracing.TraceEvent.props
Causes grief in an ASP.NET Scenario.   
The changes in EventPipeEventSource.cs are all whitespace and non-semantic.
=> Fix trace relogger ref

src/PerfView/StackViewer/FlameGraph.cs, src/PerfView/StackViewer/FlameGraphDrawingCanvas.cs, src/PerfView/StackViewer/StackWindow.xaml, src/PerfView/StackViewer/StackWindow.xaml.cs
As reported internally drawing Flame Graphs for some very big data sets was too slow (could even take few minutes). 
This PR solves the problem by replacing `FrameworkElement` with `DrawingVisual`.
`DrawingVisual` is simpler and faster. However, it does not support ToolTips OOTB so I had to implement this. I don't feel good about it, but I did not find any better idea.
For provided `.etl` file the time for drawing flame graph got from 5 minutes to 2 seconds.
I have also improved the way text is scaled and wrapped.
=> Improved performance of drawing Flame Graph

src/TraceParserGen/ETWManifest.cs, src/TraceParserGen/TraceParserGen.cs
Some manifest files have values greater than 32 bits, i.e. 0x80000000.  Add an (unchecked) type when creating an enum in these cases.
=> Add (unchecked (int)) to enum values greater than 32 bits)

src/TraceEvent/Symbols/NativeSymbolModule.cs
By default - .NET native compilers do not generate a $#_ prefix for the methods coming from the assembly containing System.Object - most of the time, it should be System.Private.CoreLib.dll
=> Change fallback module name

src/TraceEvent/EventPipe/EventPipeEventSource.cs, src/TraceEvent/EventPipe/EventPipeFormat.md, src/TraceEvent/EventPipe/EventPipeTraceEventParser.cs
There are two commits and it may be useful to view them separately.
The first commit just fiddles with comments, and renames things, and does a small amount of method 
contract simplification.  
The second commit removes a redundant table from the parser (there was already a table that did 
exactly what is needed).
=> Event pipe cleanup

src/PerfView/PerfViewData.cs
When the etlx in the cache is invalid for the current version of the PerfView, delete the etlx in the cache and try to open it again.
=> Remove cached etlx file and try again for netperf

src/Directory.Build.props, src/TraceEvent/Microsoft.Diagnostics.Tracing.TraceEvent.nuspec, src/TraceEvent/TraceEvent.csproj
Previously this was a Netstandard 1.6 build and it had some features turned off.
=> Make TraceEvent have a specific build for Netstandard2.0

src/PerfView/App.cs, src/PerfView/CommandLineArgs.cs, src/PerfView/CommandProcessor.cs, src/PerfView/Dialogs/RunCommandDialog.xaml.cs, src/PerfView/EtwEventSource.cs, src/PerfView/PerfViewLogger.cs, src/TraceEvent/Parsers/KernelTraceEventParser.cs, src/TraceEvent/TraceEvent.cs, src/TraceEvent/ZippedETL.cs
* Added NoNGenPdbs (useful for .NET Core scenarios which don't need them)
* Fixed issues with logging the CPU Counter IDs, (eg Cache Misses ...) (needs more work but this is a start).
* Allowed ProcessorNumber to be viewed on any event.
* Decoded another variation of the kernel interrupt Service routine event (which is used on newer OSes).
* Fixed bug where collection log is not put in the ZIP if there are no symbol files (like when you use NoNGenPdbs)
=> Small PerfView improvements

src/TraceEvent/Microsoft.Diagnostics.Tracing.TraceEvent.props
Problem reported by Ben Teitler if you use the library to collect data on the Desktop runtime.
=> Fix for DLL not found on Desktop for TraceEvent when collecting

Nuget.config, src/Directory.Build.props, src/PerfView/CommandLineArgs.cs, src/PerfView/CommandProcessor.cs, src/PerfView/Extensibility.cs, src/PerfView/PerfViewData.cs, src/PerfView/UserCommands.cs, src/TraceEvent/Symbols/NativeSymbolModule.cs, src/TraceEvent/TraceLog.cs
1. Added a ContinOneError option when creating an ETLX file.  Basically if there is an error reading the input it simply stops converting and makes an ETLX file out of what it has.  This is useful when there corruption, but it is not at the start.  This not the default.   PerfView uses it when the /ContinueOnError option is given.
2. Fixed issue with msdia140 not working on .NET Core properly (we were using foreach which drags in conversion routines not supported on .NET Core.
3.  Added an explict reference to nuget.org when looking up packages.  We have had people trying to build PerfView in environments that don't have this reference (they have a clone).
4.  Added a 'ThreadState' entry ot the 'Blocked CSwitch' stack in the 'AnyStacks view'.  This is useful.
=> ContinueOnError, minor fixes

src/PerfView/App.cs, src/PerfViewCollect/PerfViewCollect.csproj
There are a couple of issues that showed up when I tried to capture data on an ARM32 device running Win10:
- Self-contained publishes of PerfViewCollect fail to start because they seem to select an old version of .NET Core 2.0 that is missing a type needed by PerfViewCollect (ByReference<T>).  This is solved by requiring .NET Core 2.0.5.  This is what my machine was using by default when running against the shared framework.
- SupportFiles were being unpacked but were not being used for DLL loading.  This is because the loader found TraceEvent and its dependencies next to the app, which is what one would expect for a .NET Core build.  Furthermore, because the files have a different timestamp when they are unpacked, this results in an exception because PerfView tries to make sure that …
=> Fix PerfViewCollect Breaks

src/PerfView.TestUtilities/ThrowingTraceListener.cs, src/TraceEvent/Symbols/SymbolReader.cs, src/TraceEvent/TraceEvent.Tests/GeneralParsing.cs, src/TraceEvent/TraceEvent.Tests/inputs/net.4.0.x64.baseline.txt, src/TraceEvent/TraceEvent.Tests/inputs/net.4.0.x86.baseline.txt, src/TraceEvent/TraceEvent.Tests/inputs/net.4.5.2.x64.baseline.txt, src/TraceEvent/TraceEvent.Tests/inputs/net.4.5.2.x86.baseline.txt, src/TraceEvent/TraceEvent.Tests/inputs/net.4.5.x64.baseline.txt, src/TraceEvent/TraceEvent.Tests/inputs/net.4.5.x86.baseline.txt, src/TraceEvent/TraceEvent.Tests/inputs/net.4.6.2.x86.baseline.txt, src/TraceEvent/TraceEvent.Tests/inputs/netfx.4.6.1080.0.netfxrel3stage.x64.baseline.txt, src/TraceEvent/TraceEvent.Tests/inputs/netfx.4.6.1080.0.netfxrel3stage.x86.baseline.txt, src/TraceEvent/TraceEvent.Tests/inputs/sl.5.x86.baseline.txt, src/TraceEvent/TraceEvent.cs, src/TraceEvent/TraceLog.cs
The issue was that a previous change to attribute the PDB
signature to the DLL fixed one case but broke another.
In particualr if several DLL loads have the same timestamp
the logic can get confused.    Fixed this case.
Also added the number of usec for the QPC tick count when
you dump and event (some events use these ticks).
=> Fixed issue where PDBS for DLL were not found.

src/PerfView.TestUtilities/ThrowingTraceListener.cs, src/TraceEvent/TraceEvent.Tests/EtlTestBase.cs, src/TraceEvent/TraceEvent.Tests/EventPipeTestBase.cs, src/TraceEvent/TraceEvent.Tests/GeneralParsing.cs, src/TraceEvent/TraceEvent.Tests/TestBase.cs, src/TraceEvent/TraceEvent.cs, src/TraceEvent/TraceLog.cs
…Fix this.
Basically we were turning asserts to throws, which then got caught and swallowed.
Fix it so that we fail the test oin that case.
Also fix these tests to be more uniform about how we unpack the data files we comare to.   improve the test so that it is more helpful when there are failures.
Finally there were problems that were being ignored that needed to be fixed.
In particular, we were assigning two stacks to the same event (becase there were events with the same QPC time).   Fixed this by disambiguating based on processor number (this is the change in TraceLog.cs).
=> Fix tests that were passing when they should not 

src/PerfView/Dialogs/ManagePresetsDialog.xaml, src/PerfView/Dialogs/ManagePresetsDialog.xaml.cs, src/PerfView/Dialogs/NewPresetDialog.xaml, src/PerfView/Dialogs/NewPresetDialog.xaml.cs, src/PerfView/GuiUtilities/HistoryComboBox/HistoryCombBox.cs, src/PerfView/StackViewer/Preset.cs, src/PerfView/StackViewer/StackWindow.xaml, src/PerfView/StackViewer/StackWindow.xaml.cs, src/PerfView/SupportFiles/UsersGuide.htm
Initial implementation of the grouping/folding presets (#446).
Presets only include Grouping/folding/include/exclude and do not include Memory Stack specific fields.
"Builtin" GroupPats are kept as is (only updated in the text boxes), so PerfView restart will restore them even if they were overwritten by dropdown history.
This implementation works for my needs, but I'm opened to suggestion about how to improve it for wider acceptance.
=> Added support for presets of grouping/folding

src/PerfView/PerfViewData.cs, src/PerfView/SupportFiles/UsersGuide.htm, src/TraceEvent/Computers/ThreadTimeComputer.cs
You don't get a ThreadTime with task and start-stop activity attributization view if you don't collect with /threadTime.
However you CAN most of this without context switches, so make a (CPU ONLY) version of this view and allow users to use that (and thus get task and activity information) even in the normal default collection mode (which is CPU only, but has all the other events needed).
=> Add CPU ONLY Thread Time if you don't have context switches.

src/TraceEvent/TraceLog.cs
Too many DLLs violate the pdb/dll match.
Weaken to just use OS/VS dlls
=> Fix assert

src/TraceEvent/Parsers/SymbolTraceEventParser.cs, src/TraceEvent/TraceEvent.Tests/inputs/net.4.0.x64.baseline.txt, src/TraceEvent/TraceEvent.Tests/inputs/net.4.0.x86.baseline.txt, src/TraceEvent/TraceEvent.Tests/inputs/net.4.5.2.x64.baseline.txt, src/TraceEvent/TraceEvent.Tests/inputs/net.4.5.2.x86.baseline.txt, src/TraceEvent/TraceEvent.Tests/inputs/net.4.5.x64.baseline.txt, src/TraceEvent/TraceEvent.Tests/inputs/net.4.5.x86.baseline.txt, src/TraceEvent/TraceEvent.Tests/inputs/net.4.6.2.x86.baseline.txt, src/TraceEvent/TraceEvent.Tests/inputs/netfx.4.6.1080.0.netfxrel3stage.x64.baseline.txt, src/TraceEvent/TraceEvent.Tests/inputs/netfx.4.6.1080.0.netfxrel3stage.x86.baseline.txt, src/TraceEvent/TraceEvent.Tests/inputs/sl.5.x86.baseline.txt, src/TraceEvent/TraceLog.cs
This change fixes stack association logic when ImageID events with opcode 38 and 40 are present. We are seeing these on traces collected with the Diagnostic Tools collector when gathering VS traces. By setting the noStack flag the stacks get properly associated with the Image/Load event.
=> Fix stack association logic

src/PerfView/PerfViewData.cs, src/TraceEvent/Computers/TraceManagedProcess.cs, src/TraceEvent/Parsers/ClrPrivateTraceEventParser.cs, src/TraceEvent/Parsers/ClrTraceEventParser.cs
This update corresponds to https://github.com/dotnet/coreclr/pull/17989.
=> Update TraceEvent parsers to match CoreCLR manifest changes

src/Directory.Build.props, src/PerfView/SupportFiles/UsersGuide.htm, src/TraceEvent/Symbols/SymbolPath.cs, src/TraceEvent/Symbols/SymbolReader.cs
This aligns with what Visual Studio defines.
=> Change default symbol cache location

src/Directory.Build.props, src/TraceEvent/Computers/ActivityComputer.cs, src/TraceEvent/TraceLog.cs
Added a max count (1000) to a loop to insure no infinite loops even in bad traces.
=> Fix an infinite loop in the StartStop Actitivities view

src/PerfView/PerfViewData.cs
Changes from Dan Leviant: added a PerfViewFile.Open overload that can be called by PerfView
extensions like VisualStudioRPS that don't have access to
GuiApp.MainWindow. Also updated the existing Open implementation to
leverage an existing worker, when possible. Diagsession files, which do
a secondary Open operation on the embedded Etl resource leverage this
support.
=> Adding new overload for PerfView extensions

src/Directory.Build.props, src/NugetSupportFiles/Microsoft.Diagnostics.Tracing.TraceEvent.SupportFiles.Populate.bat, src/NugetSupportFiles/Microsoft.Diagnostics.Tracing.TraceEvent.SupportFiles/Microsoft.Diagnostics.Tracing.TraceEvent.SupportFiles.nuspec, src/NugetSupportFiles/PerfView.SupportFiles.Populate.bat, src/NugetSupportFiles/PerfView.SupportFiles/PerfView.SupportFiles.nuspec, src/PerfView/PerfView.csproj, src/PerfView/SupportFiles/UsersGuide.htm, src/TraceEventPackageSigning/TraceEventPackageSigning.csproj
A month ago Nuget requires microsoft packages to be signed.
Update TraceEventPackageSigning to support signing nuget packages that are checked in to NugetSupportFiles.
Also fixed a missing DLL problem (PerfView.csproj).
=> Update to support signing Nuget support packages

src/Directory.Build.props
This tests the new signed nuget packages.
It also happens to update the DiagnosticHub code (for *.diagsession parsing).
=> Use the latest support files versions

src/TraceEvent/DynamicTraceEventParser.cs
For reasons I'm not going to get into, we are using the DynamicTraceEventParser class (as opposed to a strongly typed parser from traceparsergen) to retrieve a payload value of type byte array. Its very inefficient; there is already a TODO in the codebase to handle arrays of blittable types more efficiently. I did some brief testing where I emited a single event, captured and opened up that file using the DynamicTraceEventParser, cloned the event, then read a single 2000 byte payload value 10000 times from that clone. Using perfview I can see a 5x reduction in CPU from before and after.
My change looks a little hackish, but seems safe enough until that existing TODO is properly addressed. Existing tests pass.
=> Short-circuit DynamicTraceEventParser::GetPayloadValueAt for arrays of bytes

documentation/TraceEvent/TraceEventProgrammersGuide.md, src/TraceEvent/TraceEvent.Tests/EventPipeParsing.cs, src/TraceEvent/TraceEvent.Tests/TraceEvent.Tests.csproj, src/TraceEvent/TraceEvent.cs
The Dynamic Language Runtime approach won't be as efficient as the
TraceParserGen approach, but it is convenient for prototyping or
accessing event data from PowerShell.
(see the updates to the documentation for a bit more info)
The DLR is supported in .NET Standard 2.0, but not 1.6, so we #if it out
for 1.6.
Addresses #617.
=> Add DLR support for TraceEvent dynamic properties

src/PerfView/Extensibility.cs
There is an issue where doubles are written in one local and read in another.  This was already fixed in the data, but there was a lingering problem in the FilterState (e.g. the values in the Start and End TextBoxes are also persisted in the XML).   This fix only makes the reader robust (that is it will ignore bad data.
=> Fix bug in reading PerfView.xml files

src/TraceParserGen/TraceParserGen.cs
Fixing an issue that happen when the evnt.Fields is not null but empty. Without this fix, if the evnt.Fields is empty, it will generate this kind of event:
```csharp
public event Action<Template_0> AddAnnotationStart
```
instead of:
```csharp
public event Action<EmptyTraceData> AddAnnotationStart
```
This can be easily observe by trying to generate a parser for the **wpf-etw.man**.
I just added a check on the count of evnt.Fields. Let me know if you prefer the null conditional form `if (evnt.Fields?.Count > 0 )`, I can change that.
=> TraceParserGen: fix GetTemplateNameForEvent for empty evnt fields

src/Directory.Build.props, src/EtwClrProfiler/CorProfilerTracer.cpp, src/EtwClrProfiler/ETWClrProfiler.h, src/EtwClrProfiler/ETWClrProfiler.man, src/EtwClrProfiler/StubX64.asm, src/EtwClrProfiler/compileManifest.bat, src/EtwHeapDump/DotNetHeapDumper.cs, src/FastSerialization/FastSerialization.csproj, src/HeapDump/HeapDump.csproj, src/MemoryGraph/MemoryGraph.csproj, src/PerfView/App.cs, src/PerfView/CommandLineArgs.cs, src/PerfView/CommandProcessor.cs, src/PerfView/Dialogs/MemoryDataDialog.xaml, src/PerfView/PerfView.csproj, src/PerfView/PerfViewData.cs, src/PerfView/SupportFiles/UsersGuide.htm, src/PerfView/Triggers.cs, src/PerfView/memory/ETWClrProfilerTraceEventParser.cs, src/PerfViewCollect/PerfViewCollect.csproj, src/TraceEvent/Computers/ActivityComputer.cs, src/TraceEvent/Computers/SampleProfilerThreadTimeComputer.cs, src/TraceEvent/Parsers/FrameworkTraceEventParser.cs, src/TraceEvent/Parsers/KernelTraceEventParser.cs, src/TraceEvent/TraceEvent.cs, src/TraceEvent/TraceEvent.csproj, src/TraceEvent/TraceLog.cs, src/TraceEvent/TraceUtilities/PEFile.cs
1. Added SourceLink Support (PDBs now have URLs)
2. Added TimeStampQPC (however it is marked as Discouraged, it is for unusual scenarios)
3. Added /DotNetCallsSampled which samples every ~1000 calls (which is enough that it does not slow things down too much
4.  Added /DisableInlining for /DotNetCalls* so that you can see every call whether it was inlined or not.
5. Windows now routinle does not log the machine name.  Fix logic that depended on knowing the machine name.
=> Various changes

src/PerfView/PerfView.csproj
I tried to compile Perfview and got an error:
>  error CS1566: Error reading resource '.\x86\Microsoft.Diagnostics.Runtime.dll' 'Could not find a part of the path 'C:\Users\Andre\.nuget\packagesMicrosoft.Diagnostics.Runtime\0.8.31-beta\lib\net40\Microsoft.Diagnostics.Runtime.dll'.'
packagesMicrosoft.Diagnostics.Runtime is wrong, there is a missing `\`
=> fixed compile error:  error CS1566: Error reading resource '.\x86\Microsoft.Diagnostics.Runtime.dll' 

src/TraceEvent/Symbols/SymbolReader.cs, src/TraceEvent/TraceLog.cs
Basically PerfView is a 32 bit app, and system file redirection had to be
bypassed one more place.
=> Fixes lookup of system32 symbols in the unmerged case.

src/Directory.Build.props, src/TraceEvent/Microsoft.Diagnostics.Tracing.TraceEvent.props
OSExtentions needs to be 'next' to the architecture directories where KernelTraceControl.dll lives for it to load
them properly.   This works for published .NET Core apps, but by default 'dotnet run' runs nuget DLLs out of
the nuget cache (it does not copy them to the app directory).   This breaks the loading of KernelTraceControl.dll.
We already manually copy the native files and some interop files to the output directory in the TraceEvent nuget
package.   Here we simply add OSExtentions.dll to that list so it is loaded from the same place even in the dev-time
scenario.
=> Fix dev-time load failure loading KernelTraceControl.

src/PerfView/PerfViewData.cs, src/TraceEvent/Computers/ThreadTimeComputer.cs, src/TraceEvent/TraceEventSession.cs
Logic for doing a CPU ONLY start-stop stack view inadvertently turned off 'AWAIT TIME' for all cases
(the intent was to turn of AWAIT time for just CPU ONLY view).    This bug has introduced in early May.
@xiaomi7732  FYI.
=> Await time was dropped accidentally.

src/Directory.Build.props, src/PerfView/SupportFiles/UsersGuide.htm, src/TraceEvent/DynamicTraceEventParser.cs, src/TraceEvent/Parsers/TplTraceEventParser.cs, src/TraceEvent/TraceEventSession.cs
.NET Core added an event that helps diagnose some kinds of async deadlock
(where code that should have triggered a task completion simply drops the
task that should have been signaled).     See release notes for more.
TraceEvent synthesizes a Version number to determine if one EventSource
manifest is 'better' than another.   Change it so that if you add a new event
the version goes a a lot, which allows you to also delete some entries and still
have a better version (see comments for more).
=> Support IncompleteAsyncMethod (at least a bit).

src/TraceEvent/Parsers/ClrTraceEventParser.cs
In .NET Framework 4.8, LowMemoryHostBlocking was added to GC_REASON. I am adding this to TraceEvent to keep it consistent with the framework side of GC_REASON.
=> Add LowMemoryHostBlocking to GCReason

src/PerfView/Dialogs/EmptySymbolPathDialog.xaml
Fix typo in `EmptySymbolPathDialog.xaml`
Change `sever` to `server`
=> Fix typo sever in EmptySymbolPathDialog

src/PerfView/Extensibility.cs, src/PerfView/PerfViewData.cs, src/PerfView/StackViewer/StackWindow.xaml.cs
Grouping option `[group CLR/OS entries] \Temporary ASP.NET Files\->;v4.0.30319\%!=>CLR;v2.0.50727\%!=>CLR;mscoree=>CLR;\mscorlib.*!=>LIB;\System.*!=>LIB;Presentation%=>WPF;WindowsBase%=>WPF;system32\*!=>OS;syswow64\*!=>OS;{%}!=> module $1` does not consider that `System.Xaml` namespace refers to WPF, but is displayed as `LIB` currently which can lead to extra lines in treeview like WPF->LIB(System.Xaml)->WPF.
Fixed that behaviour in this PR. Added `;\System.Xaml.*!=>WPF` to grouping expression `[group CLR/OS entries] ...`
=> Grouping: [group CLR/OS entries]: Added System.Xaml namespace to be grouped with WPF

LICENSE.TXT, src/Directory.Build.props, src/NugetSupportFiles/Microsoft.Diagnostics.Tracing.TraceEvent.SupportFiles/Microsoft.Diagnostics.Tracing.TraceEvent.SupportFiles.nuspec, src/NugetSupportFiles/PerfView.SupportFiles/PerfView.SupportFiles.nuspec, src/TraceEvent/Microsoft.Diagnostics.Tracing.TraceEvent.nuspec
Fixes issue #779.   This makes us consistent with the rest of .NET Core Framework (https://github.com/dotnet/corefx).
Like the rest of corefx, we ship under the MIT license.
=> Harmonize the license in the source and in the nuget packages.

src/PerfView/OtherSources/Linux/LinuxPerfScriptEventParser.cs
=> Read cpu number only when it's available in Linux event

src/TraceEvent/Microsoft.Diagnostics.Tracing.TraceEvent.props
This fixes bug #755.  It is a replacement for #813 which had a casing typo.
=> Fix Missing Microsoft.Win32.Registry error on Desktop

src/Directory.Build.props, src/TraceEvent/DynamicTraceEventParser.cs, src/TraceEvent/RegisteredTraceEventParser.cs
There was an example where a class with 4 nullable fields was not
being parsed correctly.    This was caused by a misunderstanding
about how to parse propertyInfo information (InType is not valid
if the property has struct type, see change RegisteredTraceEventParser.cs)
Along the way I also spotted a bug where the cache for property fetches could be fooled by nested structs.   Added a 'useCache' argument so the cache is only used for top level structs.
=> Fix bug in a complex Self-describing ETW example

src/Directory.Build.targets
The symptom that we are fixing is that on a very clean build, building from the command line (msbuild.exe) you get build errors about missing *.sourcelink.json files.  
The issue is that if your msbuild is using old components, then it might have SourceControlInformationFeatureSupported not set to true.  When this happens it does not generate a *.sourcelink.json file (which is good), but it LEFT the sourcelink variable set which tells the C# compile to try to attach this file to the resulting EXE and things fail.
=> Fix msbuild break on very clean source trees.

src/TraceEvent/Microsoft.Diagnostics.Tracing.TraceEvent.nuspec
I had updated it to use the new license element but that means
that older versions of Visual Studio can't built it .    The old way
was fine, so we will wait a while before updating to the new element.
=> Undoing change to licenseUrl element in TraceEvent.nuspec

src/MemoryGraph/MemoryGraph.csproj, src/Utilities/DirectoryUtilities.cs, src/Utilities/EnvironmentUtilities.cs, src/Utilities/FileUtilities.cs, src/Utilities/StreamUtilities.cs, src/Utilities/StringUtilities.cs, src/Utilities/Utilities.csproj, src/Utilities/XmlUtilities.cs
In the past PerfView code was used to build libraries that were used in Visual Studio.   The
DLLs that were built were Microsoft.Diagnostics.Utilties and Microsoft.Diagnostics.MemoryGraph.
These DLLs are not built as part of perfView (PerfView incorperates the soruce in the the PerfView.exe directly).  The build logic for these two DLLs is still in the repo, but it bit-rotted.
I have updated the MemoryGraph.csproj and Utiltiies.csproj to restore the ability to build these
DLL as the VS MAY find this useful (and it was easy to to do),    This may not turn out to be
useful, but at least this way the CSPROJ files are not completely out of date.
Note that all the changes in *.cs file are simply to removing the unneeded 'internal' specifiers that causes a compile error if UTILITIES_PUBLIC is …
=> Allow building the MemoryGraph and Utilities dlls.

src/PerfView/EventViewer/EventWindow.xaml, src/PerfView/EventViewer/EventWindow.xaml.cs, src/PerfView/PerfView.csproj, src/PerfView/SupportFiles/EventCounterVisualization.html, src/PerfView/SupportFiles/UsersGuide.htm
Here is a pull request for the issue #839
We used to be able to view the EventCounter traces as indivdual events.
Now you can pull up the context menu
and open the graph view:
You can double-click to zoom and drag to pan the graph to see the details.
@vancem
=> EventCounter data visualization

src/FastSerialization/CompressedStream.cs, src/FastSerialization/GrowableArray.cs, src/MemoryGraph/graph.cs
These changes should not change behavior at all.
This is in preparation for better sampling (sampling when
graph is created rather than afterward.
Also added code for a CompressedStream (ifdefed out) so we don't lose it (it should be useful for *.netperf files and
I don't want to lose the work).
=> Non-semantic refactoring changes in Graph.cs

src/PerfView/CommandProcessor.cs, src/TraceEvent/Computers/TraceManagedProcess.cs, src/TraceEvent/TraceEventSession.cs
Fix logic that allows EventSources to skip the * syntax (e.g. /ProviderName=XXX will assume XXX is
and eventSource (with a warning in the log), if it could not find it in the OS table).    This was the
intent of code added long ago but it was broken.
Renamed Insure->Ensure
Small fix in inlining processing logic.
=> Small fixes

src/Directory.Build.props, src/NugetSupportFiles/Microsoft.Diagnostics.Tracing.TraceEvent.SupportFiles.Populate.bat, src/NugetSupportFiles/Microsoft.Diagnostics.Tracing.TraceEvent.SupportFiles/Microsoft.Diagnostics.Tracing.TraceEvent.SupportFiles.nuspec, src/PerfView/GuiUtilities/WindowBase.cs
We added code to give windows owners (so that windows end up on a related screen when using multiple screens)
However it turns out you can't give a window an owner if the owner was never display, and we do precisely this
when we pop a EULA dialog on startup.  This causes a silent crash (because the normal windows to display errors
also fail).    Fix this by catching errors and proceeding without setting owners.
Also updated to use a newer SupportFiles (this just adds a PDB), and update the PerfView version number.
=> Fix bug where PerfView fails to launch.

src/MemoryGraph/graph.cs, src/TraceEvent/Computers/StartStopActivityComputer.cs
Basically OnStart already has a option (but it is not the default) that says 'don't use the current thread's activity as the parent activity.   This is just what we need to fix this issue (since classic ASP.NET Events really should not nest, if you see two starts in a row, you should not make the second activity the child of the first.
=> Fix problem where classic ASP.NET activities nest when they should not.

src/Directory.Build.props, src/TraceEvent/TraceEventSession.cs
Don't throw an exception if you can't get a Name->Guid mapping.  Simply go on.
=> Window Nano does not have a working EnumerateProviders API

src/Directory.Build.props, src/FastSerialization/MemoryMappedFileStreamReader.cs, src/FastSerialization/MemoryMappedFileStreamWriter.cs, src/FastSerialization/SegmentedMemoryStreamReader.cs, src/FastSerialization/SegmentedMemoryStreamWriter.cs, src/MemoryGraph/graph.cs
This mostly pulls in code that Marco wrote a while back (some small tweeks).   Bascially instead 
of using MemoryStream we use a new SementedMemoryStream. 
Marco. Please build this locally and test that it performs well and does what you want.  
Note that we don't use MemoryMappedFileStreamWriter anymore so I have #ifdefed it out for now.
Also to avoid dependency of MemoryMappedFileStreamReader on MemoryMappedFileStreamWriter I cloned the BlockCopyCapacity constant into  MemoryMappedFileStreamReader 
@mpeyrotc  @sharwell
=> To avoid large allocations create SegmentedStreams and use in graph. 

src/TraceEvent/Parsers/KernelTraceEventParser.cs
TraceEvent automatically converts kernel paths found in ETW events
to user paths. Depending on the available input, the conversion can
end up being inaccurate. For example, in real-time ETW sessions,
the conversion will fail for events originating from a drive inserted
after the session started (such as a USB key).
The patch enables the user to specify explicitly how path conversion
should be done by setting KernelPathToUserPathMapper. For instance,
if set to the identity function, no conversion is done and the
original kernel paths from the events are exposed.
=> Enable user-defined path conversion

src/PerfView/GuiUtilities/WindowBase.cs
Previous #758 fixed window creation so that child windows would be on the same monitor as their parents. This change has the side effect of making it impossible to put parent windows on top of child windows.
This change instead puts the window on the screen where the mouse cursor is at the time the window is created. This isn't perfect; if you double click something and quickly move the mouse you can wind up with the window on the "wrong" monitor. I think this is a better compromise than the current situation.
Fixes #865
=> Changes window ownership for better z-ordering

src/FastSerialization/SegmentedList.cs
CopyRangeTo method had destructive behavior to improve memory usage, further discussion agreed this is not a behavior a list should have.
=> Remove destructive behavior from copy

src/PerfView/app.config
Set the value to false will allow build debug binaries while not showing the assertion failure dialogs. Just to make the debugging easier.
=> Add configure to bypass assert dialogs

src/PerfView/OtherSources/Linux/LinuxPerfScriptEventParser.cs
This was caused by a trace with an empty process name.   Fixed to be resilient to that.  
Also made the code clearer while I was in there.
=> Fix a formatError exception when parsing some Linux traces.

src/PerfView/PerfViewData.cs, src/TraceEvent/Symbols/NativeSymbolModule.cs
This PR demonstrates how to retrieve the type of native allocations as described in #780 
This would be useful functionality to have in the TraceEvent nuget package to allow for scenarios like https://github.com/dotnet/BenchmarkDotNet/issues/457
There's a few questions in the PR on where certain functionality belongs.
=> track type of native allocations when available

src/NugetSupportFiles/Microsoft.Diagnostics.Tracing.TraceEvent.SupportFiles/Microsoft.Diagnostics.Tracing.TraceEvent.SupportFiles.nuspec, src/NugetSupportFiles/PerfView.SupportFiles/PerfView.SupportFiles.nuspec, src/TraceEvent/Microsoft.Diagnostics.Tracing.TraceEvent.nuspec
licenseUrl is now deprecated.  Fix warnings by using new license element instead.
=> Fix Nuspecs to use license intead of licenseUrl

src/NugetSupportFiles/Microsoft.Diagnostics.Tracing.TraceEvent.SupportFiles/Microsoft.Diagnostics.Tracing.TraceEvent.SupportFiles.nuspec, src/NugetSupportFiles/PerfView.SupportFiles/PerfView.SupportFiles.nuspec, src/TraceEvent/Microsoft.Diagnostics.Tracing.TraceEvent.nuspec
Offical builds don't support the license nuget element.   Fall back to licenseUrl for now.
=> Fix official build break.

src/TraceEvent/Parsers/ClrTraceEventParser.cs
This allows PerfView and TraceEvent to understand the instrumentation added to CoreCLR by https://github.com/dotnet/coreclr/pull/23662.
=> Add R2RGetEntryPoint event to ClrTraceEventParser

src/PerfView/SupportFiles/UsersGuide.htm
Update the docs to refer to BufferSizeMB, instead of the old convention without the units
=> Update the docs to refer to BufferSizeMB

src/PerfView64/App.cs, src/PerfView64/PerfView64.csproj, src/PerfView64/app.manifest
If you're dumb like me and download the `PerfView64.exe` wrapper and run it without `PerfView.exe` being present, it will silently error (though it will leave an error in the Windows Event Viewer).
This change means an error message will be displayed when `PerfView.exe` is missing.
=> Display error message when PerfView64 wrapper can't load PerfView.exe

documentation/Downloading.md, src/TraceEvent/BPerf/BPerfEventSource.cs
Fixes the updated release link
A stray line from my previous change is there. It is harmless because we always overwrite it but confusing and not what I intended to do. No need to update release for it.
=> Fix a typo and stale link

src/TraceEvent/TraceEventSession.cs
Fix an issue caused by unexpected stop of trace sessions when TraceEventSession is just created and attached to check if a session is active.
=> Fix an issue caused by unexpected stop of trace sessions when TraceEventSession is just created and attached to check if a session is active.

src/TraceEvent/Computers/TraceManagedProcess.cs
This fixes issue #924. The parser expects to see only a single threaded sequence of SuspendStart, SuspendStop, RestartStart, RestartStop but using GC and stack sampling simultaneously can interleave that pattern on two different threads. This confuses the parser and breaks the GC stats.
The issue is fixed by filtering out all SuspendStart events that don't have a GC reason and then filtering out further suspension events if they are not on the same thread as the SuspendStart event.
=> Fix GC suspension parser to coexist with stack sampler

documentation/Downloading.md
With the recent .nettrace format change, people will need new version of PerfView to open them - This doc is the one of the first thing that pops up on search engines but it only has link to 2.0.42, so I'm updating the documentation here for whoever else clicks this and finds that it can't open .nettrace files :-)
=> Update link to most recent version of PerfView in docs

src/FastSerialization/SegmentedMemoryStreamReader.cs, src/FastSerialization/StreamReaderWriter.cs, src/MemoryGraph/graph.cs, src/TraceEvent/TraceEvent.Tests/FastSerializerTests.cs
This fixes issue #958 
StreamLabels serialized in the FastSerialization format are 4 byte unsigned integers, but the FastSerialization library reads them using ReadInt32() so values above 2GB appear negative. Prior to PR #952 StreamLabel was a uint so (StreamLabel)ReadInt32() restored the correct unsigned semantics to the value. In PR #952 StreamLabel became a long which meant values above 2GB remained negative. Attempting to Goto() a negative StreamLabel put the reader in a bad state which lead to the observed error later in Fill().
The fix casts the int first to a uint, then assigns to the StreamLabel as before. The problematic trace was only manifesting an issue at StreamReaderWriter.cs:153, but I searched for all locations where an int was being assigned to a StreamLabel in case any …
=> Fix parsing of ETLX files larger than 2GB

src/TraceEvent/Parsers/ClrTraceEventParser.cs
Add support for enabling the CompilationVerbose keyword via /ClrEvents.  This is in reaction to https://github.com/dotnet/coreclr/pull/25544.
=> Add the CompilationVerbose keyword to CLRTraceEventParser

src/TraceEvent/Parsers/ClrTraceEventParser.cs
This change maps the event to the ID in https://github.com/dotnet/coreclr/blob/2a8529c6130f6c70488e8bace26404b319eed00f/src/vm/ClrEtwAll.man#L3175
The current ID maps the MethodJitInliningFailed event ID, which is wrong.
=> Update the MethodJitTailCallFailed event ID

src/TraceEvent/Stacks/SpeedScopeStackSourceWriter.cs, src/TraceEvent/TraceEvent.Tests/SpeedScopeExporterTests.cs
The SpeedScope file format represents every profile as a list of sorted open and close events.
An example: method Main lasts from 0.0s to 1.0s. Such a profile would be represented as:
```json
"frames": [ { "name": "Main" } ]
events:
[
{ "type": "O", "frame": 0, "at": 0.0 },
{ "type": "C", "frame": 0, "at": 1.0 },
]
```
If two samples happen at the same time, the closing sample must be exported first, then the opening sample should be exported. Descending by call stack depth:
```cs
void Main()
{ 
A(); 
B();
}
void A() => C();
void B() => C();
```
```json
"frames": 
[ 
{ "name": "Main" }, 
{ "name": "A" },
{ "name": "B" }, 
{ "name": "C" } 
]
events:
[
{ "type": "O", "frame": 0, "at": 0.0 }, // open Main
{ "type": "O", "frame": 1, "at": 0.0 }, // open A
{ "type": "O", "frame": 3, "at": 0.0 …
```
=> fix SpeedScope exporter bug

src/PerfView/StackViewer/FlameGraphDrawingCanvas.cs
I am currently working on a PerfView demo where I want to show Flame Graphs that I've implemented a long time ago.
I realized that demoing it without zoom would be very hard. So I implemented the zooming support. I've also increased the tooltip font size.
How to zoom: using Mouse Wheel.
How to move: using arrow keys or pressing, holding and moving left mouse button.
Sample:
@brianrob could you please take a look?
/cc @davidfowl @ReubenBond @danmosemsft
=> FlameGraph zooming

src/PerfView/PerfViewData.cs, src/PerfView/StackViewer/StackWindow.xaml.cs
Recently I've been profiling a lot of parallel benchmarks that do the same job on every thread (an example is PlainText TechEmpower benchmark).
I find `Thread -> AllThreads` very useful when working with FlameGraph in such cases:
Before:
After:
my proposal is to add "[join all threads]            Thread -> AllThreads" to the list of predefined GroupPats. Just to make it more accessible for new PerfView users who are not familiar with all grouping capabilities.
=> add "join all threads" to the list of pre-defined GroupPats, implement Select Process Window for LTTng traces

src/PerfView/OtherSources/Linux/LinuxPerfScriptEventParser.cs
- Allow for empty map files.
- React to https://github.com/torvalds/linux/commit/19610184693c547b4c12738df4156589892c4018#diff-2dde3a24afb7b4ade6b2cb9b7a687290 which changes the output of `perf script` backtraces to always be virtual addresses instead of file offsets.
Depends upon https://github.com/dotnet/coreclr/pull/26403/.
=> Fixes for Linux Perf_Events Traces

src/PerfView/CommandLineArgs.cs, src/PerfView/PerfViewData.cs, src/PerfView/Utilities/commandLine.cs, src/TraceEvent/BPerf/BPerfEventSource.cs, src/TraceEvent/TraceEvent.Tests/BPerfTest.cs, src/TraceEvent/TraceEvent.cs, src/TraceEvent/TraceLog.cs
Adds support to BPerf's reader for a side-database for managed method info and image load data. This allows us to enable verbose events like GC in the main session that rotates and a managed method db that doesn't rotate for the application lifetime.
@brianrob @LakshanF this change will allow us to onboard to CAP.
=> Add support to BPerf reader for symbols from a different file.

src/TraceEvent/Symbols/PortableSymbolModule.cs, src/TraceEvent/Symbols/SymbolReader.cs, src/TraceEvent/Utilities/Cache.cs
I've recently profiled an app using PerfView, opened the trace file, used `Goto Source (Def)`, closed the Source Window, modified the app source code and tried to rebuild the app.
The rebuild has failed with file in use exception:
```log
C:\Program Files\dotnet\sdk\3.0.100-preview9-013617\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(153,5): warning MSB3026: Could not copy "obj\Release\netcoreapp3.0\win-x64\ReportedTime.pdb" to "bin\Release\netcoreapp3.0\win-x64\publish\ReportedTime.pdb". Beginning retry 1 in 1000ms. The process cannot access the file 'C:\Projects\PerfViewDemo\ReportedTime\bin\Release\netcoreapp3.0\win-x64\publish\ReportedTime.pdb' because it is being used by another process.  [C:\Projects\PerfViewDemo\ReportedTime\0_ReportedTime.csproj]
```
This PR helps …
=> make sure that SymbolReader.Dispose closes all opened pdb files

src/PerfView/Triggers.cs
When using a performance counter trigger, if the instance name contains a colon ":" it will not match the regex and instead error out.  One example is the below counter which should be allowed: 
PhysicalDisk:Avg. Disk sec/Write:0 C:>0.01
I also noticed that when specifying a threshold, its required to have a leading digit (0.02 instead of .02) so I updated the error message to help anyone who might run into that.
This PR fixes the colon issue and updates the error message.
=> Fix Issue with Colons in Perf Counter Instance Names

src/TraceEvent/Parsers/ClrTraceEventParser.cs, src/TraceParserGen/ETWManifest.cs, src/TraceParserGen/TraceParserGen.cs
Cleanup TraceParserGen to generate a .cs file from which it is possible to copy/paste valid new CLR events related code intothe TraceEvent ClrTraceEventParser.cs file.
Before this change, the generated C# code was not valid and needed careful manual merge operations when new events are added to ClrEtwAll.man in CoreClr repo.
=> Cleanup ClrTraceEventParser.cs file generation

src/TraceEvent/Computers/StartStopActivityComputer.cs
Basically the issue was that to look up an activity path you need to know that process ID.    We have a mechanism for doing this without the process ID, but it is does not work for process IDs > 64K.   We were running into traces that exceeded this.  
I did two things. 
1.  Fixed it so that we always use the process ID.
2. As extra insurance, even when we don't allow the 'guess' to work with process IDs that fit in 20 bits (rather than 16).
=> Fix issue where activity paths were not being shown as paths.

src/PerfView/PerfViewData.cs
Fixed typo with .NGENPDB #1019 
.NENPDB -> .N**G**ENPDB
=> Fixed typo with .NGENPDB #1019 

src/TraceEvent/Parsers/Microsoft-Windows-NDIS-PacketCapture.cs
This PR adds support for parsing the UDP header in the captured packets and printing the related information in the ParsedPacket output string.
This will show UDP info in PerfView and allows users of the TraceEvent nuget package to get UDP info from ParsedPacket.
=> Add UDP info to ParsedPacket

src/FastSerialization/FunctorComparer`1.cs, src/FastSerialization/GrowableArray.cs, src/TraceEvent/Stacks/CallTree.cs, src/TraceEvent/Stacks/FilterStacks.cs, src/TraceEvent/TraceEvent.csproj
Reduces allocations in PerfView when opening certain memory views. Implemented as part of a solution to a 7,000+ second load time for a recent OOM heap.
⚠️ **Please do not rebase or squash this pull request during the merge.** ⚠️
=> Reduced allocations

.gitignore, src/TraceEvent/TraceLog.cs
There are two issues with TraceCodeAddresses: 
1) resizing for codeAddressObjects uses linear growth (+ 16) leading to lots of LOH allocations, This is O(N^2) algorithm. Replacing with sparse array.
2) In Name(CodeAddressIndex), there is a cache stored in string array, but no string is ever stored back, causing lots of duplicating string generation. Add write back.
=> Fix Caching Issues in TraceCodeAddresses

src/HeapDump/GCHeapDumper.cs
I encountered ArgumentNullException when running HeapDump on a snapshot memory dump of a 64-bit ASP.NET Core application. There were some types with null names.
I think they came from dynamically generated types in a DI container.
This fixes the ArgumentNullException by generating names for them based on their metadata token.
=> Avoid ArgumentNullException when HeapDump encounters a type with no name

src/FastSerialization/StreamReaderWriter.cs
When reading a non-seekable stream, the `IOStreamStreamReader` class can be put in a state where it attempts to read a count greater than length - offset of its internal buffer.
<details>
<summary>simple repro</summary>
```csharp
class Program
{
public static int align = 8;
public static int size = 0x4000;
static void Main(string[] args)
{
using var memoryStream = new MemoryStream();
for (int i = 0; i < 20 * size; i++)
{
memoryStream.WriteByte(0xFD);
}
memoryStream.Seek(0, SeekOrigin.Begin);
var nonSeekableStream = new NonSeekableStream(memoryStream);
var dst = new byte[size * 2];
using var streamReader = new IOStreamStreamReader(nonSeekableStream);
// Put the stream reader in a bad state
streamReader.Read(dst, 0, 14); // Read a length in (8,16)
streamReader.Read(dst, 0, size + align); // …
```
=> Fix IOStreamStreamReader to account for alignment padding

src/TraceEvent/Computers/TraceManagedProcess.cs
While working on replacing the performance counters in our application, I noticed the xml for GCEnd is referring to `tha` instead of `the`.
=> Update `tha` to `the` in the xml for GCEnd

src/Directory.Build.props, src/TraceEvent/Computers/SampleProfilerThreadTimeComputer.cs, src/TraceEvent/Computers/StartStopActivityComputer.cs, src/TraceEvent/Computers/ThreadTimeComputer.cs
For .NET Core 3.0 trace analysis, we need to have an option to disable application insights activity id filter.
=> Allows opt out nested activity id reducing

src/TraceEvent/BPerf/BPerfEventSource.cs, src/TraceEvent/Symbols/SymbolReader.cs, src/TraceEvent/TraceEvent.cs, src/TraceEvent/TraceLog.cs
Because BTL files support reading from an offset into the file, symbol resolution gets complicated since it needs process state information.
This complicated code actually doesn't work in the case where the cpu time is spent inside the process of interest but is in kernel code because our support code which logs symbolic information in the sidecar database can only do so for user-mode modules.
Also additional testing revealed that when we're looking for symbolic resolution in BTL files, i.e. we're doing an investigation that'll need stacks it is often time acceptable that we iterate the whole file in search for process state information. However, we don't want to lose the focusing on a specific part of the file (one of the key benefits of BTL) so the compromise is that we iterate the …
=> Simplify symbol resolution work for BTL files

src/TraceEvent/Parsers/ClrTraceEventParser.cs
Update ClrTraceEventParser to properly show new assembly loader events: https://github.com/dotnet/runtime/blob/5da85d0c4b6fc390047cb466a9e0ed674d9c121f/src/coreclr/src/vm/ClrEtwAll.man#L1673-L1808
=> Update ClrTraceEventParser with new assembly loader events

src/FastSerialization/MemoryMappedFileStreamWriter.cs, src/HeapDump/GCHeapDumper.cs, src/HeapDump/Program.cs
* Don't continue without roots on OutOfMemoryException
* Treat ERROR_NOT_ENOUGH_MEMORY as OutOfMemoryException
=> Improve handling of OutOfMemoryException

src/PerfView/CommandLineArgs.cs, src/PerfView/Dialogs/RunCommandDialog.xaml.cs
This change ensures the GC finalization table contains type information alongside the existing object counts.
=> Include the BulkType event for GC profiling

README.md
It looks like the "browse by tag" capability no longer exists in the archived blogs, but the link at least points to the correct blog.
=> Fix link to Vance Morrison's blog

src/PerfView/SupportFiles/UsersGuide.htm
I believe 3 is what the docs were going for.
=> Fix small typo in CircularMB docs about how many etl files there are.

src/TraceEvent/Symbols/SymbolPath.cs
Microsoft symbol server and reference sources' symbol server defaults to SSL site. #698
=> Microsoft symbol server now defaults to SSL site.

src/perfcollect/perfcollect
- Added start/stop to perfcollect
- Added noperf option to turn off perf when necessary
- Enabled lttng tracing of kernel events 
New usage would be:
```./perfcollect collect start <trace_name> -noperf``` to start a lttng-only trace 
```./perfcollect collect stop <trace_name>``` to stop a trace
```./perfcollect collect start <trace_name> -noperf -events kernel``` to start lttng-only kernel trace (currently only process exec/exit events, will add more)
=> Add start/stop and kernel tracing to perfcollect

src/PerfView/PerfView.csproj, src/TraceEvent/TraceEvent.cs, src/TraceEvent/TraceEvent.csproj
This fixes unaligned read errors (SIGBUS) caused by unmanaged pointer operations on ARM platforms. The [`Marshal.Read*()`](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.marshal.readint64?view=netcore-3.1) operations are portable and have little performance impacts.
=> Fix unaligned memory access errors in TraceEvent

src/Directory.Build.props, src/TraceEvent/Microsoft.Diagnostics.Tracing.TraceEvent.nuspec
#1104 adds a new package dependency to TraceEvent, but the nuspec was not updated.  This results in exceptions such as this: https://github.com/dotnet/diagnostics/pull/894?email_token=ABPMGEWPZW742HDCRXCKNXLRG5VOZA5CNFSM4LFCQFJ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEOPC2ZQ#discussion_r390837979.
=> Fix Missing NuGet Package Dependency

src/perfcollect/perfcollect
- Add ```-force``` option to perfcollect install so it can suppress prompt message
- Remove downloading PPA feed prompt from ```InstallLttng_Ubuntu``` since it's only needed for Ubuntu14.04
- Update the regex of extracting ```lttngTraceDir``` for the new output message in Lttng 2.11.2
=> Enable force installation in perfcollect

src/TraceEvent/TraceLog.cs
ETW stacks are logged as a set of separate events which are then correlated with the data events that they correspond to.  Construction of stacks and correlation with their data events occurs during `TraceLog` creation.  There are "stack definition" events, and then references to the stack definitions.  Stack references are 1:1 with their data events.  Stack definitions are 1:N where N is the number of references to the stack.  It is also important to know that stack definitions are not specific to a thread and do not contain the thread information as part of the stack.  This is done during construction of the `TraceLog`.
Prior to this change, the data structure that holds stack references assumed that all usages of a single reference came from the same thread.  It appears this may have …
=> Intern Stack Definitions Once Per Usage Instead of Once Per Definition

src/perfcollect/perfcollect
- Add ```LTTng_Kernel_ContextSwitchKeyword``` 
- Enable ```-events``` to take a list of keywords declared in the file
usage example:  
```./perfcollect start <tracename> -events LTTng_Kernel_ProcessLifetimeKeyword,DotNETRuntime_GCKeyword,<otherkeyword>```
=> Enable perfcollect to take a list of keywords

src/PerfView/EtwEventSource.cs, src/TraceEvent/DynamicTraceEventParser.cs
When filter through "large" collections of events the performance can be rather lackluster.
From profiling this scenario of PerfView it is apparent that most time is spent replacing characters in strings with Regex:
Just based on a quick glance this change was the least intrusive change possible.
A filtering through a collection of ~1_000_000 events here is the measurements from the PerfView logs:
Before:
```
Started: Scanning Events
Completed: Scanning Events   (Elapsed Time: 105.203 sec)
WARNING, returned the maximum 10000 records.
Histogram: ___o_________o0003011222365324442222424467A7453559546441001000000o__________________________________ Time Bucket 28,382.8 MSec
[Found 10000 (TRUNCATED. Set MaxRet for more) Records.  11,260 total events. ColumnSums: tag=510,000.000]
```
After:
``` …
```
=> Use compiled shared instances of commonly used regex in event view filtering

src/TraceEvent/Computers/TraceManagedProcess.cs
I needed to use this field in the gc perf infra.
=> expose ExtraGen0Commit field in perheap history in TraceGC

src/TraceEvent/Stacks/RecursionGuard.cs
There have been some cases recently of extremely deep stack traces that have resulted in `RecursionGuard` throwing a `StackOverflowException`  This change allows the maximum values that trigger a `StackOverflowException` to be configured, and also increases the maximum number of trampoline operations from 20 to 40.
=> Allow RecursionGuard Constants to be Configured

src/PerfView/MainWindow.xaml, src/PerfView/MainWindow.xaml.cs, src/PerfView/PerfViewData.cs
Scenario: I was opening some pretty large HTML reports in perfview and noticed that the default WebBrowser control was struggling to open large HTML files generated. (I had a particular /GCCollectOnly trace that had captured 180k GCs.)
To be fair, a modern browser also isn't perfect with an HTML file that big, but it is better.
So to address this I added a small feature to the right-click menu on the main TreeView that lets you open the report in your browser instead of the WPF control. Here's a demo:
To do this I had to fix a second issue - when you right-click an item in the tree view it is not automatically selected before you choose an item in the right-click menu. This meant that you could not reliably use TreeView.SelectedItem in the callback of the command that was chosen in the …
=> Add "Open in Browser" option for HTML reports in the TreeView

src/perfcollect/perfcollect
Allows `EventSources` to be consumed with the command line `./perfcollect collect sampleTrace -events EventSource`
=> Make EventSources Consumable from perfcollect

src/perfcollect/perfcollect
This makes the `perfcollect install` command aware of what packages are available on Fedora vs RHEL7 vs RHEL8.
Contributes to https://github.com/microsoft/perfview/issues/1130.
@brianrob ptal
cc @omajid
=> Make perfcollect install Fedora/RHEL8 compatible

src/PerfView/CommandLineArgs.cs, src/PerfView/CommandProcessor.cs, src/PerfView/SupportFiles/UsersGuide.htm, src/PerfView/Triggers.cs
Summary:
* Allows the MinSecForTrigger command-line flag to apply to
StartOnPerfCounter (previously only worked with StopOnPerfCounter)
* Improves logging and documentation around StopOnPerfCounter and
StartOnPerfCounter
* Improve log messages around perf counters to be clearer and make
sense for both "greater than" and "less than" scenarios.
Fixes #799
=> Improvements around MinSecForTrigger

src/PerfView/SupportFiles/UsersGuide.htm, src/PerfView/Triggers.cs
Allow the use of Windows Kernel Trace events with StopOnEtwEvent. For example: to stop when a disk read exceeds some threshold using DiskIO Read events.
Also added logic to handle float in FieldFilters and updated documentation.
=> Allow StopOnEtwEvent to use kernel provider events

src/PerfView/PerfViewData.cs, src/TraceEvent/TraceLog.cs
Fixes #1168.
Users will get a pop-up when opening the trace.  The count of lost events also appears in the EventStats view.
=> Alert Users of Lost Events for EventPipe Traces

src/TraceEvent/Stacks/ChromiumStackSourceWriter.cs, src/TraceEvent/Stacks/SpeedScopeStackSourceWriter.cs, src/TraceEvent/Stacks/StackSourceWriterHelper.cs
fixes #1178
Sample exporter name: `Microsoft.Diagnostics.Tracing.TraceEvent@2.0.56.0`
@brianrob PTAL
=> include TraceEvent name and version in the exported speedscope and chromium files

src/perfcollect/perfcollect
Current for loop expression will allow any possible inner loop to change ```$i``` randomly and result in early-exit or infinite loop. ( If there's no specific reason to use ```$i``` for loop,  recommending to get rid of this value completely to avoid similar bugs in the future )
=> update for loop in perfcollect

src/TraceEvent/Stacks/StackSourceWriterHelper.cs, src/TraceEvent/TraceEvent.Tests/SpeedScopeExporterTests.cs
I've cloned @swift-kim fork and started testing #1184 
I've found a few more things that needed to be changed (like using `CallerStackIndex` (not CallerFrameId)) which were old bugs of mine and decided to extend @swift-kim PR with some changes (see the commits)
I was not sure whether I should send a PR to @swift-kim fork or to the upstream repo. I hope that @swift-kim doesn't mind that I am sending this as a new PR.
@brianrob I've tested this a LOT. PTAL
=>  Fix aggregation of samples in the SpeedScope/Chromium exporter

src/PerfView/Triggers.cs
High values with a thousands separator were not parsed correctly and that caused trigger expression evaluation to use the value as a string. Ex: 7,664.722 in expression TimeMS >= 10000 evaluated to true.
=> Fix double value parsing in trigger expressions

src/TraceEvent/Symbols/SymbolReader.cs, src/TraceEvent/TraceEvent.csproj
Fixes #1187.
Synchronize access to the log inside of SymbolReader to avoid races caused by async handling of stdout/stderr.
cc: @suprak
=> Synchronize Access to the Log Inside of SymbolReader

src/PerfView/PerfViewData.cs, src/PerfView/SupportFiles/UsersGuide.htm, src/TraceEvent/Parsers/Microsoft-Windows-NDIS-PacketCapture.cs
Adds "Processor Stacks" advanced view if CPU stacks are available.
"Processor (x) Priority (y)" is added as the top frame to every stack, which allows per processor / priority analysis.
For convenience two grouping regexes are added to the view "Processor ({%}) Priority ({%})->Processor ($1)" and "Processor ({%}) Priority ({%})->Processor ($2)" that allow grouping by Processor and Priority respectively.
@Maoni0 , let me know if you have other thoughts around the view.
=> Add processor stacks

src/LinuxEvent.Tests/EventParseTests.cs, src/LinuxEvent.Tests/Sources/two_small_generic.perf.data.dump, src/PerfView/PerfViewData.cs, src/TraceEvent/Parsers/ClrTraceEventParser.cs, src/TraceEvent/Stacks/Linux/LinuxPerfScriptEventParser.cs, src/TraceEvent/Stacks/Linux/LinuxPerfScriptStackSource.cs
- Support for OffCPU tracing (shows up in PerfView as Thread Time stacks under the Experimental group).
- Fix naming of Process frames to be distinguishable from other non-process frames: `Process name (PID)` instead of `name`.
- Transform frames that were resolved via perf jitdump into the format `module!namespace::method` to allow them to be nicely grouped.
=> Implement Linux Tracing Improvements

src/perfcollect/perfcollect
- Adds a new -offcpu flag that enables collection of `sched` events for OffCPU analysis.
- Enables collection and inject of perf jitdumps to resolve symbols for non-native code (e.g. JIT and R2R).  For .NET applications, this is supported in .NET 5+.
=> Implement OffCPU tracing and Enable Usage of Perf Jitdumps

src/FastSerialization/FastSerialization.cs
Fixes #1207.
Make sure that `reader` is non-null before calling `Dispose` on it.
=> Make FastSerialization.Deserializer.Dispose Callable Multiple Times

src/perfcollect/perfcollect
- Add back the `-threadtime` parameter, which now properly collects `cpu-clock` and `sched` events.  This is accomplished by not specifying the `-F` parameter to `perf record`, and using the default sampling rate.  PerfView must adjust its handling of `cpu-clock` events to not assume that they come 1ms apart, but instead keep track of how often they come and dynamically adjust the sample metric.  This is done in #1213.
- Capture `jit-<pid>.dump` files in case they are needed for debugging.
- Don't log a warning when crossgen isn't present if `jit-<pid>.dump` files are present.
=> Add Back perfcollect -threadtime

src/LinuxEvent.Tests/EventParseTests.cs, src/LinuxEvent.Tests/Sources/one_complete_switch_format2.perf.data.dump, src/TraceEvent/Stacks/Linux/LinuxPerfScriptEventParser.cs, src/TraceEvent/Stacks/Linux/LinuxPerfScriptStackSource.cs
With this PR, and an accompanying change to `perfcollect` it is now possible to analyze threadtime (CPU and blocked time) of a Linux application.
- Don't depend upon `sched` events being emitted every 1ms.  Instead, keep track of how often they are emitted per CPU and use that to calculate the metric applied to the sample.
- Add support for another format of the `sched:sched_switch` event encountered on Debian.
=> Fix PerfView ThreadTime View When Capturing cpu-clock and sched Events

src/PerfView/GcStats.cs
There are two bugs in the condemned reason table construction logic:
- To determine if we should render a column. We wanted to fill `columnHasContent` array. When my original code scans a row, it stops whenever it reaches a column with data in it. We should not stop there, the remaining column could also have data. The break was intended to stop trying other rows, not other columns, in order to do that, I need to swap the loop order.
- `FillCondemnedReason` is called twice, once for `PerHeapHistory` and again for `GlobalHeapHistory`. The intent was to capture both, but my implementation overwrote the data instead of accumulating them.
=> Fix the condemned reason table construction logic

src/PerfView/CommandProcessor.cs
Make sure that the `DataFile` argument gets updated to include an ".etl" file extension if one is not specified.  Without this, `/NetCapture` is broken because UI setup code will change the file name to `PerfViewData.etl.zip` because it doesn't have a valid file extension.
Fixes #1211.
cc: @yang-er, @suprak
=> Fix /NetCapture When DataFile Does Not End With ".etl"

src/LinuxEvent.Tests/EventParseTests.cs, src/LinuxEvent.Tests/Sources/corner_case_process_names.perf.data.dump, src/TraceEvent/Stacks/Linux/LinuxPerfScriptEventParser.cs
- Handle process names that are just numbers.
- Add a regression test for corner case process names.
cc: @mjrousos
=> Handle More Corner Case Process Names in Linux Traces

src/Directory.Build.props, src/PerfView/PerfView.csproj, src/TraceEvent/NativeDlls.cs
The latest version of msdia140.dll depends upon msvcp.dll which in turn depends upon vcruntime140.dll.  This change includes them in the support files package for TraceEvent and also modifies how we load native binaries to ensure that they can be found when msdia140.dll is loaded.
=> Update to TraceEvent SupportFiles1.0.20 to Fix Missing Dependencies

src/TraceEvent/NativeDlls.cs
#1256 introduces a new version of msdia140.dll that has new dependencies.  The change included usage of `SetDllDirectory` to make sure that calls to `LoadLibrary` find the dependencies.  Upon further review, we can simplify this code by instead calling `LoadLibaryEx` and passing the `LOAD_LIBRARY_SEARCH_DLL_LOAD_DIR` flag.
=> Replace SetDllDirectory usage with LOAD_LIBRARY_SEARCH_DLL_LOAD_DIR usage

src/Directory.Build.props, src/TraceEvent/Microsoft.Diagnostics.Tracing.TraceEvent.nuspec, src/TraceEvent/TraceEvent.csproj
Include msvcp140.dll and vcruntime140.dll in TraceEvent NuGet package.
=> Fix msdia140 Dependencies in TraceEvent NuGet Package

documentation/Downloading.md
The link tends to send folks to the wrong place.
=> Remove the Download Center Link

src/TraceEvent/Computers/TraceManagedProcess.cs, src/TraceEvent/Computers/TraceProcess.cs
`TraceProcessExtensions` and `TraceLoadedDotNetRuntimeExtensions` both root the dispatcher to ensure non-concurrent access.  But once usage is complete, they hold the dispatcher until the process exits or the dispatcher is replaced.  Replace the strong reference with a weak reference so that memory associated with the dispatcher can be freed.
cc: @ivdiazsa
=> Don't Root TraceEventDispatcher in TraceProcessExtensions and TraceLoadedDotNetRuntimeExtensions

src/Directory.Build.props, src/PerfView/PerfView.csproj, src/TraceEvent/Microsoft.Diagnostics.Tracing.TraceEvent.nuspec, src/TraceEvent/Microsoft.Diagnostics.Tracing.TraceEvent.props, src/TraceEvent/TraceEvent.csproj
vcruntime140.dll on amd64 has an extra dependency on vcruntime140_1.dll.  This change includes vcruntime140_1.dll in supportfiles and consumes it from TraceEvent and PerfView.
Fixes #1268.
=> Add vcruntime140_1.dll for amd64

src/perfcollect/perfcollect
- Enable perfcollect to fallback to versions of `perf` that don't exactly match the kernel that is installed.
- Fix installation of `perf` in Azure containers.
=> PerfCollect Improvements for Azure Containers

src/TraceEvent/ZippedETL.cs
I noticed that the .etl.zip files that we capture via the Visual Studio Standard Collector Service use "PDBCache" for their symbols instead of symcache.
This causes errors when unzipping because the PDBCache folder isn't recognized. That further causes symbol resolution failures.
=> Match pdbcache folder in .diagsessions

src/PerfView/MainWindow.xaml.cs
Seems like "unmergedFiles" collection is not used anywhere. So no need to fill it.
=> Remove useless code

src/PerfView/JitStats.cs, src/TraceEvent/Computers/TraceManagedProcess.cs, src/TraceEvent/Parsers/ClrTraceEventParser.cs
Added a new event `MethodJitMemoryAllocatedForCode`  in https://github.com/dotnet/runtime/pull/44030 to log the JIT 's memory request for code. This PR displays that information in PerfView.
Here is the screenshot:
=> Display JIT Allocated Heap Size

src/TraceEvent/Symbols/NativeSymbolModule.cs, src/TraceEvent/Symbols/PortableSymbolModule.cs, src/TraceEvent/Symbols/SymbolReader.cs
This PR exposes some additional information from the SourceFile classes. This also fixes some issues with source file handling
- In addition to the URL property, there is now a new 'GetSourceLinkInfo' method that exposes the URL and the relative file path
- The checksum value/algorithm is exposed
- NativeSymbolModule now implements IDisposable using IDiaSession3.dispose
- The old code didn't calculate checksum's in Windows PDBs for managed code correctly - it only expected the 'C++ way' of encoding checksums, but that isn't how diasymreader.dll does it.
- The old code serched for sourcelink info in a native PDB via a very hacky method. This switches to doing things the right way. Along with this, I had to tweak the internal interface used to return source link data into something that …
=> TraceEvent symbol handler source file improvements

src/TraceEvent/Microsoft.Diagnostics.Tracing.TraceEvent.nuspec
Fixes #1301, see that for more info.
=> Added TraceEvent.props to nuspec also as buildTransitive

src/EtwHeapDump/DotNetHeapDumpGraphReader.cs, src/HeapDumpCommon/DotNetHeapInfo.cs, src/PerfView/PerfViewData.cs, src/TraceEvent/Parsers/ClrTraceEventParser.cs
Here are the changes required to decode the traces produced by generational aware analysis I introduced in https://github.com/dotnet/runtime/pull/40332
Notice the latest change requires https://github.com/dotnet/runtime/pull/41052
=> Decoding traces produced by generational aware analysis.

src/TraceEvent/Symbols/SymbolPath.cs
Removing dotnet.myget.org, as it's been decomissioned.
cc: @gregg-miskelly
=> Remove dotnet.myget.org symbol server from the default symbol path

src/PerfView.Tests/StackViewer/StackWindowTests.cs
Added unit tests for when setting `StartText` and `EndText` on `StackWindow`.
`TestSetTimeRangeInStartTextBoxRuRu03Async` is skipped because there's a bug in the implementation for cultures with white spaces as number group separator ou decimal number separator.
=> Added range unit tests to StackWindow

src/EtwHeapDump/EtwHeapDump.csproj
This change eliminates an unnecessary dependency on the target framework definition.
=> Simplify EtwHeapDump.csproj project file

src/HeapDump/CrossGenerationLiveness/IDebugClient.cs
This change simplifies the transition to ClrMD 2.0 for builds where `CROSS_GENERATION_LIVENESS` is not defined.
=> Condition IDebugClient.cs on CROSS_GENERATION_LIVENESS

src/TraceEvent/TraceEvent.cs, src/TraceEvent/TraceLog.cs
Fixes #1345.
This is a regression from #1277, which adds storage for the ContainerID, and changes how storage of the RelatedActivityID is stored in the ETLX file.
=> Fix RelatedActivityID storage and lookup in ETLX

Nuget.config
Builds should only require official NuGet packages and consumption of locally build `SupportFiles` packages.
=> Don't Depend on NuGet.org Inheritance

src/TraceParserGen/ETWManifest.cs
{0} was printed instead of xml element name.
Wrong overload of Debug.WriteLine was called.
=> TraceParserGen: Fix incorrect debug string format.

src/TraceParserGen/TraceParserGen.cs
Partial revert of 46a2f3a73fd91fc2b0ae30440666589a9ca72212
I think that @billwert introduced issue here.
It looks like internalOpt should be used to insert "internal" keyword instead of hardcoding it in string.
If "Internal" would be set, the it would generate double "internal" in function header.
=> TraceParserGen: Remove internal keyword when not requested.

src/PerfView/CommandLineArgs.cs, src/PerfView/CommandProcessor.cs
With the proliferation of async/await, the TPL events have become more and more verbose, to the point where enabling them preturbs the CPU profiling data fairly heavily in some workloads.  This change makes them opt-in.
cc: @davidfowl, @stephentoub
=> Make Collection of TPL Events Opt-In

src/TraceEvent/RegisteredTraceEventParser.cs
Fixed length arrays are detected by either a element count > 1 or the presence of the fixed count flag.
=> Fix detection of fixed-length array parameters in TraceLogging events

src/PerfView/SupportFiles/UsersGuide.htm
Documentation only PR.
The samples provided in the release notes are invalid (and inconvenient due to `li`):
- The JSON is invalid - missing a `]`
- The XML is invalid - missing a closing `</Sample>` tag
- XML example text incorrectly names sample 2 as sample 1
- Changed the layout to `<pre>` so that you can copy/paste it
**For your convenience:**
JSON before:
JSON after:
XML before:
XML after:
=> Fix sample JSON and XML in release notes

src/TraceParserGen/ETWManifest.cs
Fixed InvalidOperationException: Collection was modified after the enumerator was instantiated.
fix #1394
=> TraceParserGen: Exception in UpdateStrings()

src/PerfView/CommandProcessor.cs
ClrStack/Walk events are unintentionally enabled during rundown if any of the rundown suppression arguments are used.  This can result in a large number of stacks that can't be matched to CLR events and overall slower conversion of an ETL file to ETLX.
An example configuration where this occurs is with `/GCCollectOnly` traces where the fully expanded commandline includes `/NoRundown`:
```
PerfView /RestartingToElevelate:collect /DataFile:PerfViewGCCollectOnly.etl /BufferSizeMB:256 /StackCompression /KernelEvents:Process,ImageLoad /ClrEventLevel:Informational /ClrEvents:GC /NoGui /SessionName:PerfViewGCSession /NoRundown /GCCollectOnly Collect
```
These events are not needed during rundown, but are enabled because rundown for V2.0 runtimes occurs via the public provider instead of the …
=> Disable ClrStack/Walk Events During Rundown

src/PerfView/GcStats.cs, src/TraceEvent/Computers/TraceManagedProcess.cs, src/TraceEvent/Parsers/ClrTraceEventParser.cs
This change allows us to view the POH data in the raw XML view.
@brianrob
@Maoni0
=> Show POH PerHeapHistoryData in Raw XML view

src/TraceEvent/TraceEventNativeMethods.cs, src/TraceEvent/TraceEventSession.cs
Expose `EVENT_TRACE_NO_PER_PROCESSOR_BUFFERING` via `TraceEventSessionOptions.NoPerProcessorBuffering`.
=> Allow TraceEventSession to set EVENT_TRACE_NO_PER_PROCESSOR_BUFFERING

src/PerfView/EventViewer/EventWindow.xaml.cs
When stack views are opened from the Event View, they currently clear out most of the filter parameters from their configured defaults.  This change reverts most of this change because the view has been properly configured based on the stack source requested.
=> Keep Default Filter Parameters in Stacks from Event Viewer

src/TraceEvent/TraceEventSession.cs
Correct `TraceEventSessionOptions` values so that they can be specified independently or together as unique flags.
=> Fix incorrect TraceEventSessionOptions Flag Values

src/TraceEvent/Stacks/SpeedScopeStackSourceWriter.cs
This commit updates SpeedScopeStackSourceWriter to emit startValue and endValue as numbers, in line with the [JSON schema](https://www.speedscope.app/file-format-schema.json).
=> Use numbers for startValue and endValue

src/PerfView/StateMachineFramework/ComputingResourceStateMachine.cs, src/PerfView/StateMachineFramework/ServerRequestComputer.cs
`RegisterEventHandlers` is currently marked as internal, which means that consumers of the `StateMachineFramework` in PerfView extensions are unable to register their own event handlers.
=> Make RegisterEventHandlers Public

src/PerfView/StackViewer/StackWindow.xaml.cs
This is implemented in PerfView itself, rather than in TraceEvent, so that consumers of TraceEvent can make their own transport decisions.
=> Default to TLS 1.2 for Source Lookup

src/PerfView/PerfViewData.cs
As discussed in https://github.com/dotnet/runtime/issues/48937, I removed the check to `AppLog.InternalUser` for the views and expose them directly.
=> Expose the generational aware views

src/TraceEvent/Parsers/ClrTraceEventParser.cs
- Depends on https://github.com/dotnet/runtime/pull/53471
- The change above added a new reason for thread adjustment (`CooperativeBlocking`), added here too
=> Add a thread adjustment reason

src/PerfView/PerfViewData.cs
Adding advanced tabs for File Queries and Directory Enumeration operations.
These are both a simple copy of the File I/O tab.  Both use hit count as the metric where File I/O uses total I/O size.
=> Add Advanced tabs for File Queries and Directory Enumeration

src/PerfView/SupportFiles/UsersGuide.htm
Removed the text "under the assumption that the file" for the help of `/noView run` because it was duplicated in the sentence.
=> Removed duplicated text from UsersGuide.htm

src/PerfView/CommandProcessor.cs
Right now, it's possible for a trace to contain CPU/ThreadTime samples from CLR rundown, as sessions are stopped asynchronously.  Fix this by moving CLR rundown to start after all sessions are stopped.
=> Move CLR rundown to start after all sessions are stopped

src/TraceEvent/Parsers/ClrTraceEventParser.cs
Depends on https://github.com/dotnet/runtime/pull/55295
=> Update for new event that contains info about spin-wait pause/yield normalization

src/TraceEvent/TraceEventSession.cs
The current File Queries and Directory Enumerations stack views don't show the full stack if the trace was collected with PerfView, because stacks are never enabled for these events.  This PR enables stack collection for these events.
=> Enable stacks for more FileIO events

src/PerfView/SupportFiles/UsersGuide.htm
I assume that File menu was split as part of improvement, but docs remain stale.
=> Documentation reference to incorrect commands location

src/TraceEvent/Computers/TraceManagedProcess.cs, src/TraceEvent/Parsers/ClrTraceEventParser.cs
1) interpret more fields from the perheap hist event;
2) add more types for the mark event for .net 6;
=> GC events changes

src/PerfView/PerfViewData.cs
The pseudo node for each entry in the Directory Enumeration view assumed there was a file name, and so entries were incorrect.
=> Fix Directory Enumeration Pseudo Node

src/PerfView/PerfViewData.cs, src/PerfView/memory/GCHeapSimulator.cs
Work around a reported object size of 0 when profiling allocations through the CLR profiler API.
=> Don't Divide By Zero When Profiling Allocations

src/PerfView/memory/PdbScopeMemoryGraph.cs
After running ImageSize command on the NativeAOT generated image
It fails beause `SampleWindowsForms__Module___StartupCodeMain` symbol has `src="<stdin>"` after importing image. I simply workaround this issue, assuming that no other cases like that exists.
=> Fix opening NativeAOT images

src/TraceEvent/TraceLog.cs
https://github.com/microsoft/perfview/issues/1445 shows issues with current schema to detect if a address is in kernel address space. On none Windows platforms the implemented rules are not correct causing issues to display stack traces on nettrace files captured on some configurations of none Windows platforms (Android is one example).
EventPipe nettrace files only include stack traces with managed frames and only user mode code addresses, so addresses should never be in kernel address space and since the heuristics miss fire on none Windows platforms, this commit adds logic to always detect addresses using a process hooked up to an EventPipeEventSource to not be in kernel address mode. None EventPipeEventSource event sources will continue to work as before.
=> Fix issue with IsKernelAddress on none Windows platforms.

src/TraceEvent/Computers/StartStopActivityComputer.cs
For example, activityid: 0001111d-0000-0000-0000-00007bc7be59
Before:
`ActivityPathString("0001111d-0000-0000-0000-00007bc7be59")` returns `0001111d-0000-0000-0000-00007bc7be59`;
After:
`ActivityPathString("0001111d-0000-0000-0000-00007bc7be59", 2125233)` returns `#/2125233/xxx/`
Reason:
```csharp
// Validation will pass with proper pid:
bool isIt1 = StartStopActivityComputer.IsActivityPath(Guid.Parse("0001111d-0000-0000-0000-00007bc7be59"), 2125233);
// What we had assumed 0 as the pid and would fail the validation:
bool isIt2 = StartStopActivityComputer.IsActivityPath(Guid.Parse("0001111d-0000-0000-0000-00007bc7be59"), 0);
// The process id and other info is actually valid. For example, get the pid from the guid, this returns 2125233
int pid = …
```
=> Allows getting ActivityPathString by providing process id

src/FastSerialization/FastSerialization.cs, src/FastSerialization/StreamReaderWriter.cs, src/TraceEvent/TraceEvent.Tests/FastSerializerTests.cs
Currently, the `FastSerialization` library only supports 32-bit file sizes due to the requirement that a serialized file must be able to point to any location in the file with a single 32-bit address.
This is the first of a set of PRs that will be forthcoming to enable support for 64-bit serialization.  This PR does not update any components to use the 64-bit serialization support - it merely makes it available on an opt-in basis with no backwards compatibility support.  Backwards compatibility support will be included in a subsequent PR.
=> Opt-In 64-bit StreamLabel Support

src/FastSerialization/SegmentedDictionary/SegmentedDictionary.cs, src/FastSerialization/SegmentedList.cs, src/FastSerialization/SegmentedMemoryStreamReader.cs, src/FastSerialization/SegmentedMemoryStreamWriter.cs, src/HeapDump/GCHeapDump.cs, src/MemoryGraph/MemoryGraph.cs, src/MemoryGraph/graph.cs
These changes are a continuation of the following PRs:
* [1486](https://github.com/microsoft/perfview/pull/1486) Let SegmentedList Handle more than 2^31-1 elements
* [1488](https://github.com/microsoft/perfview/pull/1488) SegmentedDictionary Initial Implementation and Tests
* [1491](https://github.com/microsoft/perfview/pull/1491) Opt-In 64-bit StreamLabel Support
In summary we are hooking everything together, and able to process large memory heap dumps. The actual changes are:
1. SegmentedDictionary.cs and SegmentedList.cs have minor improvements and make sure we don't delete public methods and that new methods that were added for this scenario remain internal.
2. SegmentedStreamReader.cs takes a `SerializationConfiguration` instance specifying if it should treat `StreamLabel` instances …
=> Use new SegmentedList and SegmentedDictionary to process large heap dumps

src/PerfView/MainWindow.xaml
This tightens the margins on the directory & filter textboxes and the RichTextBox to reduce the false border around them and makes them look cleaner.
Before:
After:
=> Tighten the margins on directory/filter textboxes

src/PerfView/MainWindow.xaml
This also removes leading separator on the File menu.
Before:
After:
=> Move Hide to be close to Exit

src/PerfView/GuiUtilities/HistoryComboBox/HistoryCombBox.cs
This changes the textbox autocomplete to work like a modern browser so that when it autocompletes, pressing enter navigates to the autocompleted location. Previously this would attempt to navigate to _just_ to the text that you had just typed. This bit me constantly.
In this scenario, I enter `C:\Temp\` and expect that when I press enter, the full autocompleted location is navigated to instead of just `C:\Temp`.
Before:
After:
**Note:** PerfView has odd behavior where it navigates based on the textbox losing focus. This behavior also affects that scenario, there's not an app that I know that works like this with or without this behavior. Thoughts on this?
=> Fix textbox autocomplete to work like modern browsers

build.cmd
- Restore projects on build
- This changes MSBuild to restore packages on build, to avoid immediately getting
building about missing assets files the first time you clone the repository. This
added 1.8 seconds to build time on my i7-9700k if restore is up-to-date.
- Use multi-proc build 
- This opts into multi-proc build which reduced up-to-date build from ~8 seconds
down to 6 seconds on my i7-9700k.
=> Restore and opt into multi-proc on build

src/PerfView/MainWindow.xaml, src/PerfView/MainWindow.xaml.cs
Hide was always enabled despite only ever working if you had a stack window open.
=> Disable hide when its not available

src/PerfView/Dialogs/RunCommandDialog.xaml
Fixed typo in the Circular MB tooltip from metabytes to megabytes. To fix: https://github.com/microsoft/perfview/issues/1315
=> Fixed typo in the Circular MB tooltip

src/Directory.Build.props, src/NugetSupportFiles/Microsoft.Diagnostics.Tracing.TraceEvent.SupportFiles/Microsoft.Diagnostics.Tracing.TraceEvent.SupportFiles.nuspec, src/TraceEvent/Microsoft.Diagnostics.Tracing.TraceEvent.nuspec, src/TraceEvent/Microsoft.Diagnostics.Tracing.TraceEvent.props, src/TraceEvent/NativeDlls.cs, src/TraceEvent/TraceEvent.csproj
With this change, TraceEvent now supports execution within native arm64 processes.  This change does not impact PerfView, which still supports x86 and amd64, and can be run via emulation on arm64.
=> TraceEvent Support for arm64

src/HeapDump/Program.cs, src/PerfView/Triggers.cs
CLR performance counters belonging to 64-bit processes are not visible from 32-bit processes, such as PerfView.exe.  As such, PerfView must shell out to a 64-bit process when creating triggers on performance counters belonging to these processes.  `/MinSecForTrigger` was not properly plumbed through this path, and so this change plumbs it through.
Thanks @maoni0 for reporting this.
=> Fix /MinSecForTrigger for CLR counters of 64-bit processes

src/PerfView/MainWindow.xaml, src/PerfView/MainWindow.xaml.cs
This adds two new commands mimicing Visual Studio's behavior.
**Open Folder:** Opens a folder in Windows Explorer
**Open Containing Folder:** Opens a file, selecting it, in Windows Explorer
This also has a behavior change for Menu Items, which is to hide them when they are not enabled.
=> Add Open Folder/Open Containing Folder commands

src/TraceEvent/TraceLog.cs
Remove the 20M event limit now that ETLX files can support file sizes larger than 4GB.
=> Remove Default Event Limit

PerfView.sln, src/FastSerialization/FastSerialization.cs, src/HeapDump/GCHeapDump.cs, src/PerfView/PerfView.csproj, src/PerfView/app.config, src/PerfView64/App.config, src/PerfView64/App.cs, src/PerfView64/PerfView64.csproj, src/PerfView64/Properties/AssemblyInfo.cs, src/PerfView64/app.manifest, src/TraceEvent/EventPipe/EventPipeEventSource.cs, src/TraceEvent/TraceLog.cs
I am starting to work on a PerfView/TraceEvent 3.0, and inadvertently checked these into main.  I am reverting them here, and will keep them in the feature/perfview-3.0 branch.
=> Revert PerfView/TraceEvent 3.0 Changes from Main

documentation/Downloading.md
Getting the right release link to show up on Downloading.md involves creating the releases in the right order.  Try as I might, I still mess this up occasionally.  To address this, I have changed the link to just point to the releases page, so that folks can find the latest release directly.
=> Change Download Link on Downloading.md

src/TraceEvent/Stacks/ChromiumStackSourceWriter.cs, src/TraceEvent/Stacks/SpeedScopeStackSourceWriter.cs, src/TraceEvent/Stacks/StackSourceWriterHelper.cs, src/TraceEvent/TraceEvent.Tests/SpeedScopeExporterTests.cs, src/TraceEvent/TraceEvent.csproj
Today I've tried to convert a trace provided by the customer in https://github.com/dotnet/runtime/issues/63621#issuecomment-1010030287 to Chromium trace file format. I was able to save the file, but unable to load it in Chromium Developer Tools (F12).
It turned out that the Chromium/Speedscope exporters were not escaping some of the strings correctly.
=> Fix JSON escaping

src/TraceEvent/Computers/TraceManagedProcess.cs
There are a number of properties in the ``TraceGC`` and its related classes that contain the ``Obsolete`` attribute. In reality these __were __experimental and can now that decoration can be removed as they are used across the board. 
The presence of this attribute is causing noise with warnings in all the clients that make use of this API.  
CC: @Maoni0
=> Removed the Obsolete Attribute for GC properties

src/FastSerialization/FastSerialization.cs, src/FastSerialization/StreamReaderWriter.cs, src/TraceEvent/EventPipe/EventPipeEventSource.cs, src/TraceEvent/TraceEvent.Tests/EventPipeParsing.cs
IOStreamStreamReader had a hard coded 8 byte alignment. EventPipe streams do not have any alignment requirements (save for some 4 byte alignments inside blocks). This means that blocks can have sizes that are not aligned. EventPipeEventSource will not dispatch events read from the stream until reads complete. In live cases where these blocks are unaligned, but no new data is coming down the pipe, the reader can attempt to enforce the alignment and end up blocking until new data arrives. This results in latency for event dispatch. For infrequent events, this can be a long period of time causing users to think they haven't received events.
For example:
EventBlock 1, EventBlock 2, and EventBlock 3 all arrive with aligned lengths. EventBlock 4 arrives with an unaligned length. Until more data …
=> Add configurable alignment to FastSerializer

src/HeapDump/Program.cs, src/PerfView/memory/HeapSnapshot.cs
Warn the user if they attempt to convert a Linux process dump that this is not supported.  Currently, the user gets a failure that doesn't make this clear.
Fixes #1562.
=> Warn User That Linux Process Dumps Aren't Supported

src/PerfView/UserCommands.cs
Hello,
I was reading through for examples of `MutableTraceEventStackSource` used in anger and spotted some small typos, I thought that I might as well submit a PR to fix it whilst I was here, thanks for the great project! :)
Thanks,
Michael Radigan
=> Fix two small typos in UserCommands.cs

.ado.yml, Nuget.config
This switches the source of dependencies to a Microsoft-owned feed.  This should have no impact on functionality.
=> Switch to Azure Artifacts Feeds for Build Dependencies

src/PerfView/EtwEventSource.cs
Was previously "HasBlockedStack" and so it was always an empty column because the field is called `HasBlockingStack`.
=> Fix HasBlockingStack Column Text

src/PerfView.Tests/GraphSerialization/GraphSerializationTests.cs
To prevent the test GenerateBaselineXmlFiles from using two different time formats, the attribute UseCulture("en-US") is added.
fixes #1581
=> Added Attribute UseCulture("en-US") to prevent another time format from being taken

src/TraceEvent/Computers/TraceManagedProcess.cs, src/TraceEvent/Parsers/ClrTraceEventParser.cs
Parser support for OSR.
OSR methods jit on foreground threads.
=> Add support for OSR jitted code

src/FastSerialization/FastSerialization.cs, src/HeapDump/GCHeapDump.cs, src/TraceEvent/EventPipe/EventPipeEventSource.cs, src/TraceEvent/TraceLog.cs
It looks like an earlier merge caused a couple of 64-bit fixes to be reverted in the PerfView 3.0 branch.  Bringing them back with this PR.
=> Cherry-Pick Missing 64-bit Fixes and Improve Conversion Reporting

src/TraceEvent/EventPipe/EventPipeEventSource.cs
This PR makes the constructor for `EventPipeEventSource` non-blocking. Previously, the constructor would block until data was sent on the stream. This brings `EventPipeEventSource` closer in behavior to other similar APIs in the TraceEvent library.
~One issue that isn't solved by this PR (yet) is that we need to handle the case where users try to get metadata about the source before data arrives. Before this PR, users were guaranteed to have that information when the ctor returned. Now, this is only true for opening a completed file, hence the special casing for files. Currently, this PR makes no attempt to stop users from reading metadata properties. _I am hoping for some feedback on whether this should throw an exception or now. Until this is decided, I'll leave this in draft mode._~ …
=> Non-blocking EventPipeEventSource Ctor

src/TraceEvent/EventPipe/EventCache.cs
fixes #1474 
CC dotnet/runtime#67216 (note this will require a TraceEvent update to fix)
CC dotnet/runtime#54801
CC dotnet/runtime#59448
As described in #1474, the sequence of calls on a `ref` parameter result in it being passed as a pointer, so the underlying pinned buffer is no longer referenced. This patch adds a `GC.KeepAlive` which should keep the memory referenced through the whole function duration.
=> Use GC.KeepAlive to prevent GC hole

src/TraceEvent/TraceEventSession.cs
Removes an extra ETW flush command that is not needed, since rotating the trace file by setting the file name will cause ETW to automatically flush.  In some situations, this extra flush can cause lost events.
=> Remove superfluous flush from TraceEventSession.SetFileName

src/PerfView/CommandLineArgs.cs
Disable rundown for pre-v4.0 runtimes by default.  This can be re-enabled from the command line via `/NoNGENRundown:false`.  Given that most processes are running v4.0+ runtimes, this should not have much impact, but should reduce the trace size since there is some overlap in events that are emitted for v4.0+ runtimes with these settings enabled.
=> Disable NGEN Rundown By Default

src/TraceEvent/TraceLog.cs
There was a bug in real-time ETW session stack processing where the stack gets attributed to the next event that comes in, and not the current event.  This resulted in incorrect stacks being exposed from `TraceEvent.CallStack` and `TraceEvent.CallStackIndex` specifically for real-time sessions.
=> Fix Real-Time Session Stack Attribution

src/TraceEvent/DynamicTraceEventParser.cs
Starting with .NET 6, the runtime will emit the Microsoft-Windows-DotNETRuntime manifest into the event stream.  This results in two instances of the manifest:
- The pre-compiled copy of the manifest: `ClrTraceEventParser`
- The dynamic copy of the manifest which enables `DynamicTraceEventParser` to parse the CLR events
Normally, this would not be a problem, except that there is lots of code out there that knows that Microsoft-Windows-DotNETRuntime is not a dynamic provider, and so now that this provider manifest is written into the event stream, that code breaks.
This fix will cause `DynamicTraceEventParser` to ignore manifest events for the `Microsoft-Windows-DotNETRuntime` provider so that the previous behavior is restored.
Fixes #1591.
cc: @noahfalk, @josalem
=> Ignore the Microsoft-Windows-DotNETRuntime Dynamic Manifest

src/PerfView/Dialogs/RunCommandDialog.xaml.cs
When KernelBasedCheckBox is false, the default value is `KernelTraceEventParser.Keywords.Default`, which still has kernel events enabled.
=> Kernel based event can not be disabled on UI

src/TraceEvent/TraceEvent.cs
Hopefully this will help clarify where these exceptions are being thrown in the CI.
=> Emit the full stack when an exception is thrown during dispatch.

src/PerfView/SupportFiles/UsersGuide.htm
This is reflects fact that minimum requirements for PervView is .NET 4.6.2
And as such minimum OS supported is OS which able to install .NET 4.6.2
When made changes I made some assumptions on supported OS,
which maybe too strict, and actual support wider.
=> Update docs to mention .NET 4.6.2

src/PerfView/ClrStats.cs, src/PerfView/FileVersionInformation.cs, src/PerfView/PerfViewData.cs, src/PerfViewCollect/PerfViewCollect.csproj
Uses the `KernelTraceControl/ImageID` events to produce an HTML report with version information for loaded modules in each process.
=> New Module Version Report

src/Directory.Build.props, src/FastSerialization/FastSerialization.csproj
FastSerialization does not currently have an explicit version set, so it is always 1.0.0.0.  Breaking changes to FastSerialization can break when there are apps that have conflicting copies of FastSerialization with different versions.
This change allows us to explicitly version FastSerialization and sets the version number to 3.0.0.
=> Explicitly Version FastSerialization

src/Directory.Build.props, src/HeapDump/GCHeapDumper.cs, src/HeapDump/HeapDump.csproj, src/HeapDump/Program.cs, src/PerfView/PerfView.csproj, src/TraceEvent/Microsoft.Diagnostics.Tracing.TraceEvent.nuspec, src/TraceEvent/TraceEvent.csproj
Update ClrMD to 2.0.
- Updated to ClrMD 2.0.
- Removed special casing of dependent handles.  These are tracked by ClrMD now and will show up as normal edges in the graph.  We can do more here if this is confusing.
- Removed a lot of the heap walking retry code.  The benefit of not retrying is it's a LOT faster, and the old code was not entirely correct.  The downside is that when there is a legitimate heap walking failure then we can miss part of a segment.
=> Update ClrMD to 2.0

src/TraceEvent/Symbols/SymbolReader.cs
This fixes NGEN PDB creation during trace merge/zip when the NGEN image is loaded into an arm64 process.
=> Map ARM64 NIC Paths to ARM64 ngen.exe for NGEN PDB Creation

src/PerfView/PerfViewData.cs
Add `[group modules]` and `[group module entries]` to `XMLStackSource` stack windows.
=> Add Group Patterns to XMLStackSource Stack Windows

src/TraceEvent/Symbols/SymbolReader.cs
Fix for issue I reported earlier: https://github.com/microsoft/perfview/issues/1222
This fixes lookup for PDBs with age greater than 9.
Ran the tests, all groups passed. Not sure if there's anything else to include for this bugfix since the details are in the issue thread.
Thanks for your consideration.
=> Fix for SymbolReader's Age field rendering not following SSQP Key Conventions

src/Directory.Build.props, src/HeapDump/GCHeapDumper.cs, src/HeapDump/HeapDump.csproj, src/PerfView/PerfView.csproj, src/TraceEvent/TraceEvent.csproj
Version bump ClrMD to 2.1.
- Disable AWE reader.
- Use ClrObject.EnumerateReferenceAddresses to avoid looking up the type when we do not need it.
=> Update to ClrMD 2.1

documentation/TraceEvent/TraceEventProgrammersGuide.md, src/PerfView/SupportFiles/PerfViewWebVideos.htm
Per https://github.com/microsoft/perfview/issues/1538#issuecomment-1158241094, videos are now available at https://docs.microsoft.com/en-us/shows/perfview-tutorial/.  Update links embedded in help and video docs.
Fixes #1538.
=> Update Video Links

src/PerfView/MainWindow.xaml, src/PerfView/MainWindow.xaml.cs, src/PerfView/StackViewer/PerfDataGrid.xaml.cs
This change adds an option to the main PerfView "Options" dropdown labeled:
"Do not shorten frames copied from stack windows" (this can be changed if there is other better wording)
This option allows the user to opt-in to paste frames from stack windows as-is and unchanged.
Without option enabled (current behavior):
```
+ System.Private.CoreLib.il!AsyncTaskMethodBuilder.Start
+ System.Private.CoreLib.il!AsyncMethodBuilderCore.Start
+ Microsoft.AspNetCore.Server.Kestrel.Core.il!Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol+<ProcessRequestsAsync>d__213`1[System.__Canon].MoveNext()
+ Microsoft.AspNetCore.Server.Kestrel.Core.il!HttpProtocol.ProcessRequests
+ System.Private.CoreLib.il!AsyncTaskMethodBuilder.Start
+ System.Private.CoreLib.il!AsyncMethodBuilderCore.Start
+ …
```
=> Add option: Do not truncate/shorten stack frames on paste

src/TraceEvent/ETWTraceEventSource.cs
As part of trace zip, `ZippedETLWriter` generates the list of NGEN images that need PDBs created and then generates them.  It creates this list by tracking the set of per-process image loads, and then comparing the address space of each of the images to CPU sample and stack hits.
There is an optimization when generating the list of images that only includes the first instance of any given image in the list, which is incorrect because all of the comparisons are per-process since they operate over per-process virtual address space.
This change removes the optimization and forces the code to consider every possible NGEN image for each process.
=> Check all instances of loaded images for NGEN PDB generation

documentation/TraceEvent/SymbolReader/AzureDevOpsPATAuthenticationExample.cs, src/TraceEvent/Symbols/SymbolReader.cs
Allow users of `SymbolReader` to create a [DelegatingHandler](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.delegatinghandler?view=net-6.0) to control `HttpClient` behavior.
The most immediate usage of this is for authentication to symbol servers.  This change includes an example of how to perform Azure DevOps authentication via a personal access token.
=> SymbolReader DelegatingHandler Support

src/PerfView/CommandProcessor.cs
If `inputOptions` is `NULL`, create a new instance of `TraceEventProviderOptions`.
Fixes #1660.
=> Fix TraceEventProviderOptions Handling

src/PerfView/Extensibility.cs
Fixes #1669.
When running the SaveCPUStacks user command, it is possible for the PerfView log to be locked.  If this happens, ignore the failure and proceed with saving the stacks.
=> Ignore Failures When Saving the Log File

src/PerfView/GcStats.cs
The GCStats summary for a process should have the Number of Heaps:
CC: @Maoni0
=> Added the Number of Heaps in the Summary of the GCStats window

src/HeapDump/GCHeapDumper.cs, src/HeapDumpCommon/DotNetHeapInfo.cs, src/PerfView/memory/GenerationAwareMemoryGraph.cs
@Maoni0 reported that generational aware analysis in PerfView is not working for full core dumps. After debugging for a while, I have found a few bugs related to generation detection. This PR fixes some of them, the remaining ones are in ClrMD and are fixed [there](https://github.com/microsoft/clrmd/pull/1035).
**Note** - I changed the serialization format by adding information about POH, which I need help with backward compatibility. The CI failures are related to this.
@tommcdon - This might need to be replicated for `dotnet-gcdump`
=> Fix a few bugs related to object generation detection

src/TraceEvent/TraceEvent.csproj
`System.Reflection.Metadata` 1.8.1 is the first package to include an explicit
`net461` which allows the build to target inbox `System.*` dlls.
Specifically, this PR will cause the  `System.Net.Http` reference to drop down from `4.2.0.0` to
the correct version of `4.0.0.0`.
From the `GetDependsOnNETStandard` task in the binlog (previous output was `true`):
```
GetDependsOnNETStandard
Assembly = C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\Microsoft.NET.Build.Extensions\\tools\net472\Microsoft.NET.Build.Extensions.Tasks.dll
Parameters
References
System.IO.Compression
System.Net.Http
...
OutputProperties
DependsOnNETStandard = False
```
=> Update System.Reflection.Metadata to 1.8.1

src/TraceEvent/Microsoft.Diagnostics.Tracing.TraceEvent.nuspec
- Incorrect version of `System.Runtime.CompilerServices.Unsafe`.
- Incorrect release notes URL.
=> Fix TraceEvent nuspec Bugs

src/TraceEvent/Parsers/ClrTraceEventParser.cs
Support the `Pinned` value for `GCAllocationKind` fields on allocation events.
=> Add GCAllocationKind.Pinned

src/TraceEvent/EventPipe/EventPipeEventSource.cs
When running the UserCommand `NetperfToSpeedScope` with an invalid file name, PerfView crashes due to _deserializer being null.  When applied, this PR will do a null check before attempting to dispose of the object.
=> Add null check for Disposing EventPipeEventSource deserializer

Nuget.config
The local NuGet feed is not used.
=> Remove Local NuGet Feed

src/HeapDump/HeapDump.csproj
Fixes the following build warning:
```
"C:\src\perfview\src\HeapDump\HeapDump.csproj" (rebuild target) (1) ->
"C:\src\perfview\src\HeapDump\HeapDump.csproj" (Clean target) (1:2) ->
(CollectPackageReferences target) ->
C:\src\perfview\src\HeapDump\HeapDump.csproj : warning NU1504: Duplicate 'PackageReference' items found. Remove the duplicate items or use the Update functionality to ensure a consistent restore behavior. The duplicate 'PackageReference' items are: MicroBuild.Core 0.2.0, MicroBuild.Core 0.2.0.
```
=> Remove Duplicate PackageReference for MicroBuild

src/Directory.Build.props, src/PerfView/PerfView.csproj
Update TraceEvent.SupportFiles package to 1.0.24 which builds OSExtensions.dll against net462 instead of net45.  This is in reaction to #1691 to move the build to Visual Studio 2022 which no longer includes the .NET 4.5 targeting pack.
=> Update to TraceEvent SupportFiles 1.0.24

src/TraceEvent/TraceLog.cs
When a trace has not been merged TraceEvent does three extra checks to confirm that the on-disk binary matches the one that was present during the trace.  It compares:
- CheckSum
- ImageID
- File size
This change removes the file size check as it is not necessary, and is breaking in some scenarios where the loaded image size doesn't match the size in the PE header.
=> Remove PEFile Size Check in TraceModuleUnchanged

.ado.yml, src/PerfView/SupportFiles/UsersGuide.htm, src/PerfViewCollect/PerfViewCollect.csproj
This also eliminates a warning from the IDE when you load PerfView.sln on a machine without the .NET Core 2.1 runtime
=> Target netcoreapp3.1 in PerfViewCollect since 2.1 is out of support

src/TraceEvent/AutomatedAnalysis/Extensions.cs
A .nettrace file collected for an Asp.Net 6 app running on Azure App Service for Linux does not have coreclr as part of its loaded modules list.
=> Add more checks for managed processes

src/PerfView/PerfView.csproj
Fixes broken HeapDump.exe.  CLRMD 2.1 is built against `netstandard20` which uses version 4.0.2.0, which is not currently embedded into PerfView.
=> Embed System.Runtime.InteropServices.RuntimeInformation.dll 4.0.2.0 into PerfView

src/PerfView/Extensibility.cs, src/PerfView/SupportFiles/PerfView.xml, src/PerfView/UserCommands.cs, src/TraceEvent/TraceLog.cs
This PR adds a UserCommand to get PerfView data in a CSV format that is easy to understand since it directly correlates to the CPUStacks view and reuses the math PerfView already does when loading in the trace and outputs the data to a CSV.
This PR also adds another method of getting the process which is by the most amount of CPU msec used in the trace.
cc: @slevenstein who helped me understand how to get this data from within the PerfView application and wrote the basis which I iterated on and improved
=> Add UserCommand to save the CPUStacks view as a CSV

src/TraceEvent/TraceEventNativeMethods.cs, src/TraceEvent/TraceEventSession.cs
On `TraceEventSession` attach, the set of enabled providers is not looked up from ETW, which means that users that call `SetFileName` and have `CaptureStateOnSetFileName == true` do not actively make the calls to invoke the capture state command.
Fixes `CaptureStateOnSetFileName` by calling `EnumerateTraceGuidsEx` to fill the dictionary of enabled providers on session attach.
=> Fix CaptureStateOnSetFileName By Looking Up Enabled Providers on Attach

src/PerfView/CommandProcessor.cs
The minimal rundown keyword should be `ForceEndRundown` instead of a non-existent keyword.  This is required in order to support gathering the runtime version events from .NET Core.  .NET Core no longer unconditionally emits the runtime version event without actually asking for rundown, however, if we only specify `ForceEndRundown`, the runtime will skip the expensive parts of rundown and just emit the runtime version event.
=> Update Minimal Rundown Default Keyword

src/PerfView/OverweightReport.cs, src/PerfView/PerfView.csproj
When I used the regression report tool on two GC Dumps from an x64 Mac, it would try to make tags out of frames such as "Lib<</Applications/Example.app/Lib!Task<Example>>>" and turn it into things such as "LIB<>>". This change encodes reserved HTML characters, which should prevent this (In my example, it properly shows the original frame)
=> Use Encoded String in Regression Report

src/EtwHeapDump/DotNetHeapDumpGraphReader.cs
- Set `isVeryLargeGraph=true` for the in-memory graph representation.  NOTE: This graph doesn't get written to disk.
- Remove the 10M node limit.
cc: @Maoni0, @cshung
=> Support Arbitrarily Large ETW/nettrace Heap Snapshots

src/perfcollect/perfcollect
Like we do on Ubuntu, also walk the set of installed `perf` binaries on Debian if there isn't a version installed that matches the exact kernel version.  This is necessary for container scenarios where the container OS doesn't match the host OS exactly.
=> Discover Mismatched Versions of perf on Debian

src/TraceEvent/Computers/TraceManagedProcess.cs
The issue was we weren't counting all Server GC threads. The right way to aggregate is to look at threads with ThreadInfo of the form: 
1. .NET Server GC Thread ({ThreadNumber})
2. .NET Server GC
We were previously not accumulating the latter and as a result, our Heap Counts were wrong and not consistent with the Raw Data. 
In terms of testing, I made sure that GLAD wasn't effected by creating a console app that simply tested that the right heap count was obtained:
```csharp
using Microsoft.Diagnostics.Tracing.Etlx;
using Etlx = Microsoft.Diagnostics.Tracing.Etlx;
using Microsoft.Diagnostics.Tracing.Analysis;
using Microsoft.Diagnostics.Tracing.Analysis.GC;
using System.Diagnostics;
var TRACE_PATH = @"C:\\Traces\\GCTraces\\XAP_AATest\\GCCollectOnly_Better.etlx";
Etlx.TraceLog traceLog = …
```
=> Fix Heap Count in GCStats

src/Directory.Build.props
Consume the latest version of ClrMD, which fixes generation bounds reporting when using regions, which is enabled by default on .NET 7.
cc: @Maoni0, @cshung, @leculver
=> Fix Generation Aware Heap Snapshots When Using Regions

src/TraceEvent/Stacks/Linux/LinuxPerfScriptEventParser.cs, src/TraceEvent/Stacks/Linux/LinuxPerfScriptProcessNameBuilder.cs, src/TraceEvent/Stacks/Linux/LinuxPerfScriptStackSource.cs, src/TraceEvent/Stacks/Stacks.cs, src/TraceEvent/TraceEvent.Tests/LinuxStackSource/ProcessNameBuilderTests.cs
Existing behavior causes traces captured with perfcollect to show an incorrect list of processes.  Many of the process names are actually thread names, and so looking at usage for a single process requires a user to multi-select all of the rows whose PIDs match the one they want.
With this change, each row in the process selection dialog will represent one process.  We do our best to select the right process name.  If we can't, we'll show multiple of them with a semi-colon delimiter.
=> Linux: Merge Process Names

src/Directory.Build.props, src/HeapDumpDLL/HeapDumpDLL.csproj, src/MemoryGraph/MemoryGraph.csproj, src/Utilities/Utilities.csproj
Build the HeapDumpDLL project against the netstandard20 target framework.
Does not include the `GCHeapDumper` and associated code because some of its dependencies are not available in the netstandard20 set of APIs.
=> Build the HeapDumpDLL project for netstandard20

src/Directory.Build.props, src/EtwHeapDump/EtwHeapDump.csproj, src/HeapDump/HeapDump.csproj, src/HeapDumpDLL/HeapDumpDLL.csproj, src/PerfView/PerfView.csproj
This change introduces a new build mode so that we can easily build against a locally custom-built ClrMD. This can be very useful for diagnosing issues related to `HeapDump.exe`.
It does not change the default build, but we can change `MicrosoftDiagnosticsRuntimeVersion` in `Directory.Build.props` to local so that it will build against the local, custom-built ClrMD.
=> Make it easy to build PerfView with custom ClrMD

src/TraceEvent/Symbols/NativeSymbolModule.cs
- Add base type names for `char16_t`, `char32_t`, and `char8_t`
- Make `NativeSymbolModule.GetTypeName` handle case where the base type is not in its list of known names
This fixes an issue where unhandled base types would result in:
```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
at Microsoft.Diagnostics.Symbols.NativeSymbolModule.HeapAllocationTypeInfo.GetTypeName(IDiaSymbol symbol)
at Microsoft.Diagnostics.Symbols.NativeSymbolModule.<.ctor>b__14_0()
at System.Lazy`1.CreateValue()
at System.Lazy`1.LazyInitValue()
at System.Lazy`1.get_Value()
at Microsoft.Diagnostics.Symbols.NativeSymbolModule.GetTypeForHeapAllocationSite(UInt32 rva)
at PerfView.ETLPerfViewData.<>c__DisplayClass5_17.<OpenStackSourceImpl>g__GetAllocationType|49(CallStackIndex csi)
at …
```
=> Update base types in NativeSymbolModule

src/perfcollect/perfcollect
`-system` enables additional system-wide OS-level event capture.  Starting with major and minor faults.
=> Add -system capture capability to perfcollect

src/TraceEvent/TraceEvent.cs
I.e. GCHeapStats fails in CZ locale, because CH is actual letter.
=> User Ordinal Comparison for GC Event Detection

src/TraceEvent/Parsers/KernelTraceEventParser.cs
Due to this bug the TraceEvent fails to issue event calls on all Handle events (nothing registered)
So, this fixes it
=> Fixed handles events not firing issue

src/PerfView/EventViewer/EventWindow.xaml.cs
fixes #1759 
Now that the generated EventCounter payload text is properly JSON-quoted, needed to update the EventCounter graph-generating code to be aware of the added quotes
=> Properly quote EventCounter payload parsing for graphs

src/TraceEvent/Parsers/KernelTraceEventParser.cs
VirtualMem events currently attempt to fix-up the process associated with the event by pulling it from the payload.  This is incorrect, and results in incorrect behavior where it looks like a thread IDs are consistently re-used across processes, when in fact the thread was created only once.
Remove fix-up behavior from VirtualMem events to fix this behavior.
=> Remove Improper Fix-up from VirtualMem Events

src/PerfView/PerfViewData.cs
=> expose the .NET Framework Memory Analyzer to all users instead of internal MSFT only

src/PerfView/MainWindow.xaml, src/PerfView/MainWindow.xaml.cs
Adding a link to the standard Microsoft Privacy Policy within PerfView's help menu, which is standard Microsoft policy.
**PerfView does not collect any data from users.**
=> Add a Link to the Microsoft Privacy Policy

src/TraceEvent/TraceEvent.cs
This abstract class implements IDisposable and has a `protected virtual Dispose(bool disposing)` method, but it is missing a finalizer. Without the finalizer, dangling references will not have their native resources cleaned up.
In particular, an ETWTraceEventSource can leak native handles to open .etl files, thereby locking them on disk.
=> Add TraceEventSource finalizer

src/TraceEvent/Samples/00_AllSamples.cs, src/TraceEvent/Stacks/CallTree.cs, src/TraceEvent/Stacks/FilterStacks.cs, src/TraceEvent/Stacks/Histogram.cs, src/TraceEvent/Stacks/StackSourceWriterHelper.cs, src/TraceEvent/Stacks/Stacks.cs, src/TraceEvent/TraceEvent.cs, src/TraceEvent/TraceEventSession.cs, src/TraceEvent/TraceEventStacks.cs, src/TraceEvent/TraceLoggingEventId.cs, src/TraceEvent/Utilities/Cache.cs, src/TraceEvent/Utilities/StringBuilderCache.cs, src/TraceEvent/Utilities/command.cs, src/TraceEvent/ZippedETL.cs
(Hopefully) an easy PR for the team to review and merge. **No logic changes.**
Only 00_AllSamples.cs contains a fix inside code (a typo in a string).
Everything else is safe and just typos inside comments or XML documentation.
Happy Friday
=> Fix typos in TraceEvent library

src/PerfView/CommandLineArgs.cs, src/PerfView/CommandProcessor.cs, src/TraceEvent/Parsers/KernelTraceEventParser.cs, src/TraceEvent/TraceEventNativeMethods.cs, src/TraceEvent/TraceEventSession.cs
Add /LbrSources and /LbrFilters command line options. When the former is specified, last branch recording is enabled from the specified sources (comma-separated string of numeric source IDs or "PmcInterrupt"). /LbrFilters can optionally be specified to filter which branches are recorded (comma-separated list using same syntax as xperf).
No special parsing of these events yet, but this at least allows recording them.
=> Add support for last branch recording

src/TraceEvent/TraceLog.cs
We see intermittent test case failures in the CI Debug build due to a Debug.Assert failure.
The call-stack indicates the problem is with the JitTableCount check in Tracing.Etlx.TraceProcess.InsertJITTEDMethod.
Here's my analysis:
The check is guarded by a `_skipCount` counter. That counter is a static variable that counts down from 32 to zero.
If the `_skipCount` is zero at the top of the method, we compute a `preCount` based on the total JIT table size.
At the bottom of the method, when `_skipCount` is still zero we check that the new total table size has increased by one (`preCount + 1`).
My hypothesis is that when tests run concurrently, we can get multiple threads modifying the `_skipCount` variable. Since it's a shared (static) variable, this leads to the following race condition:
1. …
=> Fix random test case failures

src/PerfView/CommandLineArgs.cs, src/PerfView/CommandProcessor.cs, src/PerfView/PerfViewData.cs, src/PerfView/StateMachineFramework/UserCritComputer.cs
- Adds a new `/UserCritContention` command line argument to capture contention on the UserCrit.
- Adds a new `UI` view group with new views to display CPU and ThreadTime while the UserCrit is held.
=> Aggregate CPU and ThreadTime by UserCrit acquisition

src/perfcollect/perfcollect
- Switch `-f/-F` to `--fields` when calling `perf script`.
- Try calling `perf script` without requesting the `cpu` field when the first call fails.  `cpu` is not available in some containerized environments.
=> Increase Reliability of perf script Call in Perfcollect

src/perfcollect/perfcollect
Add a `setenv` command to perfcollect to allow users to setup a shell for profiling without having to know which environment variables need to be set.
=> Add perfcollect setenv

src/FastSerialization/FastSerialization.cs, src/FastSerialization/StreamReaderWriter.cs, src/TraceEvent/TraceLog.cs
I found a scenario where temporary files created during conversion to ETLX were being locked ("in use by another process") on disk. I think this happens when there's an exception during serialization (e.g. out of disk space).
Here are the changes:
1. Add a finalizer to MemoryStreamWriter. It's a based class that implements IDisposable with a `protected virtual void Dispose(bool disposing)` member. Without the finalizer, leaked instances will not get cleaned up. In particular, the derived `IOStreamStreamWriter` class won't close its stream which, in most cases is a `FileStream`.
2. Added a FileShare mode option to the `Serializer` constructor that takes a file path. This allows us to specify `FileShare.Delete` when we're doing conversion to ETLX. This means that the `File.Delete` on the …
=> Ensure .new files are cleaned up

src/TraceEvent/Parsers/KernelTraceEventParser.cs
TraceEvent does not expose these addresses symbolized anyway and the data can easily be too voluminous to handle with the existing mechanism.
=> Avoid logging code addresses for LBR event

src/PerfView/PerfView.csproj, src/TraceEvent/RegisteredTraceEventParser.cs, src/TraceEvent/TraceEvent.Tests/Parsing/DispatchTests.cs, src/TraceEvent/TraceEventNativeMethods.cs, src/TraceEvent/TraceEventSession.cs
Stop using ETWControl and ETWParsing from OSExtensions.dll. Replace them with implementations that use Microsoft-supported APIs.
- Use TraceSetInformation for configuring profile interval (no change from existing behavior other than using supported API).
- Use TraceSetInformation for configuring stack caching (same behavior, except that the new API is only supported on Windows 10 19582+).
- Use TdhEnumerateManifestProviderEvents for reading manifest data (works perfectly for manifests, but doesn't work for MOF).
Still using OSExtensions.dll for KernelTraceControl stuff, but that's supported by Microsoft. So perhaps the KernelTraceControl stuff could move into TraceEvent and then OSExtensions.dll would no longer be needed at all.
=> TraceEvent - don't use undocumented APIs

src/Directory.Build.props, src/PerfView/PerfView.csproj, src/TraceEvent/ETWKernelControl.cs, src/TraceEvent/Microsoft.Diagnostics.Tracing.TraceEvent.nuspec, src/TraceEvent/Symbols/SymbolReader.cs, src/TraceEvent/TraceEvent.csproj, src/TraceEvent/TraceEventSession.cs
- Move KernelTraceControl code directly into TraceEvent.
- Remove references to OSExtensions.dll
=> Remove OSExtensions.dll From PerfView and TraceEvent

src/PerfView.Tests/Utilities/PerfViewTestBase.cs, src/PerfView/App.cs, src/PerfView/CommandProcessor.cs, src/PerfView/Dialogs/UnhandledExceptionDialog.xaml.cs, src/PerfView/GcStats.cs, src/PerfView/GuiApp.cs, src/PerfView/MainWindow.xaml, src/PerfView/MainWindow.xaml.cs, src/PerfView/PerfViewData.cs, src/PerfView/UserCommands.cs
- Remove InternalUser checks that gate functionality.
- Remove old and unused internal feedback mechanism.
- Alphabetize the `Options` menu.
- Create a menu option for experimental GC features.
Note: There is no telemetry that PerfView or TraceEvent send back.  This is an old mechanism that hasn't been used for a long time.
=> Remove Internal-Only Code

.ado.yml
CodeQL currently runs on all jobs, which means that if the `PerfCollect` job wins, no code will be built, and no updates will be made to the CodeQL results for the repository.  Forcing the run to occur during `PerfView_Debug` ensures that PerfView and its dependencies get built during the CodeQL run.
=> Only Run CodeQL on PerfView_Debug Build Jobs

src/CSVReader/CSVReader.csproj, src/Directory.Build.props, src/EtwClrProfilerSigning/EtwClrProfilerSigning.csproj, src/EtwHeapDump/EtwHeapDump.csproj, src/FastSerialization/FastSerialization.csproj, src/HeapDump/HeapDump.csproj, src/HeapDumpDLL/HeapDumpDLL.csproj, src/MemoryGraph/MemoryGraph.csproj, src/PerfView.Tests/PerfView.Tests.csproj, src/PerfView/PerfView.csproj, src/PerfView/SymbolReaderHttpHandler.cs, src/TraceEvent/AutomatedAnalysis/DirectoryAnalyzerResolver.cs, src/TraceEvent/BPerf/BPerfEventSource.cs, src/TraceEvent/Compatibility.cs, src/TraceEvent/ETWTraceEventSource.cs, src/TraceEvent/Microsoft.Diagnostics.Tracing.TraceEvent.nuspec, src/TraceEvent/Microsoft.Diagnostics.Tracing.TraceEvent.props, src/TraceEvent/Stacks/RecursionGuard.cs, src/TraceEvent/Stacks/StackSourceWriterHelper.cs, src/TraceEvent/Symbols/SymbolReader.cs, src/TraceEvent/TraceEvent.Tests/TraceEvent.Tests.csproj, src/TraceEvent/TraceEvent.cs, src/TraceEvent/TraceEvent.csproj, src/TraceEvent/Utilities/command.cs, src/TraceEvent/ZippedETL.cs, src/TraceEventPackageSigning/TraceEventPackageSigning.csproj, src/TraceParserGen/TraceParserGen.csproj, src/Utilities/Utilities.csproj
This work is inspired by and builds off of #1808.  Thanks @kant2002!
- Standardizes libraries to build only for netstandard2.0.
- Attempts to rationalize dependency management between PerfView and TraceEvent and to depend to NuGet path properties instead of the manual construction of the path to the NuGet package.
- Removes unnecessary code for building TraceEvent against netstandard1.6 and net462.
- Includes a change to enable online certificate revocation checking in `SymbolReaderHttpHandler` which couldn't be implemented on all of the TFMs prior to this change.
=> TFM and Dependency Clean-Up

.ado.yml
Disambiguates the build of code in this repo vs. code that is only present in the internal repo.
=> Set Codeql.BuildIdentifier

src/PerfView/PerfView.csproj
Fixes #1828
MSBuild generates a number of binding redirects that end up loading many app-local versions of dependencies that are available in-box on .NET Framework.  This is unintentional, and furthermore, PerfView doesn't carry most of these dependencies, which means that they aren't present in the released version of PerfView.  This explains why recent executions of PerfView in the bin directory fail with a PlatformNotSupportedException when enabling online certificate revocation checks.  The app-local copy of System.Net.Http.dll is being loaded, which does not contain support for online certificate revocation checks.  The in-box copy of System.Net.Http.dll does contain this capability.
Remove these binding redirects by replacing the generated PerfView.exe.config file with one that only …
=> Overwite the generated PerfView.exe.config with a custom config file

src/TraceEvent/AutomatedAnalysis/DirectoryAnalyzerResolver.cs
Enable consumers of `DirectoryAnalyzerResolver` to override `OnAnalyzerLoaded`.
=> Unseal DirectoryAnalyzerResolver

src/TraceEvent/AutomatedAnalysis/StackView.cs
StackView currently loads all local NGEN symbols.  This is not necessary, and increases the cost of using `StackView`.  Instead, simply load each NGEN image's symbols if/when they are requested, which already happens when a search occurs.
=> Don't Aggressively Resolve NGEN Symbols in StackView

src/TraceEvent/AutomatedAnalysis/AutomatedAnalysisTraceLog.cs, src/TraceEvent/AutomatedAnalysis/Extensions.cs, src/TraceEvent/AutomatedAnalysis/ITrace.cs, src/TraceEvent/AutomatedAnalysis/ProcessContext.cs, src/TraceEvent/AutomatedAnalysis/StackView.cs
- Change `StackView.FindNodeByName` behavior to do exact name matches instead of `Regex` name matches.
- Add support to automated analysis and `AutomatedAnalysisTraceLog` for accessing blocked time stacks.
- Fix symbol resolution to account for the process being examined.
- Ensure that all images matching the requested name get resolved, rather than just the first in the trace file.
- Limit accessible methods on `StackView` to avoid cases where symbols don't get properly resolved.
- Add caching for symbol resolution in `StackView` to avoid calling into symbol resolution code more often than necessary.
=> Automated Analysis Improvements

src/TraceEvent/AutomatedAnalysis/AnalyzerIssue.cs, src/TraceEvent/TraceEvent.Tests/AutomatedAnalysis/AnalyzerExecutionTests.cs
So that the analyzers could decide to put a durable id onto any AnalyzerIssue instance.
=> [Auto-Analyzers] Add an issue id to AnalzyerResult

src/TraceEvent/Symbols/SymbolReader.cs, src/Utilities/FileUtilities.cs
If a .NET app is built on Windows, then deployed on Linux, the pdb path will have Windows path separators. On Unix, `Path.GetFileName` will not consider '\\' as a path separator and will fail to extract the file name.
The change adds a new utility method: `PathUtil.GetPlatformIndependentFileName` that, when running on non-Windows platforms, will check to see if the path contains any '\\' separators and return only the string after the last separator. `SymbolReader.FindSymbolFilePath` will use this new method to get the pdb file name.
=> Enable pdb file name extractions for Windows file names when running on Linux.

src/PerfView/App.cs
Diagsession files can contain a compressed PDBCache directory that contains PDBs associated with the contained ETL file.  If the PDBCache directory exists, add its uncompressed location to the SymbolPath.
=> Add Extracted PDBCache Directory for DiagSession Files to SymbolPath

src/PerfView/App.cs, src/PerfView/PerfViewData.cs
@pharring pointed out that there was already code in PerfView to merge the DiagSession's PDBCache into the local SymCache, such that the SymbolPath shouldn't need to point at the extracted PDBCache.  In looking at this further, the merge was failing because `Directory.Move` cannot move across volumes.  I have updated this code to enumerate the files and move them individually.
This PR also reverts #1846.
=> Fix PDBCache Merge From DiagSession to Local SymCache

src/PerfView/CommandProcessor.cs
Allow minimal rundown to collect the following events:
- Microsoft-Windows-DotNETRuntimeRundown/TieredCompilationRundown/SettingsDCStart
- Microsoft-Windows-DotNETRuntimeRundown/GC/SettingsRundown
Both of these events are emitted once per process and provide useful configuration information for the runtime.
Fixes #1831.
cc: @Maoni0, @brandonh-msft
=> Add Additional Configuration Events to Minimal Rundown

src/PerfView/StackViewer/StackWindow.xaml.cs, src/TraceEvent/Stacks/FilterStacks.cs
https://github.com/microsoft/perfview/issues/783
- Record last used Filter in field
- Account for start/end time switching 0 based precision (e.g. 0 -> 0.000 are string != but double ==)
No automated tests created, only manual tests executed
=> Don't refresh UI if filter combo boxes are unchanged

src/PerfView/CommandProcessor.cs, src/PerfView/DotNetVersionLogger.cs
The `DotNetVersionLogger` was inadvertently enabling all keywords `(0)` which resulted in very verbose traces.  This is especially true for processes that start during tracing, which will then enable logging of all allocations.
=> Don't Enable All CLR Keywords in DotNetVersionLogger 

src/PerfView/StackViewer/StackWindow.xaml.cs, src/TraceEvent/Stacks/FilterStacks.cs
This reverts commit 56d152818ac155c647ce0acdfbc751611665a3b2.
Reverting this commit because it breaks symbol resolution.  When symbols are resolved, the UI does not refresh because nothing in the filter has changed.  I looked briefly at what it would take to fix this, but it was not immediately obvious to me.  I'm happy to re-consider a PR with this functionality that fixes symbol resolution.  We should also see if there are other operations that require a refresh.
cc: kkostrzewa
=> Revert "Don't refresh UI if filter combo boxes are unchanged"

src/TraceEvent/TraceEventSession.cs
While working with a `TraceEventSession` session, I pressed F12 on the `EnableKernelProvider()` method to see what exactly it did.  The documentation that was displayed to me above the decompiled method was a bunch of sentences without periods that had been mushed together into a giant paragraph that didn't make a lot of sense.  Inspection of the source code here revealed that the closing `</summary>` tag accidentally got placed after the parameter documentation (instead of before it).
This change fixes the malformed XML documentation, and fixes a couple other spots in the file as well while we're at it.
=> Fix malformed XML documentation in TraceEventSession.cs

src/TraceEvent/Stacks/Linux/LinuxPerfScriptEventParser.cs, src/TraceEvent/Stacks/Linux/LinuxPerfScriptStackSource.cs, src/TraceEvent/Stacks/Linux/LinuxPerfScriptThreadStateComputer.cs
- Handle cases where the process name contains spaces.
- Handle cases where the process name shows up as ":<number>".
- Handle cases where the trace is captured in a container and the process ID / thread ID don't match what is present in the `sched:*` event payload.  This happens because the kernel doesn't update the PID / TID based on the process namespace.
=> Fix Bugs in Linux Perf Script Traces

src/PerfView/SupportFiles/HtmlReportUsersGuide.htm, src/TraceEvent/Parsers/ClrTraceEventParser.cs
.Net 8 introduces new instrumented tiers into Tiered Compilation. Add event parsing support for these.
Update the HTML guide section on Tiered Compilation, and add some information about OSR and PGO.
=> Add new instrumented tiers, update html guide for tiering and pgo

src/PerfView/CommandLineArgs.cs, src/PerfView/CommandProcessor.cs, src/PerfView/DotNetVersionLogger.cs, src/TraceEvent/TraceEventSession.cs
1. Allow users to specify `/RundownMaxMB` to limit the size of the rundown ETL file.
2. Update the `DotNetVersionLogger` to enable a non-existent keyword.  This ensures that unrequested rundown events aren't enabled.
3. Update `TraceEventSession.GetActiveSessionNames` to allocate on the heap instead of on the stack to ensure that failures don't occur on machines with a large number of sessions.
4. Add the `DotNetVersionLogger` session to the list of sessions covered by the `abort` command.
=> Improve Rundown and Abort Paths

src/PerfView/StackViewer/StackWindow.xaml, src/PerfView/StackViewer/StackWindow.xaml.cs
I have a scenario where I am attempting to optimize the exlusive cost of a set of methods, and viewing exlusive costs in the source view has been quite helpful.
=> Change source view to include both the inclusive samples data as well as the exclusive samples data

src/perfcollect/perfcollect
The explicit check is to support scenario when somebody installed LTTng from non-package (i.e. compiling from sources).
That in turn is used in perf lab to use LTTng from 2.12 branch to ensure compatibility (at the moment) with runtime.
=> Check whether LTTng is installed and if so, don't attempt to install it.

src/TraceEvent/TraceEventSession.cs
While looking over a peer's PR that added ETL providers, I wanted to read more information about the TraceEventSession class.
This PR fixes a few grammatical errors and provides additional clarity to the TraceEventSession class summary.
Please feel free to take this fix or not.
=> nit: Update the TraceEventSession class summary.

src/CSVReader/EventSource.cs, src/PerfView/EtwEventSource.cs, src/PerfView/EventViewer/EventWindow.xaml
1) increasing the columns displayed in the Events view to 10 before resolving to Rest.for someone who uses the Events view heavily only displaying 4 columns before resolving to Rest seems like a unnecessary limitation (was this because this was written at a time when we had very small monitors? 😄). 
2) displaying the Events view window maximized by default because most likely you will want to do that
3) changed the Rest column to fit the window instead of leaving a huge amount of space which means if you select that column you will mostly see just empty space and just lost most of your valuable columns on the left hand side -
=> 3 UI changes to the Events view

.ado.yml
Temporarily pin version of VSTest to 17.6.3 till we figure out why TRX is not produced on newer versions.
=> Use previous stable release of VSTest

src/TraceEvent/TraceEventSession.cs
Avoid dereferencing a null pointer if `providersDesc` is `null`.
This code has not changed recently - it appears that something has changed underneath this call.  That said, we can definitely harden this path and do better.
=> Harden TraceEventSession.ProviderNameToGuid

src/PerfView/GcStats.cs
The numerator and denominator for the Alloc MB / Total Pause Time calculation was reversed. This PR fixes this.
CC: @Maoni0
=> Fixed calculation of Alloc MB / Pause Time in GC

src/TraceEvent/Microsoft.Diagnostics.Tracing.TraceEvent.nuspec
TraceEvent depends on Microsoft.Win32.Registry but does not specify the dependency in the nuspec file.  .NET Core shared framework applications are unaffected because Microsoft.Win32.Registry is part of the shared framework, however self-contained and .NET Framework applications are affected.  Many users don't see this issue because Microsoft.Win32.Registry is often on the machine.  This change will guarantee that Microsoft.Win32.Registry is present.
=> Explicitly Reference Microsoft.Win32.Registry as a NuGet Dependency

src/PerfView/CommandProcessor.cs
Fixes #1913
`/DumpHeap` only works with GUI collections.  This change emits a warning when `/DumpHeap` is used with `/NoGui` telling the user to re-capture with a GUI collection.
=> Fix indefinite wait when using /HeapDump and /NoGui

.ado.yml, src/PerfView/MainWindow.xaml.cs
PerfView tests are running in process because they are .NET Framework tests, and the WPF code is exiting process with 0, which makes the test runner think all tests passed, but in reality only a small portion of tests run.
Make the tests run in a sub-process, where we can detect that it exited before it should, even when it exits with 0. I am also enabling blame so it shows you which test most likely crashed the process. This adds a little bit of overhead, feel free to remove that if you don't need it. It will still crash, but with less info.
=> Enable running in isolation and --blame

src/Directory.Build.props, src/PerfView/PerfView.csproj, src/TraceEvent/Microsoft.Diagnostics.Tracing.TraceEvent.nuspec, src/TraceEvent/Microsoft.Diagnostics.Tracing.TraceEvent.props, src/TraceEvent/TraceEvent.csproj
Fixes #1659.
Replaces msdia140.dll with a new version that fixes CVE-2018-25032.  Removes dependencies that the new version of msdia140.dll doesn't require.
=> New version for Microsoft.Diagnostics.Tracing.TraceEvent.SupportFiles.

src/LinuxEvent.Tests/LinuxTracing.Tests.csproj
Same element is on L11 (L10 now).
=> Remove duplicated AutoGenerateBindingRedirects.

src/Directory.Build.props, src/PerfView/PerfView.csproj
Update Azure.Identity to version 1.10.2 to address CVE-2023-36414.
Other package updates are due to transitive dependency changes stemming from the update of Azure.Identity.
=> Update Azure.Identity to version 1.10.2 to address CVE-2023-36414

src/TraceEvent/Computers/TraceManagedProcess.cs, src/TraceEvent/Computers/TraceProcess.cs
By correctly getting the Etlx.TraceLog, we have the information necessary to discern whether the process has SVR GC threads. This is important as in DATAS, we start off with 1 heap and then change the heap count and the previous logic was failing to get us the BGC based GlobalHeapHistory event as it is fired after GC/Stop. 
We appropriately set process.Log to point to the pertinent Etlx.TraceLog (if available) by ensuring that the TraceProcess allows an Etlx.TraceLog in its constructor rather than the Analysis.TraceLog; the initial concern was that we'll be coupling the Etlx.TraceLog to the Analysis but this has already been done by setting the type of process.Log to Etlx.TraceLog vs. Analysis.TraceLog.
The order of events for BGC based GlobalHeapHistory events were:
-> GC/Start
-> …
=> Properly setting the process.Log to be used by the GC to discern whether the process is running with SVR GC Threads.

src/PerfView/Dialogs/RunCommandDialog.xaml.cs
Once set, the "Focus process" option cannot be reset because `PopulateCommandLineArgs` never sets `FocusProcess` to null.
This is a very simple fix without unit tests. I can add tests for `RunCommandDialog` if needed, but it requires to slightly change the constructor to allow skipping the elevation.
=> Reset FocusProcess when checkbox is unselected

src/PerfView/PerfViewData.cs
Show the ObjectSize field of GCAllocationTick events in the Any Stacks view when available.
cc: @davidfowl
=> Show Object Size in for GCAllocationTick Events in Any Stacks

src/TraceEvent/ETWTraceEventSource.cs, src/TraceEvent/TraceEvent.cs, src/TraceEvent/TraceEventNativeMethods.cs
- Add LogfileHeader.[TimerResolution](https://learn.microsoft.com/en-us/windows/win32/api/evntrace/ns-evntrace-trace_logfile_header)
- Add UserTime and KernelTime fields for [ProcessorTime](https://learn.microsoft.com/en-us/windows/win32/api/evntcons/ns-evntcons-event_header)
=> Add properties for accessing processor time & 

src/PerfView/Dialogs/MemoryDataDialog.xaml.cs, src/PerfView/PerfViewData.cs
- Recognize .hdmp and .mdmp files as process dumps.  Change the .gcdump file suffix to include the source suffix (e.g. .hdmp.gcdump) to avoid inadvertent overwrites of files with the same name but different suffix.
- Trim surrounding quotes from the target .gcdump path to avoid failures in platform APIs that do not expect them.
cc: @leculver
=> Fixes for Process Dump to GC Dump Conversion

.ado.yml
Trigger the CI to run weekly at midnight UTC.  This ensures that we maintain fresh component governance data to be used to detect security vulnerabilities.
=> Weekly CI Trigger

src/perfcollect/perfcollect
Based on discussion from #1953.
The `nolttng` switch comes handy here and should be a good path.
=> Explicit install of LTTng UST on Ubuntu 22 or higher.

src/TraceEvent/ETWTraceEventSource.cs
Inspired by #1928 and #1929.
By default, TaskID is not looked up from the event stream for each event, and is instead pulled from event metadata or hardcoded in the parser. This change allows users to ask `ETWTraceEventSource` to lookup the TaskID from the event stream (present in the header) for each event.  This enables tools that vary the TaskID for a given event ID to function properly.
=> Opt-in Support for TaskID Lookup Directly From the Event Stream

src/TraceEvent/TraceLog.cs
`RelatedActivityID` is stored in a `GrowableArray` as part of the `TraceLog`. When the event is pushed in to the `realTimeQueue` in order to dispatch it, the event is cloned.  Cloning creates a new instance of `TraceEvent`, and allocates buffers that are owned by the new clone.  When the event is dispatched, we are missing an assignment of `myBuffer`, which contains the `RelatedActivityID`. Assign `myBuffer` prior to dispatch so that the `RelatedActivityID` is correct.
=> Fix Surfacing of RelatedActivityID in Real-Time Session Dispatch

src/EtwHeapDump/DotNetHeapDumpGraphReader.cs, src/EtwHeapDump/EtwHeapDump.csproj, src/HeapDump/GCHeapDumper.cs, src/HeapDump/HeapDump.csproj, src/HeapDumpCommon/GCHeapDumpNames.cs, src/HeapDumpDLL/HeapDumpDLL.csproj, src/PerfView/PerfView.csproj, src/TraceEvent/TraceEvent.Tests/Memory/ClrMD_Dependencies.cs, src/TraceEvent/TraceEvent.Tests/TraceEvent.Tests.csproj
The goal of this change is to ensure that we don't unexpectedly change root names.
- Detect if the set of roots changes via a test.
- Add code comments to document these changes via release notes.
=> Maintain stable root names for heap snapshots

src/perfcollect/tests/containers/mariner-2.0.dockerfile
Remove the pinned commit hash for Mariner Docker image since we aren't going to get automatic notifications of updates.
We were previously getting updates, but they were "internal" updates and needed to be ported to GitHub.
=> Remove Pinned Commit Hash for Mariner Docker Image

.ado.yml, .pipelines/perfcollect-job.yml, .pipelines/perfview-job.yml
This is required for some internal changes around how we run Azure Pipelines.  The goal is to make sure that however we run the CI in the open is also how we run it internally.  This change refactors the CI into multiple yaml files so that they can be consumed by multiple pipelines.
Scheduled runs are also removed because they can be scheduled internally, which is where they are needed.
=> Refactor Azure Pipelines To Allow for Re-Use

src/PerfView/EventViewer/EventWindow.xaml.cs, src/PerfView/MainWindow.xaml, src/PerfView/MainWindow.xaml.cs
Implement the option to allow a user to toggle whether or not the entire contents of a raw event are dumped to the log from the Events view. The original behavior was and the default still is to truncate the middle portion of the event unless the user disables the option.
=> Add option to toggle raw event data truncation

src/TraceEvent/Microsoft.Diagnostics.Tracing.TraceEvent.nuspec, src/TraceEvent/TraceEvent.csproj
This includes the following work:
1. Add the missing System.Collections.Immutable explicit dependency.
2. Update the TraceEvent nuspec file to include all dependencies.
Fixes #1989.
=> Update TraceEvent Dependencies

src/perfcollect/perfcollect
Enable users capturing larger traces or traces of larger workloads to specify a buffer size to perf_events.
Adds `-buffersize` argument that takes a value of the following format:
- A number of pages.
- A number of bytes, kilobytes, megabytes, or gigabytes by using the suffix B, K, M, or G accordingly.
Example usages include:
- `-buffersize 20`: 20 pages
- `-buffersize 100M`: 100 megabytes
Note: `perf` will convert the value to a number of pages, and then round up to the nearest power of 2.  Thus, we shouldn't see a smaller buffer size, but we may see a larger size than requested.
=> Add -buffersize to perfcollect

src/PerfView/CommandProcessor.cs
Without this change, a very simple mistake such as an extra space in the comma-separated list of providers will silently cause the provider to not be enabled.  This is a very easy mistake to make if the list of providers you want to enable is large and you are copying and pasting the list from somewhere else and it gets word wrapped, etc.
=> Trim whitespace when parsing additional providers

src/Directory.Build.props
- Update to version 3.1.9.
- Switch to using a single MSBuild variable instead of updating each one individually.
=> Increment Versions and Simplify Future Updates

src/TraceEvent/Stacks/ChromiumStackSourceWriter.cs
I converted a .nettrace file to the chromium format via `dotnet-trace convert` and noticed that my 15s long trace was only displayed as being 15ms long. After some digging and consulting the documentation, it appears that a timestamp expressed in milliseconds is being written into the `ts` field that expects a microsecond timestamp.
This bug has been previously reported here https://github.com/dotnet/diagnostics/issues/1315#issuecomment-653632216 but incorrectly classified as a bug in chromium. I believe this confusion might have been due to setting
```csharp
writer.Write("\"displayTimeUnit\": \"ms\", ");
```
just a few lines below but alas this is only a display concern
=> Chromium Timestamp is in microseconds

src/PerfView/GcStats.cs, src/TraceEvent/Computers/TraceManagedProcess.cs
Trivial fix.
The presence of per heap history events is detected by comparing PerHeapHistories with `null`, but this property is never `null`, since the list is allocated in the constructor. 
https://github.com/microsoft/perfview/blob/dec5b67a215a446863285169d4be09b4f91180d1/src/TraceEvent/Computers/TraceManagedProcess.cs#L2507
As a result, even though we can fallback to allocation ticks, we never fallback and if the history events are missing, the allocation rate is unavailable or incorrect. 
We can check for `Count == 0` instead and then fallback works.
=> Fix detection of PerHeapHistories events presence

src/Directory.Build.props, src/TraceEvent/Microsoft.Diagnostics.Tracing.TraceEvent.nuspec, src/TraceEvent/TraceEvent.csproj
This dependency was added when adding support for `netstandard1.6` and appears to no longer be necessary.
Fixes #2016.
=> Remove dependency on Microsoft.NETCore.Portable.Compatibility

src/PerfView/PerfViewData.cs
This PR adds the _ASP.NET Core Stats_ view to the "Advanced" folder (placement was based on where the current IIS Stats and ASP.NET Stats views are located, but can definitely be changed). At the moment it relies on the presence of **Microsoft.AspNetCore.Hosting** events, such as _Request/Start_ and _Request/Stop_. 
This view is added for both regular ETL files, as well as EventPipe files - it's only built/generated in one place so it looks the same from either type of dataset.
While right now it only consumes those Hosting events, the goal for future output is to be able to consume Microsoft.Extensions.Logging events as well to supplement output, or even base the calculations on those events instead of Hosting (say, when Hosting events aren't available but ILogger events are). Another …
=> Add ASP.NET Core Stats view

src/PerfView/GcStats.cs, src/TraceEvent/Computers/TraceManagedProcess.cs
In .NET 6, @Maoni0 introduced the `GCGlobalHeapHistory_V4` in https://github.com/dotnet/runtime/pull/55888 that expose some timing information for each phase of the GC and I did the parsing of it in https://github.com/microsoft/perfview/pull/1758. It turns out just parsing it is not enough, we need to expose it as property on `TraceGC` in order to be consumed, so this PR expose that array.
Unfortunately, the compact time can often be wrong because a bug I fixed in https://github.com/dotnet/runtime/pull/100599, practically that means for some traces, the compact time will be wrong (often seen as 0)
=> Expose times array

src/PerfView/CommandProcessor.cs
When converting from MB to bytes, it is possible to overflow MaxSizeMB because it gets converted from MB to bytes.  Cast `maxSizeMB` to `long` to avoid this.
=> Address Overflow of /MaxSizeMB

src/PerfView/CommandLineArgs.cs
The Microsoft-Windows-DotNetRuntimeRundown provider was added as part of CLR 4.0.  In order to handle rundown for CLR 2.0, we must enable the Microsoft-Windows-DotNetRuntime provider, which in CLR 2.0, contains the rundown events.  Unfortunately, this creates a situation where we're also turning on some potentially verbose non-rundown events for CLR 4.0 processes.  This results in unintentionally larger traces, and rundowns that take much longer than expected.
Given that CLR 2.0 is not nearly as common as it once was, we will disable rundown for CLR 2.0 by default.  Users that want to profile CLR 2.0 processes can do so by setting `/NoV2Rundown:false` during collection.
=> Disable V2 Rundown by Default

src/Directory.Build.props, src/TraceEvent/Microsoft.Diagnostics.Tracing.TraceEvent.nuspec, src/TraceEvent/TraceEvent.Tests/TraceEvent.Tests.csproj, src/TraceEvent/TraceEvent.csproj
Fixes #2032.
These package references are no longer necessary since TraceEvent now targets `netstandard2.0`.
=> Remove Unnecessary PackageReferences

src/TraceEvent/Computers/StartStopLatencyComputer.cs
This change will use the time difference between the Contention/Start and Contention/Stop event unless the process is running on a newer version of .NET Core that specifies the time difference in the Contention/Stop event.  This is the ensure that this view works for all .NET processes and not just newer .NET Core processes.
=> Fix the Contention Stacks View for .NET Framework and Older .NET Core Processes

src/Directory.Build.props, src/PerfView/Authentication.cs, src/PerfView/PerfView.csproj, src/PerfView/SymbolReaderHttpHandler.cs, src/TraceEvent/Symbols/SymbolPath.cs, src/TraceEvent/Symbols/SymbolReader.cs
- Add support for authentication to Symweb.
- Add missing dependencies that previously broke existing ADO authentication and are also needed for Symweb.
- Increase timeout for downloads.
- Tell `HttpClient.GetAsync` to return immediately after the response headers have been downloaded.  This allows `SymbolReader` to show download progress and not timeout for larger symbol files.
=> Add Support for Symweb Authentication to PerfView

.pipelines/mirror.yml
This is necessary to remove errors that appear in internal systems due to the fact that the mirror pipeline does not build any code.
=> Disable CodeQL Scanning for Code-Mirror Jobs

.pipelines/perfview-job.yml
Fix this by adjusting the path to contents to be captured.
=> Artifacts are not currently captured properly in CI jobs

src/Directory.Build.props, src/HeapDump/GCHeapDumper.cs, src/HeapDump/Program.cs
- Enable ClrMD to authenticate to a symbol server if required.
- Update ClrMD API calls.
=> Update to ClrMD version 4.0.0-beta.24314.3

src/PerfView/PerfView.csproj, src/TraceEvent/Symbols/NativeSymbolModule.cs
Remove support for downloading source code from source depot.  This support is no longer needed, and will allow us to remove sd.exe from the PerfView binary.
=> Remove Source Depot Support

src/NuGetPackageSigning/NuGetPackageSigning.csproj
These build artifacts are empty and unused.
=> Remove NuGetPackageSigning.dll and NuGetPackageSigning.pdb

src/perfcollect/perfcollect
Make sure that the pid exists before running the `perf` command.
=> Validate the input value of -pid

src/perfcollect/perfcollect
`perfcollect` no longer requires:
- `crossgen` R2R support: This is not required as of .NET 5, which supports `perf_events` jitdump integration.
- native symbol archiving in the final trace.zip file: Native symbols are consumed at collection time during `perf script`.
=> Remove Unnecessary Code from perfcollect

src/EtwHeapDump/EtwHeapDump.csproj, src/HeapDump/HeapDump.csproj, src/HeapDumpDLL/HeapDumpDLL.csproj, src/SymbolsAuth/SymbolsAuth.csproj, src/TraceEvent/TraceEvent.Tests/TraceEvent.Tests.csproj
Address additional projects that transitively pull in vulnerable versions of System.Text.Json.
=> Address CVE-2024-30105 by directly consuming System.Text.Json 8.0.4

src/PerfView/GcStats.cs, src/TraceEvent/Computers/TraceManagedProcess.cs, src/TraceEvent/Parsers/GCDynamicTraceEventParser.cs, src/TraceEvent/TraceEvent.cs
This PR is ready to be reviewed. (It is easier to review by commits)
The idea of truly dynamic event is to make `GCDynamicEvent` truly dynamic, in the sense that the GC team can modify the runtime to emit any dynamic event, and then we can consume them in a reasonable API without modifying `TraceEvent` at all.
The primary use case for this is through a .NET Interactive notebook, where: 
1. The notebook user specifies a list of `DynamicEventSchema` that specify the names of the events the schemas handle as well as the field and types, and then
2. Be able to access them through the `TraceGC.DynamicEvent()` extension method as if they were parsed, using the C# dynamic keyword magic.
Beside the obvious advantage to reduce work, it also allow a more agile practice. Previously, whenever we …
=> Truly Dynamic Event

src/TraceEvent/Stacks/Linux/LinuxPerfScriptProcessNameBuilder.cs
Required to support ParallelLinuxPerfScriptStackSource.
Address unlocked access to `Dictionary` objects in `LinuxPerfScriptProcessNameBuilder` that can occur when called from `ParallelLinuxPerfScriptStackSource`, which splits the processing work across multiple threads.
=> Support Concurrent Access to LinuxPerfScriptProcessNameBuilder

src/PerfView/App.cs
When attempting to use a locally-detected symbol file, prompt the user with the following text:
"Found <path to pdb> on your local machine.  Do you want to use it?"
=> Update Symbol File Check Text for PerfView

src/PerfView/cgmanifest.json, src/TraceEvent/cgmanifest.json
The `cgmanifest.json` files will surface otherwise undetectable dependencies in component governance in the Microsoft-internal Azure DevOps instance.
=> Add cgmanifest.json Files to Track Dependencies from SupportFiles Packages

.pipelines/mirror.yml
The mirror is currently failing due to rename detection.  The mirror should not be handling renames.
=> Address Mirror Merge Conflicts

src/EtwClrProfiler/ETWClrProfilerX64.vcxproj, src/EtwClrProfiler/ETWClrProfilerX86.vcxproj
Mitigate possible side-channel attacks by compiling with `/QSpectre`.
=> Compile ETWClrProfiler with /QSpectre

src/PerfView.TestUtilities/ThrowingTraceListener.cs
Per guidance, `Exception(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context)` is now obsolete and should not be extended by application code.
=> Remove Obsolete Exception Constructor

src/PerfView/App.cs, src/PerfView/Utilities/SupportFiles.cs
Add the `/buildLayout <path>` command to PerfView.
This allows users to build a self-contained fully-extracted version of PerfView that doesn't depend on `%appdata%.  This is useful for certain deployment mechanisms where the deployed PerfView shouldn't impact PerfView in `%appdata%.
=> PerfView BuildLayout Command

src/PerfView/Utilities/SupportFiles.cs
This can occur on machines that haven't ever run PerfView before.
=> Don't Fail /buildLayout if SupportFilesDirBase Doesn't Exist

.vsconfig, README.md
With the recent change to ensure that the C++ libraries are built with spectre mitigations enabled, it requires you to install an additional component to the VS installation to build the project which wasn't mentioned in the building instructions. This PR updates the building instructions to mention this, and also makes it a bit easier to read. I also used this as an opportunity to add a .vsconfig file which will get VS to prompt you if it notices any required components are missing:
=> Update building docs + add a .vsconfig file

src/TraceEvent/TraceEvent.Tests/inputs/netcore.3.1.x64.twocontainers.baseline.txt, src/TraceEvent/TraceLog.cs
`GetFileNameWithoutExtensionNoIllegalChars` would always trim the "extension" regardless of whether or not the extension was truly an extension. This led to instances such as https://github.com/dotnet/runtime/issues/107315 where a `TraceModuleFile` with a `FilePath` of "System.Private.CoreLib" (due to reasons where no physical file on disk backed the image, so a fallback value of the module name was used), would end up with a `TraceModuleFile.Name` of "System.Private", when it should still be "System.Private.CoreLib".
=> [TraceEvent] Restrict extension truncating to known exts

src/TraceEvent/EventPipe/EventPipeEventSource.cs
Reference: https://github.com/dotnet/runtime/issues/105132
=> Fix memory leak when TraceEvent modifies the _eventRecord->ExtendedData field

src/TraceEvent/TraceEventNativeMethods.cs, src/TraceEvent/TraceEventSession.cs
This changes adds support for two additional EVENT_TRACE flags, EVENT_TRACE_PRIVATE_LOGGER_MODE and EVENT_TRACE_PRIVATE_LOGGER_MODE.
These flags are not compatible with real time logging, but can be used with file mode based logging which is useful for applications which are trying to capture locally the events that their process is generating for later diagnosis.
=> Add support for EVENT_TRACE_PRIVATE_LOGGER_MODE and EVENT_TRACE_PRIVATE_IN_PROC flags for file mode logging

src/Directory.Build.props, src/FastSerialization/FastSerialization.csproj, src/SymbolsAuth/SymbolsAuth.csproj
Prior to this change, SourceLink attempted to point to the internal repo where we build the Microsoft distribution of PerfView and TraceEvent.
With this change, sources will be embedded in the PDBs so that all users can debug and profile shipped releases.
=> Configure SourceLink to Embed Source Files in PDBs

src/Directory.Build.props, src/PerfView/App.cs, src/PerfView/Dialogs/FileInputAndOutput.xaml, src/PerfView/Dialogs/MemoryDataDialog.xaml, src/PerfView/Dialogs/RunCommandDialog.xaml, src/PerfView/Dialogs/RunCommandDialog.xaml.cs, src/PerfView/Dialogs/SymbolPathDialog.xaml, src/PerfView/Dialogs/UserCommandDialog.xaml, src/PerfView/EventViewer/EventWindow.xaml, src/PerfView/EventViewer/EventWindow.xaml.cs, src/PerfView/Extensibility.cs, src/PerfView/GuiUtilities/StatusBar/StatusBar.xaml, src/PerfView/GuiUtilities/TextEditor/TextEditorControl.xaml, src/PerfView/GuiUtilities/TextEditor/TextEditorWindow.xaml, src/PerfView/GuiUtilities/WebBrowser/WebBrowser.xaml, src/PerfView/GuiUtilities/WebBrowser/WebBrowser.xaml.cs, src/PerfView/HeapView/GcInfoView.cs, src/PerfView/MainWindow.xaml, src/PerfView/MainWindow.xaml.cs, src/PerfView/PerfView.csproj, src/PerfView/PerfViewData.cs, src/PerfView/StackViewer/PerfDataGrid.xaml, src/PerfView/StackViewer/StackWindow.xaml, src/PerfView/StackViewer/StackWindow.xaml.cs, src/PerfView/SupportFiles/UsersGuide.htm, src/PerfView/Themes/DarkTheme.xaml, src/PerfView/Utilities/ProcessTree.cs, src/PerfView/app.config, src/PerfViewExtensions/GlobalSrc/Commands.cs
An accessibility review was completed on PerfView which identified a number of accessibility issues with PerfView, this PR addresses as many of the Sev 1 and Sev 2 accessibility issues that were possible without too much work. There are some other issues which were not addressed in this PR because they would require a significant amount of work to fix or it needed some more investigation.
The ActiveX-based WebBrowser control has been replaced with WebView2 controls. A large number of accessibility issues that were identified were in places we were using the WebBrowser as it wasn't generating a very accessible UI. WebView2 was a (mostly) drop-in replacement that was able to address every accessibility issue that was reported. The WebView2 package includes inside it the driver/dll, so it is …
=> Address accessibility issues

src/HeapDump/HeapDump.csproj
New versions of Visual Studio fail to build `HeapDump.csproj` with the following error: 
```
"D:\a\1\s\src\HeapDump\HeapDump.csproj" (Build target) (5:3) ->
(ResolvePackageAssets target) -> 
C:\hostedtoolcache\windows\dotnet\sdk\8.0.403\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error NETSDK1047: Assets file 'D:\a\1\s\src\HeapDump\obj\project.assets.json' doesn't have a target for 'net462/win-x64'. Ensure that restore has run and that you have included 'net462' in the TargetFrameworks for your project. You may also need to include 'win-x64' in your project's RuntimeIdentifiers. [D:\a\1\s\src\HeapDump\HeapDump.csproj::TargetFramework=net462]
```
If we replace `win7-x64` with `win-x64`, then the CI fails with a similar error because `win7-x64` can't …
=> Add win-x64 RID to HeapDump.csproj

src/FastSerialization/FastSerialization.cs, src/FastSerialization/MemoryMappedFileStreamReader.cs, src/FastSerialization/SegmentedMemoryStreamReader.cs, src/FastSerialization/SegmentedMemoryStreamWriter.cs, src/FastSerialization/StreamReaderWriter.cs, src/HeapDump/GCHeapDump.cs, src/HeapDump/GCHeapDumper.cs, src/HeapDump/HeapDump.csproj, src/MemoryGraph/MemoryGraph.cs, src/MemoryGraph/graph.cs, src/TraceEvent/EventPipe/EventPipeEventSource.cs, src/TraceEvent/TraceEvent.Tests/Parsing/EventPipeParsing.cs, src/TraceEvent/TraceEvent.Tests/Serialization/FastSerializerTests.cs, src/TraceEvent/TraceLog.cs
Implements a set of breaking changes for `FastSerialization`.
Highlights:
- `SerializationSettings` are now required when creating a stream for use with `FastSerialization`.
- All non-primitive types must be registered with `Deserializer` before they can be deserialized.  Failure to do so will cause the deserialization operation to fail.
More Details:
- Rename `SerializationConfiguration` to `SerializationSettings` and make it a required parameter when creating a stream for use with `FastSerialization`.
- Make `SerializationSettings` read-only once passed into a reader or writer implementation by cloning the object whenever a setting is changed.
- Move `StreamReaderAlignment` from an optional parameter to reader constructors to a property on `SerializationSettings`.
- All non-primitive …
=> Breaking Changes for FastSerialization

.github/CODEOWNERS
Add a CODEOWNERS file so that GitHub can be configured to request code reviews from owners.
=> Add CODEOWNERS File

src/perfcollect/perfcollect
WHY:
Azure Linux and Mariner are the same image with different branding however the `DISTRIB_ID` on Azure Linux 3.0 onwards is changed from "mariner" to "azurelinux"
FIX:
Include checking for "azurelinux" when setting the Ismariner flag.
Bug/Fix discovered with @faluciano
Fixes https://github.com/microsoft/perfview/issues/2134
=> FIX: perfcollect install script Azure Linux 3

src/PerfView/GcStats.cs
Updated the following in the Raw XML View in GCStats:
1. Added the `MarkShortWeak` entry to the GlobalHeapHistory node that was missing.
2.  Added the `MarkSizedRef`, `MarkOverflow`, `MarkDependentHandles`, `MarkNewFQ`, `MarkSteal` and `MarkBGCRoots` entries to the PerHeapHistory node.
=> Added missing time info fields in the Raw XML View in GCStats

src/TraceEvent/Computers/StartStopActivityComputer.cs
The OpenTelemetry SDK event source is emitting request start/stop information, but the format differs from what TraceEvent expects for start/stop operations. This mismatch prevents proper recognition of activities in the CallTree view.
This change introduces an exception to accommodate the OpenTelemetry SDK’s event format, ensuring that start/stop activities are correctly recognized and displayed in the CallTree view.
**Details:**  
For reference, see the implementation in the OpenTelemetry SDK:  
[OpenTelemetrySdkEventSource.cs](https://github.com/ualehosaini/opentelemetry-dotnet/blob/1e89b39d72236285081c727956439af6715ab782/src/OpenTelemetry/Internal/OpenTelemetrySdkEventSource.cs)
**Before the change:**
**After the change:**
Tagging @brianrob for awareness.
=> Update start stop activity computer to support OpenTelemetry-Sdk EventSource

src/TraceEvent/ETWReloggerTraceEventSource.cs
When using relogger to writes an event that did not exist previously into the data stream, the context data and timestamp is given explicitly.  The newEvent.SetTimeStamp expects a QPC time based on UTC time.
=> Set the timestamp as a QPC value based on UTC time

src/PerfView/PerfViewData.cs
Fixes #2141. The changes to address accessiblity issues (#2120) caused the command handler in `PerfViewRuntimeLoaderStats` to not be called. I have verified that these changes resolve the issue.
=> Fix RuntimeLoader commands not being handled

src/TraceEvent/Computers/TraceManagedProcess.cs, src/TraceEvent/Parsers/ClrTraceEventParser.cs
Fixes https://github.com/microsoft/perfview/issues/2024. CC: @Maoni0
=> Added fixes for a number of POH issues

.github/workflows/stale.yml
Use `actions/stale` to perform the following actions twice daily:
- Mark issues that haven't been touched for 1 year as stale.
- Close issues that have been marked stale for 30 days without an update.
=> Implement Stale Issue Handling

src/TraceEvent/Computers/TraceManagedProcess.cs
This PR fixes cases where we are accessing GenData for cases where certain generations e.g., POH don't exist.
CC: @Maoni0 
Tested:
1. On a trace with no POH allocations.
2. On a trace with POH allocations.
3. On a trace from .NET Framework.
=> Fix IndexOutOfRangeException when we iterate over all the Generations and try to access GenData

src/TraceEvent/TraceLog.cs
Allows consumers of realtime session to configure providers for rundown, same way they do for actual session.
=> feat: allow setting rundown providers for realtime EventPipe Tracelog

src/CSVReader/CsvReader.cs, src/CSVReader/EventSource.cs, src/PerfView/EtwEventSource.cs, src/PerfView/EventViewer/EventWindow.xaml, src/PerfView/EventViewer/EventWindow.xaml.cs
This will add a multi line viewer to the Event Viewer, which can be turned on and off with F2.
Issue #2158
=> Add multi line viewer for Event Window

src/PerfView/Dialogs/FileInputAndOutput.xaml, src/PerfView/Dialogs/ManagePresetsDialog.xaml, src/PerfView/Dialogs/MemoryDataDialog.xaml, src/PerfView/Dialogs/RunCommandDialog.xaml, src/PerfView/Dialogs/RunCommandDialog.xaml.cs, src/PerfView/Dialogs/SelectProcess.xaml, src/PerfView/EventViewer/EventWindow.xaml, src/PerfView/GuiUtilities/HistoryComboBox/HistoryComboBox.cs, src/PerfView/HeapView/GcInfoView.cs, src/PerfView/HeapView/HeapAllocView.cs, src/PerfView/HeapView/HeapDiagram.cs, src/PerfView/HeapView/IssueView.cs, src/PerfView/HeapView/ThreadView.cs, src/PerfView/HeapView/Toolbox.cs, src/PerfView/MainWindow.xaml, src/PerfView/ObjectViewer/TreeViewGrid.xaml, src/PerfView/StackViewer/FlameGraphDrawingCanvas.cs, src/PerfView/StackViewer/PerfDataGrid.xaml, src/PerfView/StackViewer/StackWindow.xaml, src/PerfView/Themes/LightTheme.xaml
This PR resolves some more accessibility bugs with PerfView. 
There were some major changes to the flame graph:
- Fixed a bug where only two of the 100 randomly generated flame graph colors were used, now we have our random colors again
- Updated the color generator to ensure that all colors have sufficient contrast with the text and background
- Added a border around flame boxes to allow for light coloured flame boxes (e.g. yellow) to have sufficient contrast against the background
- Fixed some bugs regarding rendering at different zoom levels. We now re-render every time the zoom level is updated. This might need some additional testing on some large traces to ensure it can handle it, but it seemed to handle fine on my machine with some test traces I made.
- Allowed keyboard focus on …
=> Further accessibility fixes

src/Directory.Build.props, src/TraceEvent/EventPipe/EventPipeEventSource.cs, src/TraceEvent/TraceEvent.Tests/Parsing/EventPipeParsing.cs
- Prepare for the release of 3.1.20.
- Disable nettrace V6 support as it is not yet complete, and we don't want to release it incomplete.
=> Increment Versions and Disable Nettrace V6 Support

src/TraceEvent/EventPipe/EventCache.cs, src/TraceEvent/EventPipe/EventPipeEventSource.cs, src/TraceEvent/EventPipe/EventPipeMetadata.cs, src/TraceEvent/EventPipe/EventPipeTraceEventParser.cs, src/TraceEvent/EventPipe/FixedBuffer.cs, src/TraceEvent/EventPipe/LabelListCache.cs, src/TraceEvent/EventPipe/RewindableStream.cs, src/TraceEvent/EventPipe/SpanReader.cs, src/TraceEvent/EventPipe/StackCache.cs, src/TraceEvent/EventPipe/ThreadCache.cs, src/TraceEvent/TraceEvent.Tests/Parsing/EventPipeParsing.cs, src/TraceEvent/TraceEvent.Tests/Platform/EventPipeTestBase.cs, src/TraceEvent/TraceEvent.csproj
- Re-enabling support for parsing format V6 and re-enabling the tests
- Removed support for ancient netperf format version 1 and 2 that were only used during .NET Core 2.0 (not even 2.1).
- The implementation of the Nettrace reader was doing a bunch of pinning because the TraceEvent internal model of events uses unmanaged pointers, however the pinning was creating bad GC performance. TraceEvent builds for .NET standard so we don't have guaranteed access to the pinned heap and I didn't want to start doing lots of copying and/or managing pools of pinned arrays. Instead I switched the stream reading over to using spans backed by native heap allocations and explicit block lifetime tracking. As a side benefit it also brings the V3-5 block iteration code a bit closer to the V6 block iteration …
=> Change NetTrace format version support, eliminate pinning, and improve UnsupportedVersionException

src/PerfView/CommandLineArgs.cs, src/PerfView/CommandProcessor.cs
The OS heap provider technically supports circular buffering, but it's very sensitive to lost events (dropped or overwritten). So, it doesn't make sense to use circular buffering to limit its size. This PR adds a new flag to set a max file size on the heap session, which enforces the size even if PerfView is killed before the session is stopped.
I tested the flag on my machine by killing PerfView in the middle of a collection and confirming that the heap file stopped at the specified max size.
=> Add /OSHeapMaxMB to set a max size for OS heap sessions

src/MemoryGraph/graph.cs, src/PerfView/PerfViewData.cs, src/TraceEvent/EventPipe/EventPipeEventSource.cs, src/TraceEvent/EventPipe/UniversalProviders.md, src/TraceEvent/Parsers/UniversalEventsTraceEventParser.cs, src/TraceEvent/Parsers/UniversalSystemTraceEventParser.cs, src/TraceEvent/SourceConverters/NettraceUniversalConverter.cs, src/TraceEvent/TraceEvent.cs, src/TraceEvent/TraceLog.cs
Adds support for consuming nettrace files that contain usage of the universal providers.  These are:
1. UniversalSystem - Provides a view of the state of the system (processes, mappings, symbols, etc.)
2. UniversalEvents - Provides sampled based events (e.g. CPU, CSwitch)
cc: @beaubelgrave, @noahfalk, @mdh1418
=> Implement Nettrace Support for Traces with Universal Providers

src/TraceEvent/EventPipe/EventPipeMetadata.cs, src/TraceEvent/TraceEvent.Tests/Parsing/EventPipeParsing.cs
The work to add V6 NetTrace parsing regressed the special name handling for names that end with "Start" or "Stop". Prior to this fix the suffix was correctly removed when the opcode in the trace was 0, but it was not removed if the opcode reported in the file was Start or Stop.
The fixed code removes the "Start" and "Stop" suffixes when the opcode is either 0 or when it is already set to start/stop respectively. An old V4 nettrace produced by the runtime would have opcode = 0 whereas a newer V5 nettrace from the runtime would have the opcode set.
Ideally the runtime would be doing this event name transform on its own and the parser would not be in the business of making these changes but for backwards compat we must.
@wiktork - this PR looks like it should fix the issue you were hitting …
=> Fix NetTrace parsing for Start/Stop event names

.pipelines/perfview-job.yml
Enable amd64 MSBuild, in multiproc mode, and include the NuGet restore in a single step.
(this time with a name that shouldn't anger GitHub: https://github.com/microsoft/perfview/pull/2191#issuecomment-2859426506).
=> More efficient build in PRs

.ado.yml
Per https://learn.microsoft.com/azure/devops/pipelines/tasks/reference/publish-build-artifacts-v1 this is recommended and faster.
(#2192 from a "clean" branch name)
=> Switch to pipeline artifacts

src/PerfView/Dialogs/SelectProcess.xaml, src/PerfView/HeapView/Toolbox.cs, src/PerfView/IProcess.cs
When selecting one or more processes to display in a stack viewer, the `Duration` field is sorted as a text string instead of a duration.
Fixes sorting by using a floating point value representing total seconds and telling WPF to sort by that value instead of the text value.
cc: @bwadswor
=> Implement Duration Column Sorting

src/PerfView/Dialogs/MemoryDataDialog.xaml, src/PerfView/Dialogs/RunCommandDialog.xaml, src/PerfView/Dialogs/SelectProcess.xaml
After the last round of accessibility bug fixes, only one bug was sent back as unresolved, so this should fix that last accessibility bug. Essentially, the hyperlinks inside the help ribbons were not navigable by the keyboard using tab navigation. It seems that this is a bug with RichTextBox or FlowDocument as I was not able to get it to work, so I just converted it to a TextBlock and added a border to match the previous styling.
Comparing the help ribbons before and after the change, the styling is identical.
=> Fix tab navigation to hyperlinks inside help ribbons

.github/workflows/copilot-setup-setups.yml
Restore all Linux-buildable projects during copilot agent jobs.  This allows copilot to build these projects and react to any build breaks without human intervention.
=> Make Copilot More Effective

src/TraceEvent/TraceEventSession.cs
Then TraceEventSession.ProviderNameToGuid is called code assumes this never results in null. See TraceEventProviders.GetProviderGuidByName. Then TraceEventNativeMethods.TdhEnumerateProviders results return a hr != 0 or providersDesc == null then Trace.WriteLine will be called and the function returns null. This pull request changes the behavior to return an incomplete list instead of crashing with a NRE. A point can me made to change the Trace.WriteLine to a throw new Exception(.
=> NRE when calling TraceEventProviders.GetProviderGuidByName

src/PerfView/Computers/RealtimeAntimalwareComputer.cs
- Address `NullReferenceException` when there is a missing process event.
- Show all scans even when the filter driver events aren't present.  This is especially useful when looking at traces generated by New-MpPerformanceRecording.  These events will show up with an "Unknown" reason and won't have a stack, since these are both generated by the filter driver events.
=> Address NullReferenceException in Anti-Malware Realtime Scans View

src/EtwHeapDump/DotNetHeapDumpGraphReader.cs, src/HeapDump/GCHeapDumper.cs
With this, PerfView will be able to create native AOT gcdumps. It activates the same codepaths we had for Project N, so it will also properly decode type names.
The changes to DotNetHeapDumpGraphReader match https://github.com/dotnet/diagnostics/pull/5506.
=> Add support for native AOT gcdumps

src/HeapDump/Program.cs, src/PerfView/Authentication.cs, src/SymbolsAuth/Samples/1_InteractivePopupAuth.cs
Provide a more deterministic set of chained credentials:
1. Visual Studio credentials (if present)
2. Prompt the user.
NOTE: This only affects interactive uses of PerfView.  Users of TraceEvent's symbol authentication functionality have always been required to provide a `TokenCredential` directly.
=> Remove uses of DefaultAzureCredential

src/TraceEvent/Symbols/NativeSymbolModule.cs, src/TraceEvent/Symbols/PortableSymbolModule.cs, src/TraceEvent/TraceEventSession.cs, src/TraceParserGen/Program.cs
Suppressions must have an explanation in order to be effective.
=> Add Explanations for CodeQL Suppressions

src/PerfView/MainWindow.xaml
Without this the menu and filter are white on white in dark mode.
Before:
After:
=> Use themed background brush for menu and filter

src/TraceEvent/EventPipe/EventCache.cs, src/TraceEvent/EventPipe/EventPipeEventSource.cs, src/TraceEvent/EventPipe/EventPipeMetadata.cs, src/TraceEvent/EventPipe/LabelListCache.cs, src/TraceEvent/EventPipe/NetTraceFormat.md, src/TraceEvent/TraceEvent.Tests/Parsing/EventPipeParsing.cs
This adds two new features to NetTrace V6 format:
- The LabelList now has explicit encodings for OpCode, Level, Keywords, and Version. These labels can be used to override the values stored in metadata allowing the fields to vary on a per-event basis. It also provides writers more flexibility on how to store the data regardless whether the values are varying. Using metadata is still expected to be the more the compact encoding in most scenarios but writers may need to weigh other implementation concerns beyond file size.
- The SequencePointBlock now supports a flag to flush all metadata entries. This eliminates the final place in the format where writers were forced to maintain a cache of potentially unbounded size to write an unbounded number of events. If the writer's metadata cache …
=> NetTrace LabelList metadata overrides and metadata flushing

src/TraceEvent/ETWTraceEventSource.cs
If an ETL file is malformed, it's possible to end up with a null handle in `ETWTraceEventSource.handles`.  Ensure that we only dispose of non-null handles.
=> Only Dispose Non-Null Handles in ETWTraceEventSource

src/TraceEvent/EventPipe/NetTraceFormat_v5.md
The spec didn't accurately describe the encoding of field definitions inside the V2 Params area of NetTrace V5 metadata. I am updating the doc to align it with what the CLR generates and what TraceEvent parses.
Reference source for the parser:
https://github.com/microsoft/perfview/blob/0691921c6cc22eacaff2b41efa5b4d38ef1ffd20/src/TraceEvent/EventPipe/EventPipeMetadata.cs#L397-L404
=> Revise V2 field definitions in NetTraceFormat_v5.md
