microsoft/perfview

src/TraceEvent/Computers/TraceManagedProcess.cs, src/TraceEvent/Parsers/ClrPrivateTraceEventParser.cs
@swgillespie @adityamandaleeka @vancem this is mostly for processing the revisited pages so we can use it in our perf analysis
=> Added BGC events handling

src/PerfView/CommandProcessor.cs, src/PerfView/Dialogs/MemoryDataDialog.xaml.cs, src/PerfView/GcStats.cs, src/PerfView/HeapView/HeapView.cs, src/PerfView/JitStats.cs, src/PerfView/OtherSources/WTStackSource.cs, src/PerfView/PerfViewData.cs, src/PerfView/Triggers.cs, src/PerfView/Utilities/ProcessTree.cs, src/PerfView/memory/GCHeapSimulator.cs, src/PerfView/memory/JavaScriptHeapDumper.cs, src/PerfView/memory/PdbScopeMemoryGraph.cs, src/PerfViewExtensions/GlobalSrc/Commands.cs, src/TraceEvent/Symbols/SymbolReader.cs, src/Zip/CustomStreams.cs
Fixed simple mistakes and warnings
=> Simple mistakes and warnings

CONTRIBUTING.md
Fix a few small typos and consistency issues in CONTRIBUTING.md
=> Fix small typos and consistency issues in CONTRIBUTING.md

src/TraceEvent/TraceEventSession.cs
Added the missing ALPC event guids and types in SetStackTraceIds
=> Added missing ALPC stack trace settings

src/PerfView/StackViewer/StackWindow.xaml.cs
=> Preserve column sort order after symbol lookup

src/PerfView/StackViewer/PerfDataGrid.xaml.cs
=> Sort columns in descending order when they are first clicked

src/TraceEvent/TraceUtilities/HistoryDictionary.cs
HistoryDictionary keeps its values in a sorted linked list.  This can get long and sow if there are many entires.
We normally only access them sequentially, however so we can speed up access by remembering
the last entry we used and start from there if we can.
=> Speed up HistoryDictionary

src/PerfView/Dialogs/RunCommandDialog.xaml, src/PerfView/Dialogs/RunCommandDialog.xaml.cs
Thus, the most recently run commands will be available for
easy re-use.
=> Change CommandToRun from a text box to a history text box

src/PerfView/GuiUtilities/TextEditor/TextEditorWindow.xaml
This makes issue #213 less severe in a trivial way 
@BruceForstall
=> Make text editor windows bigger by default.

src/HeapDump/CrossGenerationLiveness/CrossGenerationLivenessCollector.cs, src/HeapDump/GCHeapDumper.cs, src/HeapDump/Program.cs, src/PerfView/App.cs, src/PerfView/CommandProcessor.cs, src/PerfView/Utilities/SupportFiles.cs, src/TraceEvent/NativeDlls.cs, src/TraceEvent/Symbols/SymbolReader.cs
:memo: I'm going to make a few notes in the diff with questions on this one.
=> Simplify handling of processor architecture

src/TraceEvent/Computers/TraceManagedProcess.cs
This change adds a local cache from `TraceProcess` to `TraceLoadedDotNetRuntime`, resulting in a dramatic reduction in the time it takes to open the **GCStats** window for large traces.
:memo: It wasn't clear exactly how you prefer items like this to be implemented. However, the performance difference from this change is somewhere between 3:1 and 10:1 (saving dozens of seconds to minutes), so I'm particularly interested in finding a good way to get it included.
=> Improve the performance of opening the GCStats window

src/PerfView/PerfViewEventSource.cs
trivial change to avoid some build warnings.
=> Assign some variables to suppress warning.

src/PerfView/PerfViewData.cs
=> Remove has process events

src/LinuxEvent.Tests/App.config, src/LinuxEvent.Tests/LinuxTracing.Tests.csproj, src/LinuxEvent.Tests/packages.config, src/PerfView.Tests/PerfView.Tests.csproj, src/PerfView.Tests/packages.config, src/TraceEvent/Ctf/CtfTracing.Tests/CtfTracing.Tests.csproj, src/TraceEvent/Ctf/CtfTracing.Tests/packages.config, src/TraceEvent/TraceEvent.Tests/TraceEvent.Tests.csproj, src/TraceEvent/TraceEvent.Tests/packages.config
Update test projects to reference the same versions of the .NET Framework and xunit.
* .NET Framework 4.6
* xunit 2.2.0
=> Consolidate xunit

PerfView.sln, src/LinuxEvent.Tests/LinuxTracing.Tests.csproj, src/PerfView.TestUtilities/PerfView.TestUtilities.csproj, src/PerfView.TestUtilities/Properties/AssemblyInfo.cs, src/PerfView.TestUtilities/UseCultureAttribute.cs, src/PerfView.TestUtilities/WorkItemAttribute.cs, src/PerfView.TestUtilities/packages.config, src/PerfView.Tests/PerfView.Tests.csproj, src/PerfView.Tests/StackViewer/StackWindowTests.cs, src/TraceEvent/Ctf/CtfTracing.Tests/CtfTracing.Tests.csproj, src/TraceEvent/TraceEvent.Tests/TraceEvent.Tests.csproj
* Create a utilities library **PerfView.TestUtilities**
* Move `WorkItemAttribute` and `UseCultureAttribute` to the new utilities library so it can be used in any test
=> Test utilities

src/TraceEvent/Symbols/SymbolReader.cs, src/TraceEvent/TraceLog.cs
=> Support new SHA-256 source file hash type in DIA

src/TraceEvent/DynamicTraceEventParser.cs, src/TraceEvent/TraceLog.cs
The change is to fix #322. 
@vancem @pharring
=> Missing containsSelfDescribingMetadata in serialization

src/TraceEvent/Computers/TraceManagedProcess.cs, src/TraceEvent/Parsers/ClrTraceEventParser.cs
+ added support for full GCs triggered during provisional mode
+ fixed a bug in LOH alloc calculation
=> support for GCs under new condition and bug fix

src/PerfView/PerfView.csproj
=> Avoid multiple items with the same Link metadata

src/TraceEvent/Parsers/IisTraceEventParser.cs
=> Add Keywords for the new IIS provider.

src/PerfView/App.cs, src/PerfView/CommandProcessor.cs, src/PerfView/Extensibility.cs, src/PerfView/GcStats.cs, src/PerfView/UserCommands.cs, src/PerfView/Utilities/SupportFiles.cs, src/PerfViewCollect/PerfViewCollect.csproj
Enables two user commands for PerfViewCollect:
LinuxGCStats
LinuxJITStats
These user commands generate HTML reports for GC and JIT stats respectively.
=> Enable UserCommands on Linux in PerfViewCollect

src/PerfView/memory/MemoryGraphStackSource.cs, src/TraceEvent/Stacks/CallTree.cs, src/TraceEvent/Stacks/FilterStacks.cs, src/TraceEvent/Stacks/RecursionGuard.cs
Fixes #348 
Likely fixes #161, but I did not test this
=> Improve support for deeply-nested stacks

src/PerfView/PerfViewData.cs
When opening a DiagSession, there could be multiple ETL files. If there are multiple files, attempt to merge them into a single file for analysis using the NONE option. This approach is valid since the auxillary events normally injected during a merge by KTC are instead insert into a aux ETL file in DiagSession scenarios (i.e. Visual Studio).
=> Support dynamic merge for DiagSession ETL files

src/PerfView/CommandLineArgs.cs, src/PerfView/CommandProcessor.cs, src/PerfView/Dialogs/RunCommandDialog.xaml, src/PerfView/Dialogs/RunCommandDialog.xaml.cs, src/TraceEvent/Parsers/TplTraceEventParser.cs
:memo: Please make sure to not rebase or squash this change during the merge process.
=> Add a check box for TPL events

src/TraceEvent/TraceEvent.Tests/DispatchTests.cs
=> Avoid using Assert.DoesNotContain due to performance problems

src/FastSerialization/GrowableArray.cs, src/MemoryGraph/MemoryGraph.cs, src/MemoryGraph/graph.cs
📝 Please make sure to not rebase or squash this change during the merge process.
=> Improve debugging experience by omitting children from Node.ToString()

src/PerfView/GuiUtilities/TextEditor/TextEditorControl.xaml.cs
=> Set filename from "save as" dialog

src/TraceEvent/Microsoft.Diagnostics.Tracing.TraceEvent.nuspec, src/TraceEvent/Symbols/SymbolReader.cs, src/TraceEvent/TraceEvent.cs
Fix assert, fix spelling, add more diagnostics.
=> Three Minor fixes

src/TraceEvent/TraceLog.cs
=> Add using statement to mange TraceLog disposal

src/TraceEvent/Microsoft.Diagnostics.Tracing.TraceEvent.nuspec
Follow up to https://github.com/Microsoft/perfview/pull/455
Fix a comment
=> Change comment to reflect the actual framework used

.editorconfig
=> Added EditorConfig file to enforce spacing.

src/Directory.Build.props, src/PerfView/CommandLineArgs.cs, src/PerfView/CommandProcessor.cs, src/PerfView/GuiApp.cs, src/PerfView/PerfViewData.cs, src/PerfView/SupportFiles/UsersGuide.htm, src/TraceEvent/ZippedETL.cs
Added the /LowPriority qualifer so that merging/ngening/zipping is done at low CPU priority.
=> Low priority

Nuget.config, README.md, src/PerfView/PerfView.csproj, src/TraceEvent/TraceEvent.csproj
There may be more, but this much is pretty much for sure.
=> Changes to get signing working

src/PerfView/StackViewer/CallTreeView.cs, src/PerfView/StackViewer/StackWindow.xaml, src/PerfView/StackViewer/StackWindow.xaml.cs
=> Add Shift-Space shortcut to colapse nodes in tree view.

src/PerfView/PerfViewData.cs
In this pull request, these are the issues fixed
- Parsed the Request CorrelationId which is used to accurately launch the Activity Start Stop Time View for slow requests.
- Added logic for the IIS's GENERAL_CHILD_REQUEST_START events which was causing us to incorrectly identify the slowest modules in the IIS request processing pipeline
- Add logic for more IIS related ETW events
- Parsing the ASP.NET Module for Pipeline Module events
Here is a screenshot of how the Stack Traces view looks like now. The option to launch Activity View is provided if the request has switched threads and the option to launch Threads View is provided to launch thread time view for synchronous requests.
=> Updating IIS Stats View to show Activity and Thread time view both

src/TraceEvent/TraceEvent.cs
Jeff checked in AddDispatch but after the review I wanted the API to easily support 'wrapping' (e.g. lock) scenarios.
(That is the hook is called which can set somethign up, call the original dispatch, and then tear it down).
I talked with Jeff, and I he is OK with this change.
=> Change AddDispatch Hook to allow wrapping hooks

src/TraceEvent/TraceEvent.cs
This is by itself mostly to test the CI system.
=> Add a debugging method to dump arrays of bytes.

src/TraceEvent/TraceEventStacks.cs
This only happened when you had a large number of ETW CPU samples that had no stack associated with them (this is pretty rare, but can happen if you set CPU samples to simply not log stacks).
TraceEvent does not discard CPU samples with no stacks but rather creates a one element broken stack (somethign is better than nothing).   Unfortunately it has a
limit on how many of these it can make (it has to decide a maximum before knowing
how many it needs, so it guesses).
WHat it should have done is give up when this maxium was reachced, but instead it returned the first stack it ever encountered (thus many samples could be attributed
to this one stack.    Fixed this.
=> Fix issue where some traces had CPU samples attributed to the wrong thread

src/TraceEvent/TraceEvent.Tests/EventPipeParsing.cs
After recent @vancem rewrite of the consumer part of Event Pipe the #461 bug is gone
I added the test to make sure that it never comes back.
Vance what is the difference of using `EventPipeEventSource` directly (like it was before) vs `var traceLog = new TraceLog(TraceLog.CreateFromEventPipeDataFile(eventPipeFilePath))` ? Whis is this the recomended usage?
=> add test to prove that old bug is gone, fixes #461

PerfView.sln, src/TraceEvent/Samples/00_AllSamples.cs, src/TraceEvent/Samples/10_SimpleEventSourceMonitor.cs, src/TraceEvent/Samples/11_SimpleEventSourceFile.cs, src/TraceEvent/Samples/12_SimpleOSEventMonitor.cs, src/TraceEvent/Samples/20_ObserveGCEvent.cs, src/TraceEvent/Samples/21_ObserveJitEvents.cs, src/TraceEvent/Samples/22_ObserveEventSource.cs, src/TraceEvent/Samples/30_MonitorLoads.cs, src/TraceEvent/Samples/31_KernelAndClrMonitor.cs, src/TraceEvent/Samples/32_KernelAndClrFile.cs, src/TraceEvent/Samples/33_KernelAndClrMonitorWin7.cs, src/TraceEvent/Samples/34_KernelAndClrFileWin7.cs, src/TraceEvent/Samples/40_SimpleTraceLog.cs, src/TraceEvent/Samples/41_TraceLogMonitor.cs, src/TraceEvent/Samples/50_SimpleFileRelogger.cs, src/TraceEvent/Samples/51_SimpleMonitorRelogger.cs, src/TraceEvent/Samples/MainProgram/Program.cs, src/TraceEvent/Samples/ReadMe.txt, src/TraceEvent/Samples/SupportFiles/EventProducer.cs, src/TraceEvent/Samples/TraceEventSamples.csproj, src/TraceEvent/Samples/app.config, src/TraceEvent/Samples/packages.config, src/TraceEvent/TraceEvent.csproj
Still need to figure out exactly how to publicize these samples, but this at least gets these artifacts into the code base so they don't get lost.
=> Added TraceEventSamples to code base.

src/TraceEvent/Stacks/CallTree.cs
:memo: Please use the merge strategy instead of rebase or squash if/which this commit is merged.
=> Fix a stack overflow in TransferInclusiveSamplesToList

src/PerfView/MainWindow.xaml.cs
=> Make rename rename all unmerged files.

README.md, documentation/Downloading.md, src/Directory.Build.props, src/HeapDump/GCHeapDump.cs, src/HeapDump/GCHeapDumper.cs, src/HeapDump/HeapDump.csproj, src/PerfView/App.cs, src/PerfView/PerfView.csproj, src/TraceEvent/RegisteredTraceEventParser.cs, src/TraceEvent/Symbols/SymbolPath.cs, src/Utilities/EnvironmentUtilities.cs
Also added some docs
Fixed a manifest generation bug that cause TraceParserGen to fail.
=> Cleanup unused ifdefs

src/TraceEvent/ETWReloggerTraceEventSource.cs, src/TraceEvent/ETWTraceEventSource.cs, src/TraceEvent/TraceLog.cs
This fixes issue #478 
Basically it implements GetOSPointerSize() in a way that works around bugs see $478 for more
It also removes some unused ifdefs.
=> Pointer size fix

src/FastSerialization/_README.cs, src/TraceEvent/Computers/ActivityComputer.cs, src/TraceEvent/Computers/StartStopActivityComputer.cs, src/TraceEvent/Computers/ThreadTimeComputer.cs, src/TraceEvent/Parsers/ClrTraceEventParser.cs, src/TraceEvent/Symbols/SymbolPath.cs, src/TraceEvent/ZippedETL.cs
Migrate some easy fixes from Service Profiler to PerfView for TraceEvent library.
=> Migrate ServiceProfiler changes - baseline

src/TraceEvent/Computers/SampleProfilerThreadTimeComputer.cs, src/TraceEvent/Computers/StartStopActivityComputer.cs, src/TraceEvent/Computers/ThreadTimeComputer.cs, src/TraceEvent/Symbols/NativeSymbolModule.cs, src/TraceEvent/Symbols/SymbolReader.cs
Mainly add switches to allow callers to turn on/off some experimental features.
=> Migrate serviceprofiler changes 2

README.md
=> Update "how to build" instructions in main README.md

src/PerfView/StackViewer/StackWindow.xaml.cs
The was a bug where you could not select a time range by selecting cells if the TreeView (you could in ByName)
The titles used in the 'diff' menu, could be stale (if you updateed the view)
=> Two small GUI fixes

src/TraceParserGen/TraceParserGen.cs
Some manifest files use keywords as task names, i.e. "new", "object", etc.  Create a dictionary of some keywords, and change the name to title case if found.
=> Strip c# keywords from manifest task names

src/PerfView/MainWindow.xaml.cs, src/TraceEvent/TraceEvent.cs
Added logic when you delete a file in the GUI to also delete any unmerged companion files as well (we fixed rename to do something similar a few months ago.  
Also add ProcessorNumber to the output when an event is dumped.
=> Delete all unmerged files in the GUI Delete command

src/PerfView/Dialogs/ManagePresetsDialog.xaml.cs
Small bugfix of preset renaming to complement main preset feature #446 .
=> Fixed preset renaming bug

src/PerfView/OtherSources/Linux/LinuxPerfScriptEventParser.cs
=> Fix default on Linux Reads

src/PerfView/Dialogs/ManagePresetsDialog.xaml, src/PerfView/Dialogs/ManagePresetsDialog.xaml.cs, src/PerfView/StackViewer/Preset.cs, src/PerfView/StackViewer/StackWindow.xaml.cs, src/PerfView/SupportFiles/UsersGuide.htm
Also fixed some UI issues.
Should resolve #656
=> Removed Inc/Exc patterns from preset, replaced with comment

src/TraceEventPackageSigning/TraceEventPackageSigning.csproj
After several attempts, this was finally succesful with the TraceEventPackageSigning project.
This is sub-optimial, see https://github.com/Microsoft/perfview/issues/673 for more details.
=> Successfully added nuget package signing.

src/PerfView/PerfViewData.cs, src/TraceEvent/TraceEvent.cs, src/TraceEvent/TraceLog.cs
Removed unused method
Normalized indentation
Added Processor number to Machine Counter Events in AnyStacks view.
Be robust to empty string names.
=> Small Updates

src/TraceEvent/TraceLog.cs
- Fix bug with native symbol resolution where symbols would not resolve
if the RSDS event came after the module load event
=> Fix bug with native symbol resolution

documentation/MakingSupportFilesNugetPackages.md, src/HeapDump/Debugger/DumpDebugging/pipeline.cs, src/PerfView/SupportFiles/UsersGuide.htm
Also fixed some other doc typos.
=> Add details about making SupportFiles Nuget packages

src/Directory.Build.props, src/PerfView/PerfViewData.cs, src/PerfView/StackViewer/StackWindow.xaml.cs, src/PerfView/SupportFiles/UsersGuide.htm, src/TraceEvent/Symbols/SymbolReader.cs, src/TraceEvent/TraceLog.cs
Bug fixes for source lookup of traces collected on Linux.
Make thread names a bit prettier if we don't have CPU information
Doc improvement for pinning views.
=> Support .netperf.zip files, small fixes.

src/PerfView/PerfViewData.cs
Fix initialization of hasDotNetHeapDumps = true from #732.
=> Fix hasDotNetHeapDumps Initialization

src/Directory.Build.props, src/EtwClrProfiler/CorProfilerTracer.cpp, src/EtwHeapDump/DotNetHeapDumpGraphReader.cs, src/PerfView/SupportFiles/UsersGuide.htm, src/TraceEvent/EventPipe/EventPipeEventSource.cs, src/TraceEvent/EventPipe/EventPipeTraceEventParser.cs, src/TraceEvent/Parsers/KernelTraceEventParser.cs, src/TraceEvent/Stacks/RecursionGuard.cs, src/TraceEvent/TraceEventStacks.cs, src/TraceEvent/TraceLog.cs, src/TraceEvent/Utilities/Cache.cs, src/Utilities/FileUtilities.cs
Changed calls stack sampling to 997 from 97 (better default)
Spelling in comments.
Checked in change to limit recursion to 8K (was unlimited, but that can lead to hangs).
Catch and swallow exceptions in ForceDelete.
=> Misc fixes

src/Directory.Build.props, src/NugetSupportFiles/Microsoft.Diagnostics.Tracing.TraceEvent.SupportFiles.Populate.bat, src/NugetSupportFiles/Microsoft.Diagnostics.Tracing.TraceEvent.SupportFiles/Microsoft.Diagnostics.Tracing.TraceEvent.SupportFiles.nuspec, src/NugetSupportFiles/PerfView.SupportFiles.Populate.bat
to fix a problem with collecting CPU perf counte events in real time sessions
=> Update OSExtentions 

src/PerfView/SupportFiles/UsersGuide.htm
One instance of ASP.NET was written as ASP.NEt
=> Small change in UsersGuide.htm

src/Directory.Build.props, src/TraceEvent/ETWReloggerTraceEventSource.cs, src/TraceEvent/Parsers/KernelTraceEventParser.cs, src/TraceEvent/TraceEvent.csproj, src/TraceParserGen/ETWManifest.cs, src/related/EventRegister/eventRegister.csproj
minor cleanup items.   Just getting them out of the way.
=> Minor tweeks.

src/TraceEvent/Computers/TraceManagedProcess.cs
- Provide the generation in GCStart event (instead of always 0)
- don't forget to count the suspension time between the start of BGC gen 2 and inner gen 0/1
=> Fixes in TraceLoadedDotNetRuntime.SetupCallback

src/PerfView/GcStats.cs
This PR resolves #616 - by providing more accurate name and description of the condemn reason named so far "Very Fragmented Ephemeral".
=> Fixing Very Fragmented Ephemeral condemn reason name and description

src/TraceEvent/Computers/StartStopActivityComputer.cs
This is part of the work on Application Insights Service Profiler to support Java-based workloads. 
Initially I thought I will piggy back on existing code that knows about Microsoft-ApplicationInsights-Data EventSource and can treat its "Request" events to mark StartStopActivity begin and end. But it turns out that it is not as easy as I have thought to mimic this .NET-based EventSource using EventPipe. 
So instead I am using a generic EventSource-like provider for the same purpose. This seems to work and is very easy to use from the client perspective. All one needs to do is to define a provider with the well-known name ("Microsoft-Diagnostics-ActivityTracking") and use a pair of events named "SomethingStart" and "SomethingStop".
=> Add generic EventSource for start/stop activity tracking

src/TraceParserGen/ETWManifest.cs
=> Fix for TraceParserGen error

CONTRIBUTING.md, README.md, documentation/CodingStandards.md, documentation/Downloading.md, documentation/MakingSupportFilesNugetPackages.md, documentation/OpenSourceGitWorkflow.md, documentation/SettingUpRepoInVS.md, documentation/SimpleGitWorkflow.md
Made a few minor grammar fixes that stuck out in all text files.
=> Updated all text files with grammar corrections and minor revisions 

src/PerfView/Dialogs/RunCommandDialog.xaml, src/PerfView/Dialogs/RunCommandDialog.xaml.cs, src/PerfView/SupportFiles/UsersGuide.htm
This is simple UI to expose FocusProcess command line option in UI.
Addresses #823
=> Added UI for the FocusProcess option

documentation/Downloading.md
The link text has 2.26 instead of 2.0.26
=> Fix PerfView.exe download link text

src/Directory.Build.props, src/TraceEvent/Parsers/ClrTraceEventParser.cs
Original code thought Count was NumHeaps, when it was the generation count.  
Fix issue #853
=> Fix a bogus assert 

src/EtwClrProfiler/ETWClrProfilerX64.vcxproj, src/EtwClrProfiler/ETWClrProfilerX86.vcxproj, src/FastSerialization/FastSerialization.cs, src/FastSerialization/FastSerialization.csproj, src/FastSerialization/MemoryMappedFileStreamReader.cs, src/FastSerialization/MemoryMappedFileStreamWriter.cs, src/FastSerialization/StreamReaderWriter.cs, src/HeapDump/Debugger/DumpDebugging/DumpReader.cs, src/MemoryGraph/graph.cs, src/PerfView/PerfView.csproj
Could not build Perfview locally. Making PR to get review.
=> Remove Span to avoid adding Memory.dll dependency

src/MemoryGraph/graph.cs, src/PerfView/PerfView.csproj, src/TraceEvent/Computers/StartStopActivityComputer.cs, src/TraceEvent/Parsers/ClrTraceEventParser.cs, src/TraceEvent/Symbols/SymbolReader.cs
Removed some workarounds in PerfVIew.csproj, which are the only thing that might cause grief.
=> Some very small changes

src/Directory.Build.props, src/PerfView/PerfViewData.cs, src/PerfView/SupportFiles/UsersGuide.htm
This improves https://github.com/Microsoft/perfview/pull/857.
In particular it does not look up every PDB aggressively.
=> Fixes for support for showing types in the Net OS Heap Alloc view.

src/HeapDump/HeapDumpDLL.csproj
For some reason HeapDumpDLL is not getting signed.  Eliminate needless variation to start.
=> Minor reorganization of HeapDumpDLL.csproj to make uniform with others

src/PerfView/SupportFiles/UsersGuide.htm
https://github.com/Microsoft/perfview/pull/424
=> The default buffer size has been changed

src/PerfView/CommandProcessor.cs, src/PerfView/PerfViewLogger.cs, src/TraceEvent/EventPipe/EventPipeEventSource.cs, src/TraceEvent/Utilities/Cache.cs
=> Small typos and other minor fixes.

src/Directory.Build.props
Increase version numbers to 2.0.42 in preparation for the next release.
=> Bump the Version Numbers

src/PerfView/PerfViewData.cs
Copies the memory views from the ETW handling code into EventPipe.  This is probably worth re-factoring and consuming a single shared source from different file format classes, but for now, this is just a copy.
=> Add managed memory views for EventPipe

src/Directory.Build.props, src/HeapDump/GCHeapDumper.cs, src/HeapDump/ICorDebugGCHeap.cs
Waiting on a new version of CLRMD to be published that contains a fix for the removal of the shared domain from .NET Core 3.0 processes.
This PR updates the version of CLRMD and makes the necessary surface changes to adopt the new version of the package.
=> [WIP] Update CLRMD to version 1.1.37504

src/TraceEvent/EventPipe/EventPipeFormat.md
Clarifying SequenceNumber calculation
=> Update NetTrace format doc

src/PerfView/EventViewer/EventWindow.xaml.cs
FIX: no counters where recognized with regex
FIX: show the counter display name if available
=> Support the 2 types of .NET Core 3.0 counters (Sum and Mean)

src/perfcollect/docker-demo/Dockerfile, src/perfcollect/perfcollect
Includes the commit history as well.
=> Move PerfCollect to the PerfView Repo

src/TraceEvent/Parsers/KernelTraceEventParser.cs
=> Fix typos memmory

src/PerfView/EventViewer/EventWindow.xaml.cs
Fix https://github.com/microsoft/perfview/pull/981#discussion_r312603250
=> PayloadToken for .NET Core collected with dotnet-trace

src/Directory.Build.props
Increase the version numbers for TraceEvent and PerfView in preparation for release.
=> Increase the version numbers for TraceEvent and PerfView.

src/TraceEvent/EventPipe/EventPipeEventSource.cs, src/TraceEvent/TraceEvent.Tests/EventPipeParsing.cs
NetPerf and NetTrace v1 format don't support serializing array typed parameters.
DiagnosticSourceEventSource declares well known events that use array typed parameters
and the runtime serializes EventPipe metadata which claims the events have no parameters.
This is a targetted fix so that EventPipeEventSource will recognize these well-known events
and ignore the empty parameter metadata provided in the stream, treating the events
as if the runtime had provided the correct parameter metadata.
I am concurrently working on a runtime fix and updated file format revision which can
correctly encode these parameter types. However for back-compat with older runtimes we
need this.
=> Parse EventPipe payloads for DiagnosticSourceEventSource events

documentation/Downloading.md
Update download link to the latest version.
=> Update to the latest version

src/TraceEvent/Parsers/ClrTraceEventParser.cs
There is a new MethodDetails event that has been added to CoreCLR. This change adds that event to TraceEvent
Additionally, the BulkType event has been augmented with the ability to represent multidimensional arrays. This change mirrors that change into the TraceEvent library as well.
=> MethodDetails event processing

src/TraceEvent/BPerf/BPerfEventSource.cs
=> Fix BPerf ctor

src/TraceEvent/Samples/10_SimpleEventSourceMonitor.cs
=> Update documentation comments :  10_SimpleEventSourceMonitor.cs

src/TraceEvent/Stacks/SpeedScopeStackSourceWriter.cs
Each sample contains `RelativeTime` and `Metric`.
For some reason, the trace files very often contain overlapping samples. An example: 
* Main: `RelativeTime=0` and `Metric=1`
* Main: `RelativeTime=0` and `Metric=2`
In the initial implementation of the exporter, I assumed that overlapping samples should be modified (see `MakeSureSamplesDoNotOverlap` method) so they just don't overlap.
Last week I've been converting a LOT of TechEmpower trace files to Speedscope and I was hitting this exception a lot:
https://github.com/adamsitnik/perfview/blob/abd56ddbc09106f7be2be32d1861522fdf5b784f/src/TraceEvent/Stacks/SpeedScopeStackSourceWriter.cs#L206-L207
What turned out to be a good solution it to sort the samples by relative time, then metric and later let `GetAggregatedOrderedProfileEvents` …
=> Improve SpeedScope exporter

src/perfcollect/perfcollect, src/perfcollect/tests/build-containers.sh, src/perfcollect/tests/container-entrypoint.sh, src/perfcollect/tests/containers/ubuntu-16.04.dockerfile, src/perfcollect/tests/containers/ubuntu-18.04.dockerfile, src/perfcollect/tests/run-containers.sh
Adds Docker-based tests for Ubuntu 18.04 for perfcollect install and perfcollect collect.
=> Add Very Basic Tests for Perfcollect

src/perfcollect/perfcollect
Minor usability improvement
cc @brianrob
=> perfcollect: ensure usage is printed even when prerequisites are not met

README.md
Update the build status link in the README.
=> Updates From #1135

src/PerfView/EtwEventSource.cs, src/TraceEvent/DynamicTraceEventParser.cs
This reverts commit f4b3490205e060ed1a4de4daf95f049962caecf9.
=> Revert "Introduce compiled shared instances of commonly used regex"

src/PerfView/EtwEventSource.cs, src/TraceEvent/DynamicTraceEventParser.cs
This reverts commit 4873a4d621f3411a63313949317529e128f34afa.
=> Undo Revert of Regex Compilation

src/PerfView/Dialogs/SelectProcess.xaml, src/PerfView/Dialogs/SelectProcess.xaml.cs, src/PerfView/SupportFiles/UsersGuide.htm
Implementation for the #1025 - simple process filter based on the process name and command line.
=> Process selection dialog: implement filter

src/TraceEvent/Parsers/KernelTraceEventParser.cs
In the CreateFile event, the Disposition byte consists of the KM enum for the disposition, not the UM one passed to CreateFileW.
This PR changes the values of the enum in a source-compatible way.
For future reference, the data in the ETW event is taken from the _FLT_IO_PARAMETER_BLOCK.Create struct, and probably another union branch for other file events.
=> [TraceEvent]: Fix CreateDisposition in CreateFile - it's the KM enum

PerfView.sln, src/PerfView/PerfViewData.cs, src/TraceEvent/AutomatedAnalysis/AutomatedAnalysisExecutionContext.cs, src/TraceEvent/AutomatedAnalysis/AutomatedAnalysisIssue.cs, src/TraceEvent/AutomatedAnalysis/AutomatedAnalysisIssueCollection.cs, src/TraceEvent/AutomatedAnalysis/AutomatedAnalysisManager.cs, src/TraceEvent/AutomatedAnalysis/AutomatedAnalysisPerProcessRule.cs, src/TraceEvent/AutomatedAnalysis/AutomatedAnalysisReportGenerator.cs, src/TraceEvent/AutomatedAnalysis/AutomatedAnalysisRule.cs, src/TraceEvent/AutomatedAnalysis/AutomatedAnalysisRuleResolver.cs, src/TraceEvent/AutomatedAnalysis/Extensions.cs, src/TraceEvent/AutomatedAnalysis/IAutomatedAnalysisRuleProvider.cs, src/TraceEvent/AutomatedAnalysis/ProcessContext.cs, src/TraceEvent/AutomatedAnalysis/StackView.cs, src/TraceEvent/TraceEvent.csproj
Implements an automated performance analysis framework that can execute rules against a trace and identify potential performance issues.  This first PR implements the framework and basic report exposure in PerfView.
=> Automated Performance Analysis Framework

src/LinuxEvent.Tests/EventParseTests.cs, src/PerfView/PerfViewData.cs, src/TraceEvent/Stacks/Linux/LinuxPerfScriptStackSource.cs, src/TraceEvent/Stacks/LinuxPerfScriptStackSourceSample.cs, src/TraceEvent/Stacks/Stacks.cs
+Allow perfview to also open perf.data.txt directly
=> Expose CpuNumber in Stack Sample data

src/Directory.Build.targets, src/FastSerialization/FastSerialization.csproj, src/TraceEvent/TraceEvent.csproj
Fixes https://github.com/microsoft/perfview/issues/1194
=> Upgrade Source Link packages

src/perfcollect/perfcollect
- Implement `perfcollect install` support.
- Handle cases where optional executables aren't present on the machine.
=> Perfcollect Support for Alpine Linux

src/Directory.Build.props
Contains updated versions of KernelTraceControl.dll and msdia140.dll.
=> Update Microsoft.Diagnostics.Tracing.TraceEvent.SupportFiles NuGet Package

src/TraceEvent/Microsoft.Diagnostics.Tracing.TraceEvent.props
Add entries for new dependencies msvcp140.dll and vcruntime140.dll
=> Add Missing Entries in Microsoft.Diagnostics.Tracing.TraceEvent.props

src/TraceEvent/TraceLog.cs
Use `ExtendedDataCount` as the event field to point at the container ID instead of `UserContext` since `UserContext` isn't actually persisted into the ETLX.  Also, add de-duplication of container ID into processing of the `ETL` file so that the `ETLX` does not contain duplicated container ID values.
=> Fix ETLX Storage of Container ID

documentation/TraceEvent/TraceEventProgrammersGuide.md
=> Update TraceEventProgrammersGuide.md - fixed several typoes

src/TraceEvent/Symbols/SymbolReader.cs
=> ArrayEquals fix

src/PerfView/ConfigData.cs
Fix infinite recursion for ElementName property
=> Fix infinite recursion for ElementName property

src/TraceEvent/Samples/40_SimpleTraceLog.cs
=> Add fileName to log message

src/CSVReader/CsvReader.cs, src/EtwHeapDump/DotNetHeapDumper.cs, src/HeapDump/GCHeapDumper.cs, src/HeapDump/ICorDebugGCHeap.cs, src/PerfView.Tests/StackViewer/StackWindowTests.cs, src/PerfView/CommandProcessor.cs, src/PerfView/EventViewer/EventWindow.xaml.cs, src/PerfView/Extensibility.cs, src/PerfView/GcStats.cs, src/PerfView/HeapView/HeapDiagram.cs, src/PerfView/ObjectViewer/ObjectViewer.xaml.cs, src/PerfView/ObjectViewer/TreeViewGrid.xaml.cs, src/PerfView/PerfViewData.cs, src/PerfView/StackViewer/CallTreeView.cs, src/PerfView/StackViewer/PerfDataGrid.xaml.cs, src/PerfView/StackViewer/Preset.cs, src/PerfView/StackViewer/StackWindow.xaml.cs, src/PerfView/memory/GCPinnedObjectAnalyzer.cs, src/TraceEvent/Ctf/CtfTracing.Tests/CtfTraceTests.cs, src/TraceEvent/DynamicTraceEventParser.cs, src/TraceEvent/RegisteredTraceEventParser.cs, src/TraceEvent/Stacks/SpeedScopeStackSourceWriter.cs, src/TraceEvent/Stacks/StackSourceWriterHelper.cs, src/TraceEvent/TraceEventSession.cs, src/TraceParserGen/ETWManifest.cs, src/TraceParserGen/TraceParserGen.cs
Set initial capacity for collections where it is predefined
=> Set initial capacity for collections where it is predefined

src/PerfView/StackViewer/StackWindow.xaml.cs
=> Fix preset saving when GroupPat is empty

src/TraceEvent/Parsers/ClrTraceEventParser.cs
New events expected to be part of .NET 6 CoreCLR.
=> Add handling for the JitInstrumentationData events

src/TraceParserGen/ETWManifest.cs, src/TraceParserGen/Program.cs, src/TraceParserGen/TraceParserGen.cs
Trivial trailing whitespace removal.
=> TraceParserGen: Remove trailing whitespace.

src/PerfView/PerfViewData.cs
=> Account for "empty" IisPipelineEvent

src/PerfView/CommandProcessor.cs, src/PerfView/Dialogs/RunCommandDialog.xaml, src/PerfView/Dialogs/RunCommandDialog.xaml.cs
=> Add a command-line option to RunCommandDialog.

src/Directory.Build.props, src/PerfView/PerfView.csproj
React to changes in the analyzers package / DLL.
=> Consume new analyzers in PerfView

src/PerfView/SupportFiles/UsersGuide.htm
Fixed a couple of small grammar errors, spacing and missing words I found while reading through the documentation.
No code change, should be easy MR!
Thanks.
=> Improve documentation

src/perfcollect/perfcollect
=> Explicitly send SIGINT to perf

src/TraceEvent/TraceEventSession.cs
Reading Max ETW Loggers from Registry Key
=> Read Max ETW Loggers from Registry Key

src/PerfView/SupportFiles/UsersGuide.htm
This PR is a (late) answer to #1350 where I promised to include an answer that I've been given in the user guide.
I was quite minimalistic with my changes as I know I miss some knowledge about PerfView, so I did my best not to include false information. Let me know if this is all right and if I could extend my PR with something!
=> Extend GC Heap Net Mem section in UserGuide

src/TraceEvent/TraceLog.cs
=> TraceEvent: remove trailing whitespace in TraceLog.cs

src/HeapDump/Debugger/DumpDebugging/DumpReader.cs
=> Fix arithmetic overflow in DumpReader

src/TraceEvent/Microsoft.Diagnostics.Tracing.TraceEvent.props
Microsoft.Diagnostics.Tracing.TraceEvent.props
Fixes #1449
=> Add ..\build to paths to native binaries in build/.props

src/EtwClrProfiler/CorProfilerTracer.cpp, src/EtwClrProfiler/CorProfilerTracer.h
Fixes the GC Heap Alloc Ignore Free view.
Before:
(Note the presence of `?[]` and `<Unknown>`)
After:
=> Fix failure to identify types defined in mscorlib

src/PerfView/StackViewer/StackWindow.xaml.cs
This says 5% of the metric, but it's actually 2%.
=> Fix comment to reflect code

src/TraceEvent/TraceEvent.Tests/SegmentedDictionary/TestBase.Generic.cs
=> Add summary to end of doc comment

src/TraceEvent/ETWTraceEventSource.cs
PerfView and TraceEvent currently don't consider compressed stack events when calculating the set of NGEN images used by the trace.  This results in missing NGEN image symbols at analysis time.  This PR adds support for compressed stacks during this calculation.
Thanks @vladimir-cheverdyuk-altium for reporting this!
=> Look at compressed stack events when determining NGEN image set

src/PerfView/CommandLineArgs.cs, src/PerfView/CommandProcessor.cs
- Reduce the number of events collected for /GCCollectOnly.
- Add /GCTriggeredStacks to enable stack collection for each GC.
=> Reduce the number of events and stack walks required for /GCCollectOnly

src/PerfView.TestUtilities/DebugAssertionTests.cs
See https://github.com/microsoft/perfview/issues/1571 for details.
=> Disable DebugAssertionTests

README.md, src/CSVReader/CSVReader.csproj, src/EtwClrProfilerSigning/EtwClrProfilerSigning.csproj, src/EtwHeapDump/EtwHeapDump.csproj, src/FastSerialization/FastSerialization.csproj, src/HeapDump/HeapDump.csproj, src/HeapDumpDLL/HeapDumpDLL.csproj, src/LinuxEvent.Tests/LinuxTracing.Tests.csproj, src/MemoryGraph/MemoryGraph.csproj, src/PerfView.TestUtilities/PerfView.TestUtilities.csproj, src/PerfView.Tests/PerfView.Tests.csproj, src/PerfView/PerfView.csproj, src/PerfViewCollect/PerfViewCollect.csproj, src/PerfViewExtensions/GlobalSrc/Global.csproj, src/TraceEvent/BPerf/BPerfEventSource.cs, src/TraceEvent/Compatibility.cs, src/TraceEvent/Ctf/CtfTracing.Tests/CtfTracing.Tests.csproj, src/TraceEvent/Microsoft.Diagnostics.Tracing.TraceEvent.nuspec, src/TraceEvent/Microsoft.Diagnostics.Tracing.TraceEvent.props, src/TraceEvent/Samples/TraceEventSamples.csproj, src/TraceEvent/Samples/packages.config, src/TraceEvent/Stacks/StackSourceWriterHelper.cs, src/TraceEvent/TraceEvent.Tests/TraceEvent.Tests.csproj, src/TraceEvent/TraceEvent.csproj, src/TraceEventPackageSigning/TraceEventPackageSigning.csproj, src/TraceParserGen/TraceParserGen.csproj, src/Utilities/Utilities.csproj
This is the same as https://github.com/microsoft/perfview/pull/1555 targetting feature/perfview-3.0
=> Upgrading to .NET framework 4.6.2

src/PerfView/CommandProcessor.cs, src/PerfView/MainWindow.xaml.cs
We prompt the user to ensure that he's aware of the cancelation.
fixes #1293
=> Added a GUI warning popup when closing PerfView during rundown/zipping

src/HeapDump/GCHeapDump.cs, src/HeapDump/GCHeapDumper.cs
Match heapdump serialization with deserialization settings.
=> Fixed Missed Serialization Overrides

src/PerfView/EventViewer/EventWindow.xaml.cs, src/PerfView/Utilities/LogicalGridDataComparer.cs
=> logical sorting for grid in eventwindow

.ado.yml
Fixes failures in the CI due to NuGet resolution.
=> Install NuGet.exe Version 6.3.0 in CI

.ado.yml
Enable CodeQL in pipelines post merge.
=> Enable CodeQL 3000

src/TraceEvent/Computers/TraceManagedProcess.cs
=> Expose the GenerationCount property on TraceGC for usability

src/PerfView/OtherSources/XMLStackSource.cs, src/PerfView/PerfViewData.cs
Allows for more extensibility of file formats that don't have built-in support in PerfView.
=> Allow for Registration of Custom PerfViewFile Implementations

src/TraceEvent/Symbols/SymbolReader.cs
Avoid integer overflow by using long instead of int to count bytes in symbol reader.
Also, increase the buffer size from 8K to 80K to improve download speed.
Fixes #1732
=> Avoid integer overflow in symbol reader log

src/PerfView/App.cs
=> Fix for server nano which does not support STA Threads.

README.md
=> Remove incorrect Windows 10 SDK version from the README

src/TraceEvent/Ctf/CtfChannel.cs
Various places ignored when `Stream.Read` would read less on first try, and would read more on next attempt (as standard `Stream` behavior).
=> Fix CtfChannel Improper Read Behavior

src/PerfView/PerfView.csproj
=> Detect location of the package using package path property

src/HeapDump/GCHeapDump.cs, src/PerfView/EtwEventSource.cs, src/PerfView/Triggers.cs, src/PerfView/memory/HeapSnapshot.cs, src/TraceEvent/DynamicTraceEventParser.cs, src/TraceEvent/ETWReloggerTraceEventSource.cs, src/TraceEvent/ETWTraceEventSource.cs, src/TraceEvent/Parsers/KernelTraceEventParser.cs, src/TraceEvent/Stacks/AggregateStackSource.cs, src/TraceEvent/Stacks/IndexMap.cs, src/TraceEvent/Symbols/NativeSymbolModule.cs, src/TraceEvent/Symbols/SymbolReader.cs, src/TraceEvent/TraceEventSession.cs, src/TraceEvent/Utilities/Cache.cs, src/TraceEvent/Utilities/command.cs, src/Utilities/OperatingSystemVersion.cs
Hided public utilities namespaces.
Solves:
#1448 
#1049
=> hided all utilities namespaces

src/TraceEvent/Computers/TraceManagedProcess.cs
We witnessed in some customer traces that for .NET Framework, the `ThreadInfo` is not reliable. It is possible that we have only one thread with the `.NET Server GC` thread info and therefore leading PerfView to believe there is only one heap.
Actually, PerfView already has provision to do the right thing during `ProcessGlobalHistory`, but it is not doing its work just because we set the flag and heap counts to the wrong value based on the unreliable data, so this change just gets rid of it.
=> Fix heap count again

src/CSVReader/ETLStackBrowse/Trace.cs, src/PerfView/SymbolReaderHttpHandler.cs, src/TraceEvent/Symbols/NativeSymbolModule.cs, src/TraceEvent/Symbols/PortableSymbolModule.cs, src/TraceEvent/TraceEventSession.cs, src/TraceParserGen/Program.cs
- Remove usage of `BinaryFormatter`.
- Enable certificate revocation checking in PerfView.
- Suppress usage of weak algorithms in places where they are used in existing published protocols for EventSource and symbol/source validation.
=> Fixes for Issues Identified by CodeQL

src/Directory.Build.props, src/PerfView/PerfViewData.cs, src/TraceEvent/AutomatedAnalysis/HtmlReportGenerator.cs, src/TraceEvent/AutomatedAnalysis/StackView.cs
- Refresh the set of analyzers by consuming the latest NuGet package.
- Switch from Regex matching to custom symbol matching to address false positives.
- Rename Automated CPU Analysis to Automated Trace Analysis since it is now possible to analyze blocked time.
=> Additional Automated Analysis Improvements

src/TraceEvent/Symbols/NativeSymbolModule.cs
so that it's created only once.
The original code created a new COM class factory for each loaded PDB. I don't think it was causing memory leaks (they will eventually be released), but it isn't necessary. COM class factories are designed to be reused. This is a small performance improvement (avoiding the extra DllGetClassObject call in most cases)
=> Cache the DIA class factory

src/PerfView/PerfViewData.cs
With the help of TPL TaskWaitSend event we can find all the places that use sync-over-async pattern
=> Add TaskWaitSend.Behavior to AnyStacks

src/TraceEvent/Symbols/NativeSymbolModule.cs, src/TraceEvent/Symbols/SymbolReader.cs, src/TraceEvent/TraceLog.cs, src/TraceEvent/Utilities/WindowsDeviceToVolumeMap.cs
=> Don't try to open Windows PDBs on Linux

src/Directory.Build.props
Set to 3.1 per https://github.com/microsoft/perfview/issues/1823.
=> Increment Version Numbers

src/perfcollect/docker-demo/Dockerfile
- Update to Ubuntu 22.04.
- Update to .NET 7.
=> Update perfcollect docker-demo

src/TraceEvent/Computers/TraceManagedProcess.cs
BGCs shouldn't accumulate the FGCs' Pause Times to compute their corresponding % Pause Time in GC. 
Also, fixes an error with the wrong index being used for the BGC. 
CC: @Maoni0 @cshung
=> Added a fix for the Computation of the Pause Time % in GC for GCs by not including FGCs

documentation/TraceEvent/TraceEventLibrary.md
to match what's in csproj file
=> Update information about supported platforms

src/TraceEvent/ETWReloggerTraceEventSource.cs
Add float type to SetPayload functionality when relogging.
=> Add float as a SetPayload type in Relogger

src/TraceEvent/TraceEventSession.cs
Protect initialization of TraceEventSession.ProviderNameToGuid and TraceEventSession.ProviderGuidToName with a lock to allow for multiple concurrent callers.
This does not change the concurrency guarantees for TraceEvent, but does allow for multiple concurrent callers of TraceEventSession.EnableProvider on different instances of TraceEventSession, where prior to this change it was possible for this to produce a crash on insertion into the Dictionary or SortedDictionary.
Reported via https://github.com/dotnet/runtime/issues/91769.
=> Protect Initialization of TraceEventSession Provider Lists

documentation/TraceEvent/TraceEventLibrary.md
A simple cleanup, mostly whitespaces and some basic formatting fixes.
=> Fix Microsoft.Diagnostics.Tracing.TraceEvent MD formatting

documentation/TraceEvent/TraceEventLibrary.md
=> Update info about versions for TraceEvent.

src/perfcollect/perfcollect
Fixes https://github.com/microsoft/perfview/issues/1850
=> Support ubuntu 22.04 in perfcollect

src/PerfView/PerfViewData.cs, src/TraceEvent/Parsers/ClrTraceEventParser.cs
New event introduced in https://github.com/dotnet/runtime/pull/94737
=> Support WaitHandleWait events

src/PerfView.Tests/Utilities/PerfViewTestBase.cs, src/PerfView/MainWindow.xaml.cs
=> Fix PerfView not completely closing after closing the main window.

src/perfcollect/tests/containers/mariner-2.0.dockerfile
Cherry pick from https://devdiv.visualstudio.com/DevDiv/_git/perfview/pullrequest/521246.
=> Pin docker image for PerfCollect tests

src/Directory.Build.props, src/PerfView/PerfView.csproj, src/TraceEvent/Samples/TraceEventSamples.csproj
AzureCoreVersion 1.35.0 -> 1.36.0
AzureIdentityVersion 1.10.2 -> 1.10.4
MicroBuildCoreVersion 0.2.0 -> 0.3.1
MicrosoftNETCorePortableCompatibilityVersion 1.0.1 -> 1.0.2
MicrosoftIdentityClientVersion 4.54.1 -> 4.58.1
MicrosoftIdentityClientExtensionsMsalVersion 2.31.0 -> 4.58.1
MicrosoftIdentityModelTokensVersion 6.22.0 -> 7.1.2
MicrosoftIdentityModelJsonWebTokensVersion 6.22.0 -> 7.1.2
MicrosoftSourceLinkGitHubVersion 1.1.1 -> 8.0.0
MicrosoftWin32RegistryVersion 4.4.0 -> 5.0.0
SystemCollectionsImmutableVersion 1.7.1 -> 8.0.0
SystemDiagnosticsDiagnosticSourceVersion 6.0.1 -> 8.0.0
SystemMemoryVersion 4.5.4 -> 4.5.5
SystemReflectionMetadataVersion 1.8.1 -> 8.0.0
SystemReflectionTypeExtensionsVersion 4.3.0 -> 4.7.0
SystemRuntimeVersion 4.3.0 -> 4.3.1 …
=> Version updates for most packages to latest versions

.ado.yml
=> Update to current .NET SDK in pipelines

src/TraceEvent/EventPipe/EventPipeFormat.md
=> Correct Nettrace magic

src/PerfView/GcStats.cs, src/TraceEvent/Computers/TraceManagedProcess.cs
This will work with the new condemn reason introduced in https://github.com/dotnet/runtime/pull/98954.
=> Condemned Reason for Aggressive GC

src/Directory.Build.props
Fixes https://nvd.nist.gov/vuln/detail/CVE-2024-29992.
=> Update Azure.Identity to 1.11.0

src/PerfView/PerfViewData.cs
Added ability to click ActivityIds for requests in all request tables that opens the Events window with that ActivityId as a text filter (along with start/end times set). This is similar to what IIS Stats does.
From a zipped PerfView trace:
and clicking one of the request IDs:
Behavior is identical for a nettrace file as well.
=> Add clickable ActivityIDs to requests in ASP.NET Core Stats view

src/PerfView/MainWindow.xaml.cs
=> Open external content in default browser

src/Directory.Build.props
Update to the following packages:
- Azure.Identity 1.11.4
- Microsoft.Identity.Client 4.61.3
- Microsoft.Identity.Client.Extensions.Msal 4.61.3
=> Update Dependencies to Address Vulnerabilities

README.md
=> Specify Minimum .NET Framework Version

src/TraceEvent/Microsoft.Diagnostics.Tracing.TraceEvent.nuspec
=> Add Microsoft.Diagnostics.NETCore.Client to the TraceEvent nuspec

documentation/Downloading.md
Set the direct download link for `PerfView.exe` in `documentation/Downloading.md`.
=> Update the Direct PerfView Download Link

README.md, documentation/Scenarios.md
- Scenario documentation to help users get started and set expectations.
- `README` clean-up pass.
=> Documentation Updates

src/PerfView/SupportFiles/UsersGuide.htm
Corrected a few grammatical errors, etc.
=> Updating the PerfView documentation

src/PerfView/MainWindow.xaml.cs
This ensures that if the URL changes, we'll automatically get the update.
=> Use The fwlink Version of the Privacy Policy URL

src/Directory.Build.props
Address CVE in System.Text.Json.  More details at https://github.com/dotnet/announcements/issues/329.
=> Address CVE-2024-43485 in System.Text.Json

src/PerfView/GcStats.cs
Reverts microsoft/perfview#2140 - need to test a bit more and fix more timing issues.
=> Revert "Added missing time info fields in the Raw XML View in GCStats"

src/PerfView/CommandProcessor.cs, src/TraceEvent/TraceEventSession.cs
Fixes #2147.
This ensures that if PerfView crashes or is killed, the file size limitation will still be respected.
=> Implement /RundownMaxMB Using an ETW-based File-Size Limitation

src/PerfView/CommandProcessor.cs
Rundown occurs in a series of steps.  Each step enables a provider that can then produce events that flow into the session.  When a session is size-constrained, as is the case with /RundownMaxMB, when the session reaches is maximum size, the session is stopped.  Further attempts to enable a provider will fail with the error `0x80071069: The instance name passed was not recognized as valid by a WMI data provider.`  These failures are expected, and are how handled by PerfView.
cc: @suprak
=> Ensure that a small /RundownMaxMB value doesn't break rundown.

src/TraceEvent/TraceLog.cs
Before this pr the unhandled event handler will be registered repeatedly as long as DispatchClonedEvent is called causing very high cpu usage
=> Fixes that repeatedly adding unhandled event handler to TraceLog to real time session conversion

src/PerfView/SupportFiles/UsersGuide.htm
Fixing a typo in the release notes
=> Fixing a typo in the release notes

src/TraceEvent/TraceEventNativeMethods.cs, src/TraceEvent/TraceEventSession.cs
=> Fix GetActiveSessionNames to handle ERROR_MORE_DATA

documentation/Downloading.md
Provide instructions on how to script download of PerfView.exe using curl.
=> Update Download Guidance

src/TraceEvent/Symbols/NativeSymbolModule.cs, src/TraceEvent/Symbols/PortableSymbolModule.cs, src/TraceEvent/TraceEventSession.cs, src/TraceParserGen/Program.cs
Some additional CodeQL suppressions as the suppression format has changed.
=> More CodeQL Suppressions

src/TraceEvent/EventPipe/NetTraceFormat.md
Some minor corrections where descriptive summary parts of the doc were out-of-sync with the detailed specifications. There is no change in the underlying format.
=> Revise NetTraceFormat.md for clarity
